### ISSUE TITLE
Catch another case with non-optional outputs

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1009]
See error message

at simple_engine.py:76

When the previous outputs are not optional this should throw

```
               step_context.log.info(
                    (
                        'Not all inputs covered for {step}. Not executing. Output need for '
                        'inputs {expected_outputs}'
                    ).format(expected_outputs=expected_outputs, step=step.key)
                )
```

**Comment by alangenfeld** [comment]
Since we throw on missing non-optional when processing the outputs of a step in `_error_check_step_output_values` called by `_execute_steps_core_loop`, we shouldn't ever get to processing the next step. The only case where we hit simple_engine.py:76 is when the outputs in the previous step were optional. 

Is this incorrect? Did you see this fail? Do you think we should add another check here?

**Comment by schrockn** [comment]
I ran in this while doing re-executions while developing PR1011

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )
