### ISSUE TITLE
Improve asset partition state visibility

### ISSUE THREAD

**Issue by aroig** [dagster-io/dagster#10157]
### What's the use case?

I maintain a dagster pipeline of about 30 assets and 10's to 100's of static partitions. It would be very helpful for us to have visibility of the state of each asset partition on dagit as in "up to date", "upstream changed" (some dependency is newer or out of date), or "missing", in order to know we are working on fresh data, and trigger re-materializations when necessary.

The visibility aspect matters to us, even if we automate re-materializations of downstream assets via a reconciliation sensor. We still want to have a way to check whether anything is stale or missing.

### Ideas of implementation

Currently the graph view does not show "upstream changed" state for partitioned assets. This is tracked here #9374. The "upstream changed" tag would be helpful, but only solves our problem partially: We would not see which partitions are the ones that need to be re-materialized.

Additionally, the state shown in the partition view, either on the materialize dialog (the green and red bar), or the Partitions page for a job (the dot matrix), does not show current state, it shows something close to state aggregated from runs since last backfill, I believe. It falls short in the following ways:
  - Does not see full state. If I run a backfill to materialize one asset, I loose visibility of everything else!
  - Does not show "upstream changed" state. Even if everything is green, some partitions may still be stale.

Getting a representation of the current state as in "up to date", "upstream changed", "missing" on the partition view (both the bar and the matrix) seems a good way to solve our visibility problem.

### Additional information

I am willing to contribute work on this. Do you have any plans or feedback on how to approach it? I realize it may involve extending graphQL APIs or changing db schemas.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
> Additionally, the state shown in the partition view, either on the materialize dialog (the green and red bar), or the Partitions page for a job (the dot matrix), does not show current state, it shows something close to state aggregated from runs since last backfill, I believe.

That's not the intended behavior in general, so if you're experiencing this, it might be a bug? The intended behavior is that the partition views should should reflect the entire history.  I.e. if a partition was materialized before the most recent backfill, but not materialized in the most recent backfill, it should still show up as green in the bar.   This applies to the partitions bar on the Asset Details page, the partitions bar that shows up when you Materialize partitioned assets, and the partitions bar on the Partitions tab of the Job page.

> Does not show "upstream changed" state. Even if everything is green, some partitions may still be stale.

This is definitely a gap.  If you'd be up for working on this, that would be awesome.

The biggest challenge is managing the performance of this: any materialization of any partition of an upstream asset can affect the "Upstream Changed" status of the asset in question.  To avoid a really slow experience, I think we should aim to do two things:
- Require the user to click a button or something to show the per-partition "Upstream Changed", rather than always showing it when the page is loaded.
- Find a way to implement this that avoids submitting a separate database query per partition.  Bonus points if we can do it all in one query and/or avoid scanning any event log entries we don't strictly need to. A few ways we might avoid scanning some records:
  - Once we've found an upstream partition materialization that occurred after the latest materialization of the partition we're trying to determine "Upstream Changed" for, we don't care about other "Upstream Changed" records for that partition.
  - We don't need to look at any records that occurred before the materialization of the partition in question (though this gets a more complicated with PartitionMappings where an upstream partition maps to multiple downstream partitions).

If you think you'll have time to take this on, it might be useful to schedule some time to chat about it.

cc @prha @bengotow

**Comment by aroig** [comment]
Thank you for the quick answer @sryza !

> That's not the intended behavior in general, so if you're experiencing this, it might be a bug? The intended behavior is that the partition views should should reflect the entire history. I.e. if a partition was materialized before the most recent backfill, but not materialized in the most recent backfill, it should still show up as green in the bar. This applies to the partitions bar on the Asset Details page, the partitions bar that shows up when you Materialize partitioned assets, and the partitions bar on the Partitions tab of the Job page.

Ah ok, I was thinking mostly about the partition matrix on the Job > Partitions page. I realize now that the partitions bar on the assets details and Materialize dialog behaves differently, and does seem to accumulate beyond last backfill, as you mention. I opened 2 bug reports describing details of unexpected behaviour on both cases in #10159 and #10161. There is also #10147, which seems related and I missed yesterday.

There seems to be a lot going on around this ticket. A summary of work to do:
1. Address partition bar and matrix bugs reported in #10159 , #10161 and maybe #10147
2. Address racy "upstream changed" asset tag for non-partitioned assets in #10160 (this one I found out today)
3. Extend "upstream changed" asset tag to work on partitioned assets #9374
4. Show "upstream changed" state on the partition bar for the asset details, Materialize dialog, and Job > Partitions page.

Do you agree? Did I miss anything?

> If you think you'll have time to take this on, it might be useful to schedule some time to chat about it.

Well, there is a lot of work in 1 to 4 above :laughing: I can spend some of my spare time working on this. If we agree on an overall plan, I can make contributions in small pieces. Give me a few days to familiarize a bit better with the relevant parts of the code, before we chat.

Ah, by the way, despite all the complaining in this ticket, thank you for building this great piece of software! :blush:

**Comment by sryza** [comment]
@aroig that all sounds right to me. I left some comments on the individual tickets as well.

> Well, there is a lot of work in 1 to 4 above 😆 I can spend some of my spare time working on this. If we agree on an overall plan, I can make contributions in small pieces. Give me a few days to familiarize a bit better with the relevant parts of the code, before we chat.

That sounds great.

**Comment by simonvanderveldt** [comment]
Seems like this has gotten worse with the latest releases? For Jobs that are used for Assets it seems like one can no longer see the Ops, it only shows the state of the Runs in the partitions/matrix view (I believe that's what it's called)
![image](https://user-images.githubusercontent.com/204286/214890806-ecaa12e9-26fc-421a-98ee-9a3c68d29a1a.png)

For the Assets themselves it's even worse, you only have a sort of list on the left side that again only shows the aggregate/Partition, no details per Op (we use graph backed assets)
![image](https://user-images.githubusercontent.com/204286/214891093-3aed2a1c-5193-450d-a1d4-c70f69430ac1.png)

And these are only the pages for specific assets, the Assets overview page also contain very little useful information to enable being in control of the state over everything. Any run done will result in the "Materialized" column being updated/no longer showing "stale" even when it's a Run for  partition from years ago, so the latest partitions can all be missing/stale and the overview will happily state "Materialized <timestamp today>".

Are these accidental regressions or was this planned? I can't find any clear indication of what the plan/roadmap is. We like the concept/idea of Assets, but what's currently there is lacking too much for proper day to day operation.

**Comment by sryza** [comment]
Hey @simonvanderveldt - asset partitions are a very active area of development for us. Thanks for bearing with us on them.

>  For Jobs that are used for Assets it seems like one can no longer see the Ops, it only shows the state of the Runs in the partitions/matrix view (I believe that's what it's called)

This was a deliberate change, based on a couple observations and beliefs:
* For multi-assets, the op-based view wasn't granular enough, because it would show a single op when there might be multiple assets.
* Users who had defined their jobs in terms of assets often found it confusing to see their partitions page in terms of ops.
* From a monitoring perspective, theoretically, the entities that matter are the assets, so if users are trying to find out what's "missing", the asset status represents that.

That said, I'm curious to hear more about your situation. Maybe there's a middle ground we can provide.

> For the Assets themselves it's even worse, you only have a sort of list on the left side that again only shows the aggregate/Partition, no details per Op (we use graph backed assets)

Is the main issue here that you can't see the status of the individual ops, or are there other issues as well?

> And these are only the pages for specific assets, the Assets overview page also contain very little useful information to enable being in control of the state over everything. Any run done will result in the "Materialized" column being updated/no longer showing "stale" even when it's a Run for partition from years ago, so the latest partitions can all be missing/stale and the overview will happily state "Materialized ".

I don't think it ever worked differently, but I definitely agree this is a big gap. @bengotow and @clairelin135 are actually currently working on addressing this, and I believe we're aiming to show more granular status within a week or two.

**Comment by simonvanderveldt** [comment]
Hi @sryza Thanks for the reply! We have a call planned with you for next week Tuesday (planned by my colleague @yeachan153). We'll make sure to have clearly written down the issues/challenges we ran into and the questions we have. Once we've had the call I can write down the summary of the relevant parts here. Does that sound OK to you?

**Comment by sryza** [comment]
@simonvanderveldt that sounds great

**Comment by sryza** [comment]
Since this issue was filed, we shipped functionality that shows the number of materialized, missing, and failed partitions for each partitioned asset.

We already have https://github.com/dagster-io/dagster/issues/9374 to track stale assets, so I'm going to close this issue now.  Feel free to file followup issues for any asset partition state visibility issues that are not fixed or covered by that issue.
