### ISSUE TITLE
Black no longer formatting tutorial files

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1053]
![Screenshot 2019-03-28 10 47 13](https://user-images.githubusercontent.com/28738937/55180577-164a3280-5147-11e9-9773-cce85c65aa5f.png)

Confirmed that it doesn't work

**Comment by mgasner** [comment]
Basically the reason this isn't working is https://github.com/dagster-io/dagster/blob/master/.pre-commit-config.yaml#L7: I added this line because black completely ignores the `--excludes` when a file is explicitly passed on the command line, and the pre-commit hook by default passes all of the files that have changed (including ones that should be excluded) on the command line. I think we can fix this by slightly abusing the pyproject.toml system and adding one that does nothing but config black to the /dagster/dagster/tutorials directory.

**Comment by schrockn** [comment]
We can also considering abandoning pre-commit for now.

**Comment by mgasner** [comment]
Going to propose that we solve this by just formatting everything with uniform --line-length 100.
