### ISSUE TITLE
make asset reconciliation sensor work with SourceAssets

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#10724]

**Comment by linssendane** [comment]
Hi @sryza , do you have any updates on this? :)

We want to create workflows by daisy-chaining assets across several repositories. I feel like using asset reconciliation sensors would be the best / clearest / easiest way to do it!

**Comment by sryza** [comment]
@OwenKephart - you recently introduced some fixes here - is that right? I know that there are some scenarios where the behavior is still wonky (e.g. propagating staleness across code locations). But I don't believe we blatantly error in as many cases? Do you know what works and what doesn't?

**Comment by OwenKephart** [comment]
Hi! Currently, we essentially ignore the presence of source assets in the asset reconciliation logic (i.e. the sensor will do the same thing with or without a source asset defined), but the medium-long term vision is definitely to allow for workflows like you're imagining. Eventually, this would be achieved by separating out the reconciliation logic into a Daemon, but it's possible that some easier short-term solutions exist. I'll take a look into this in the coming weeks :)

**Comment by linssendane** [comment]
Thanks, @OwenKephart ! Much appreciated! :)

**Comment by linssendane** [comment]
Hi Dagster crew!

For your radar: https://github.com/dbt-labs/dbt-core/discussions/6725

dbt labs are working on multi-project deployments. I imagine that this dagster feature will become even more useful when that's the case! :)

**Comment by OwenKephart** [comment]
For some extra context, right now, the sensor does not look at source assets because it cannot distinguish between a source asset that encodes a software-defined asset that exists in some other code location (in this case, there will be upstream materialization events to consider) and a source asset that encodes an asset that does not have a definition at all (in this case, there will never be materialization events to look for)

In the medium term, we're hoping to move this logic into a daemon (which can see all code locations), which would eliminate this distinction. It's also possible that there is some reworking of the logic we could do to make this distinction between different types of source assets irrelevant.

**Comment by sryza** [comment]
Our main branch and the upcoming 1.3 release contain `AutoMaterializationPolicy`s and the auto-materialization daemon, which subsume `build_asset_reconciliation_sensor`. Auto-materialization policies correctly handle source assets and auto-materialization across code locations.

**Comment by linssendane** [comment]
> Our main branch and the upcoming 1.3 release contain `AutoMaterializationPolicy`s and the auto-materialization daemon, which subsume `build_asset_reconciliation_sensor`. Auto-materialization policies correctly handle source assets and auto-materialization across code locations.

Brilliant!! Thank you so much 🙏
