### ISSUE TITLE
InputDefinition and OutputDefinition have different parameter order

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1087]
`InputDefinition` takes `name, dagster_type, ...`

`OutputDefinition` takes `dagster_type, name, ...` 

we should fix this early before the extant client code makes it painful to migrate later...

**Comment by schrockn** [comment]
So this was actually a deliberate decision, because the most common case is that there is a single OutputDefinition and it gets the default name 'result'. I agree this is somewhat confusing and inconsistent (there are actually a few of these at the top level). This is worth discussing. I actually think the best solution may be to *require* kwargs in certain situations (most notably when naming an OutputDefinition)

**Comment by mgasner** [comment]
I'd like to resolve this sooner than later, and I think that the require kwargs approach is probably the right one. I'm a little skeptical of the default name "result", because most of my interactions with it to date have features someone's confusion over where result should come from (for instance in error messages).

**Comment by mgasner** [comment]
because we now have the python3 DSL, which covers the simple case:

```@solid
def my_cool_solid(context, cooltyped_input: CoolInputType) -> CoolOutputType:
    ...
```

the argument for the inconsistency now applies only to py27, and I think it's ok to impose slightly more boilerplate on this user group, i.e., they will have to write:

```output_defs=[OutputDefinition(dagster_type=CoolOutputType)]```

instead of
```output_defs=[OutputDefinition(CoolOutputType)]```

**Comment by sryza** [comment]
I think the ship has sailed on this one
