### ISSUE TITLE
dagster-dbt fails when we change the target-path in the dbt_project.yml

### ISSUE THREAD

**Issue by f-tremblay** [dagster-io/dagster#10918]
### Dagster version

dagster, version 0.15.0 (I installed dagster = "1.1.5" and dagster-dbt = "0.17.5" )

### What's the issue?

dagster-dbt does not work correctly when we change the target-path (which is useful when dbt is not allowed to write in the project dir)

The value of target-path in the dbt_project.yml is not used 
a workaround is to also set the config target_path for dbt_cli_resource, but I think many dbt users will want to use dbt_project.yml

### What did you expect to happen?

A user should be able to change the value of target-path in the dbt_project.yml, (without having to also change the target_path in the configs for the dbt_cli_resource).

### How to reproduce?

1. change the value of target-path in the dbt_project.yml, (and not in the configs for dbt_cli_resource), 
2. run dbt with dagster (dbt_run_op, dbt_test_op)
3. get the following error:

> dagster_dbt.errors.DagsterDbtCliOutputsNotFoundError: Expected to find file at path /opt/dagster/dagster_home/dbt_test_project/target/run_results.json
  File "/opt/venv/lib/python3.8/site-packages/dagster/_core/execution/plan/execute_plan.py", line 266, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/opt/venv/lib/python3.8/site-packages/dagster/_core/execution/plan/execute_step.py", line 388, in core_dagster_event_sequence_for_step
    for user_event in check.generator(
  File "/opt/venv/lib/python3.8/site-packages/dagster/_core/execution/plan/execute_step.py", line 94, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/opt/venv/lib/python3.8/site-packages/dagster/_core/execution/plan/compute.py", line 177, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn):
  File "/opt/venv/lib/python3.8/site-packages/dagster/_core/execution/plan/compute.py", line 145, in _yield_compute_results
    for event in iterate_with_context(
  File "/opt/venv/lib/python3.8/site-packages/dagster/_utils/__init__.py", line 460, in iterate_with_context
    next_output = next(iterator)
  File "/opt/venv/lib/python3.8/site-packages/dagster_dbt/ops.py", line 96, in dbt_run_op
    dbt_output = context.resources.dbt.run()
  File "/opt/venv/lib/python3.8/site-packages/dagster_dbt/cli/resources.py", line 145, in run
    return self.cli("run", models=models, exclude=exclude, select=select, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/dagster_dbt/cli/resources.py", line 90, in cli
    return execute_cli(
  File "/opt/venv/lib/python3.8/site-packages/dagster_dbt/cli/utils.py", line 145, in execute_cli
    parse_run_results(flags_dict["project-dir"], target_path)
  File "/opt/venv/lib/python3.8/site-packages/dagster_dbt/cli/utils.py", line 167, in parse_run_results
    raise DagsterDbtCliOutputsNotFoundError(path=run_results_path)

### Deployment type

Other Docker-based deployment

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @f-tremblay ! I think (unfortunately) that there's no easy fix here, and that what you're experiencing is (mostly) expected behavior.

If you're using `load_assets_from_dbt_project`, then we could probably parse out the `target-path` from the dbt_project.yml file, but even that would be fairly involved as it's not always going to be a raw string underneath that key in the yaml file (for example, you can have `target-path: "{{ env_var('DBT_TARGET_PATH') }}" `, so we'd need to hook into dbt's jinja templating stuff in order to reliably understand the target-path.

It gets even nastier if you're using `load_assets_from_dbt_manifest`, where we might not even have easy access to the dbt project until it comes time to execute the dbt assets themselves (right now, we basically always will, but this isn't something we necessarily want to be locked into).

For now, I'm going to close this issue as a "wont-fix", as the expected (although unideal) workflow for changing the target path is to change it in both the dbt_project.yaml file and the resource definition. I'm definitely open to suggestions here, I just don't see any particularly good implementation plan given what we're able to get from dbt.

**Comment by NicolasPA** [comment]
Have you tried setting the target path with the env var DBT_TARGET_PATH ?
Setting it in `dbt_project.yml` is deprecated in v1.5.
https://docs.getdbt.com/reference/project-configs/target-path (select v1.5)

**Comment by rexledesma** [comment]
Just a note, this problem is fixed in `dagster-dbt>0.20.13`, with our new `DbtCliResource`, which can be used with `@dbt_assets` and regular `@op`'s.

- You can [customize the `target_path`](https://docs.dagster.io/_apidocs/libraries/dagster-dbt#dagster_dbt.DbtCliResource.cli) when invoking `DbtCliResource.cli(...)`
- `DbtCliResource` respects the usage of `DBT_TARGET_PATH`: https://github.com/dagster-io/dagster/pull/16744
