### ISSUE TITLE
Unable to materialize any asset manually using the Materialize button

### ISSUE THREAD

**Issue by alexismanuel** [dagster-io/dagster#11157]
### Dagster version

dagster, version 1.1.6

### What's the issue?

When I try to materialize an asset selection of my job, the Materialize selected button does not create the popup to choose which partitions to run:
<img width="984" alt="image" src="https://user-images.githubusercontent.com/22666624/207909372-f31926d2-8b53-4ac3-a439-16e7da9f132f.png">

My assets are defined with the following partition:
```python
fifteen_minute_partitions = TimeWindowPartitionsDefinition(
    cron_schedule="*/15 * * * *",
    start=datetime(2022, 1, 1, 0, 0, 0),
    fmt="%Y-%m-%d %H:%M",
    timezone="Europe/Paris",
)
```

My guess is that the server encounters a timeout while trying to respond because of the large number of partitions.
Here is the http request which is in failure state (502 HTTP code):
<img width="667" alt="image" src="https://user-images.githubusercontent.com/22666624/207910404-5401c2ec-2890-437f-84de-ecba7feb16ce.png">

### What did you expect to happen?

I expected the run popup to appear

### How to reproduce?

Select assets with large number of partitions (over 100K in my case)

### Deployment type

Open Source

### Deployment details

K8S over GKE

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@bengotow - thoughts on whether there's a straightforward way to make this faster?

This is a scenario where operating on ranges instead of individual partitions might speed things up significantly.

**Comment by bengotow** [comment]
Quick update - even on localhost a query for 4 assets with this partition definition takes 32s to respond, so I think we can rule out problems with the config / collision parts of the query.

I think we can restructure this to make it more usable -- this initial loader request just asks for the names of the partition dimensions so that the UI doesn't shift as the data loads in, and it looks like asking for the dimension names is causing the backend to build all the partition keys (which aren't actually returned in this query).

It looks like it takes ~3.1s to retrieve the `33573` partition keys of each of the four assets, and it feels like we could make that faster too, given that they are the same for all four assets. There's a good chance we're spending all this time string formatting the dates.

@sryza there may be broader improvements we need to make to support super-large partition key sets (eg: sending down a representation like "2022-01-01 , */15 * * * *" instead of sending down all the keys, etc.) but we can probably get 50% better performance with some adjustments to the current approach.
