### ISSUE TITLE
Dagster intermittently shows non-applicable "definitions reloaded" banner

### ISSUE THREAD

**Issue by adam-bloom** [dagster-io/dagster#11648]
### Dagster version

1.1.9

### What's the issue?

The "Definitions Reloaded" banner is triggered inadvertently on some dagster page loads. This occurs when running more than 1 replica of dagit.

### What did you expect to happen?

I do not expect to see this banner on page load unless definitions have in fact changed.

### Deployment type

Dagster Helm chart

### Deployment details

dagit replica count: 2

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by cjduffett** [comment]
Hello! My team is also experiencing this issue. The "Definitions reloaded" message continuously appears and re-appears in our deployed environments. For redundancy we are running 2 copies of Dagit using AWS ECS Fargate + an ALB. We are also running 2 copies of each gRPC repository using ECS Fargate + an NLB.
![defs-reloaded](https://user-images.githubusercontent.com/5651138/214913068-03715176-8e69-40d9-9241-1bb8882a9ed3.png)

We started seeing this bug after we upgraded to Dagster 1.1.7, and we are _still_ seeing this issue after upgrading to the latest Dagster 1.1.13.

In the Dagster changelog I see a [bugfix in version 1.1.8](https://github.com/dagster-io/dagster/blob/master/CHANGES.md#bugfixes-5):
> Fixed a bug where “Definitions loaded” notifications would constantly show up in cases where there were multiple dagit hosts running.

I'm wondering if this is still an issue with running multiple copies of the Dagit host? Could this also be caused by running multiple copies of each gRPC host?

**Comment by flvndh** [comment]
Getting the same with version 1.1.18

**Comment by cjduffett** [comment]
Same, we just upgraded to 1.1.18 yesterday and still experiencing this issue. 🔁

**Comment by prha** [comment]
Just missed the cutoff for `1.1.20` (tomorrow), will make it in for `1.1.21` (next week)

**Comment by prha** [comment]
I think this should be closed now with `1.1.21` that was just released ... Please reopen if you still are experiencing this issue

**Comment by abi-mutinex** [comment]
@prha I am [facing something similar in my OSS Dagster deployment](https://dagster.slack.com/archives/C01U954MEER/p1690947604962979) on k8s. We are on 1.3.9.

We have a `replicaCount` of 3.

I'm not sure why is this happening if it was fixed. Could you help?
