### ISSUE TITLE
Make Dagster compatible with AWS RDS Proxy

### ISSUE THREAD

**Issue by ArnoudItility** [dagster-io/dagster#11762]
### What's the use case?

RDS Proxy can be used as a connection pooler in order to reduce the number of database connections on AWS. Unfortunately, Dagster is currently not compatible with RDS Proxy as RDS Proxy does not support receiving CLI options. 

### Ideas of implementation

Remove CLI options when using RDS

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by vi-malii** [comment]
Hi, not so long ago I faced the same problem and it seems that the problem is still relevant and hasn't been solved yet. As a workaround, I decided to use pgbouncer as a connection pooler. In my situation, I had to use this Helm chart  https://github.com/icoretech/helm/tree/main/charts/pgbouncer to deploy the application to the EKS cluster, 
since Dagster also deployed to eks.
The only thing is, I paid attention to this part of the configuration. Without ignore_startup_parameters, it doesn't work.

pgbouncer: 
    ignore_startup_parameters: options,extra_float_digits
    
After that, simply connect Dagster using the service address of pgbouncer like pgbouncer.namespace.svc.cluster.local 
and check how it works.

**Comment by ArnoudItility** [comment]
Hi, 

I took the initiative myself to find a quick fix for this as well. However, I did not want to differ from RDS Proxy due to simplicity and maintainability. I made a patch file that got the job done, the change was relatively simple! Just change the way you pass on the timeout options in the event_log.py, run_storage.py and schedule_storage.py. (Dagster version was 1.3.2 when I made the patch, code could look slightly different now). 

![image](https://github.com/dagster-io/dagster/assets/123000266/aae1ff50-92b6-40b4-b44f-29f99745a4d5)
