### ISSUE TITLE
Getting negative numbers for process execution time

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1177]
<img width="372" alt="Screenshot 2019-04-08 19 27 15" src="https://user-images.githubusercontent.com/28738937/55769111-62914e80-5a34-11e9-99df-f58147cdebc6.png">

**Comment by bengotow** [comment]
I actually fixed this here and forgot to mention it: https://github.com/dagster-io/dagster/commit/63a2b50809418935e06f84eb91e08c069592ea70#diff-843044aee269f4da4ec9de62c9b5ba32R51. Gonna close this!

**Comment by bengotow** [comment]
Should be mentioned though that this will just make it say "0ms" - the real issue is that the events actually DO have weirdly flipped timestamps. The "end" event is emitted before the "start" event . We'll need to look in to this later.

![image](https://user-images.githubusercontent.com/1037212/55987812-31449880-5c57-11e9-8d7d-245e30edb6b7.png)
