### ISSUE TITLE
Add a way of specifying different metadata per partition when materializing a partition range

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#12498]

**Comment by NicolasPA** [comment]
This is limiting in our case.

We love backfilling with the feature "Pass partition ranges to single run" because we save a lot of time by starting a single job on our infrastructure.

Sometimes 1/100 of partitions fail to execute, this currently results in the 100 partitions still being marked as not materialized.
We would like to be able to tell Dagster by ourselves if a partition was successfully materialized or not, so we can see at the end of the backfill that 99 partitions were materialized and only 1 is missing with error.

**Comment by toimcio** [comment]
A related problem is being able to supply a DataVerstion per partition in the case of a single-run-backfill for multiple partitions. There already exists a DataVersionsByPartition class, so if it were possible to pass this to the Output object in these cases, it would really make working with DataVersion driven pipelines much more viable.

**Comment by sryza** [comment]
Closing as a duplicate of https://github.com/dagster-io/dagster/issues/18123. Even though this one is older, that one has more upvotes and details.
