### ISSUE TITLE
dialog for selecting a non-time-partition is slow with large numbers of partitions

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#12756]

**Comment by bengotow** [comment]
Hmm @salazarm I wonder if this is just because `TagSelector` isn't virtualized? I know for the other partition picker in the Launchpad we had to use a react-virtualized list inside the dropdown (https://github.com/dagster-io/dagster/blob/master/js_modules/dagit/packages/ui/src/components/Suggest.tsx#L53:L53). Maybe we could copy bits of that in.

**Comment by salazarm** [comment]
Ah yeah good point, definitely this.
