### ISSUE TITLE
A lot of tqdm stdout freezes Dagit

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#13026]
### Dagster version

1.2.2

### What's the issue?

I'm training a DL model with pytorch-lighthing, which has a tqdm progress bar enabled by default. 
After a while, Dagit becomes very unresponsive.

### How to reproduce?

Run a long job with a tqdm bar

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by danielgafni** [comment]
Still happening on 1.2.7

![image](https://user-images.githubusercontent.com/49863538/232197639-6881494c-220f-4dd2-b9c4-5afb79041bae.png)

There should be a tqdm bar in the logs. It was working fine when I just started the training. But after 12 hours of training Dagit is freezing.

**Comment by danielgafni** [comment]
@hellendag just fyi in case you guys missed this issue

**Comment by hellendag** [comment]
Do you have a debug file for this run that we can take a look at?

**Comment by danielgafni** [comment]
I think this should work: 

```python
from tqdm import tqdm
from time import sleep
from dagster import asset


@asset
def long_tqdm():
    for i in tqmd(range(24 * 60 * 60)):
        sleep(1)
```

**Comment by bengotow** [comment]
Hey @danielgafni! Sorry for the delay on this one -- I tested this out locally this evening. I think the behavior has improved since your original post, but things are still not ideal.

- It seems like we handle `tqdm` correctly now. Each log line replaces the previous one which keeps the volume of logs way down, both in the UI and also in the downloaded raw log file.

- If I "break" the continuity of the logs by inserting some additional log statements inside the for loop in your example, I can still simulate a log file growing to 100k+ lines of text. When the log file grows that big AND updates continuously, it still strains the UI. It's usable (at least at 100k lines), but there still appears to be a somewhat linear relationship between performance and the number of log lines. Ironically, in a trace it looks like we may be spending a sizable amount of time just computing the line numbers themselves!

![Image](https://github.com/dagster-io/dagster/assets/1037212/b01d3286-0e1c-4e32-8251-36016096821a)


![Image](https://github.com/dagster-io/dagster/assets/1037212/db68fda4-20e6-4ecf-a8c8-db2d5c0254b3)

I'll see if there are any quick wins here.  I'm hopeful that the improvements in the way we handle line control characters means that this is a bit less common!
