### ISSUE TITLE
 AttributeError: 'Output' object has no attribute 'metadata_entries'

### ISSUE THREAD

**Issue by spenczar** [dagster-io/dagster#13589]
### Dagster version

dagster, version 1.2.6

### What's the issue?

`dagster.Output.metadata_entries` is no longer defined since #12770. The `metadata_entries` field appears in docs as a deprecated attribute of Output, but that's not accurate - it's been deleted.

### What did you expect to happen?

I expected docs to accurately describe the legal set of attributes for the Output class. A deprecated attribute should warn, but should still exist.

### Deployment type

None

### Additional information

When I look carefully at the docs, I notice that they say they're documenting the "Parameters" of `dagster.Output`, which I think means the parameters for the default constructor. But there are no other docs for the class; I assume that they're intended to describe the attributes of the class. A class with no public attributes _or_ methods would be a bit odd.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@smackesey

**Comment by dpeng817** [comment]
Yea I think we just forgot to update the docs for this case - we were throwing warnings for long after the announced release that we would remove the field.

**Comment by smackesey** [comment]
Hi @spenczar, what happened here is that for a brief period between 1.2.6, we intentionally retained `metadata_entries` as an argument (parameter) to `Output` while removing the accessor. We did this because the argument was deprecated but the accessor was private, and we wanted to wait till 1.3.0 to remove deprecated functionality. As of 1.3.0, the argument has been removed as well as the documentation for it.

I recognize this is a bit confusing because the constructor args usually match accessors, but the issue is now resolved.
