### ISSUE TITLE
backfill error when hourly asset overhangs daily asset

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#13694]
The scenario:
- An hourly-partitioned asset is upstream of a daily-partitioned asset
- There are hour partitions that don't yet have downstream date partitions - e.g. it's 5 pm on Thursday, so the 4 pm Thursday partition exists in the hourly asset, but the Thursday partition doesn't yet exist in the daily asset
- You launch a backfill over both assets that includes the latest hourly partition

What happens:
- Dagster tries to launch a run for Thursday in the downstream asset, because it launched a run for Thursday / 4 pm in the upstream asset
- The fact that there's no Thursday partition causes an error when trying to actually execute the run.

**Comment by sryza** [comment]
I think one way to fix this would be to make `PartitionMapping`s aware of `current_time`, and then make it so that `TimeWindowPartitionMapping` never returns partitions that aren't part of the `PartitionsDefinition` being mapped to.

**Comment by clairelin135** [comment]
I agree we should make `TimeWindowPartitionMapping`s aware of the current time. This is probably something we should've been doing before this anyway.

One consequence is that if `get_upstream_partitions_for_partitions` also respects the current time, an hourly partition would successfully execute when it doesn't yet have an upstream daily partition, which might be surprising behavior. One way to deal with this is to not pass in current time during runs, so that within a run all dependency partitions will be returned, rather than just the ones that exist at that time.

**Comment by sryza** [comment]
> One consequence is that if get_upstream_partitions_for_partitions also respects the current time, an hourly partition would successfully execute when it doesn't yet have an upstream daily partition, which might be surprising behavior.

@clairelin135 are you able to explain this scenario in more detail?

**Comment by clairelin135** [comment]
So say we have:
- upstream daily partitions def `DailyPartitionsDefinition("2023-01-01")`
- downstream hourly partitions def `HourlyPartitionsDefinition("2023-01-01-00:00")`

Calling `get_upstream_partitions_for_partitions(hourly_subset("2023-05-01-00:00"), downstream_partitions_def, current_time="2023-05-01")` returns an empty subset since the 2023-05-01 partition of the upstream daily partitions def does not exist yet. Subsequently a run that materializes just the "2023-05-01-00:00" partition will succeed even though "2023-05-01" is not materialized, since dagster thinks there are no upstream partition dependencies.

One way to fix this would be to make `current_time` optional, so that when `current_time=None` the partition mapping methods return the full set of dependent partitions, regardless of whether they currently exist or not. Then:
- We can set `current_time` in reconciliation/backfill scenarios when we create runs, ensuring we don't create runs for partitions that are nonexistent
- Within a run, current time should be `None`, so dagster will know recognize partitions that are not yet existent and error when these upstream partitions have not been materialized

**Comment by sryza** [comment]
Ah, I see. This is a tough one, because it exposes a state that we haven't really thought about before - a partition exists, but it can't be materialized because it on an upstream partition that doesn't exist yet.

FWIW, I think this will be rare. It doesn't really make sense for an hourly-partitioned asset depend on a single daily-partitioned asset. Maybe you would have an hourly-partitioned asset depend on both a daily-partitioned asset and another hourly-partitioned asset. But even then - what's the point? You can't materialize the hourly-partitioned asset until the day is over, so why not just make it daily?

What would happen if we made `TimeWindowPartitionMapping.get_upstream_partitions_for_partitions` raise an error in these cases?

**Comment by clairelin135** [comment]
Yeah, that seems reasonable to make `get_upstream_partitions_for_partitions` error in those cases. That will populate an error when:
- you launch a run for an asset whose upstream partition does not exist yet
- you launch a backfill for partitions whose upstreams do not exist

I think this is the behavior we want, I'll go ahead and implement this
