### ISSUE TITLE
Pythonic Config not working with Graph Assets

### ISSUE THREAD

**Issue by PascalStehling** [dagster-io/dagster#13880]
### Dagster version

dagster, version 1.3.1

### What's the issue?

When supplying graph assets with an pythonic config, it allways throws the error: `TypeError: graph_asset() missing 1 required positional argument: 'config'` even when config is specified.

### What did you expect to happen?

The pythonic config is working the same way for assets and graph_assets, as the results of both decorators should be an asset.

### How to reproduce?

In the following code example the asset and graph asset are defining exactly the same function, but the graph asset cannot be loaded and the `TypeError: simple_graph_asset() missing 1 required positional argument: 'config'` exception is thrown.

```py
from dagster import op, graph_asset, Config, Definitions, asset


class NumConfig(Config):
    a: int


@op
def plus_one(config: NumConfig) -> int:
    return config.a + 1


@op
def add(a: int, b: int) -> int:
    return a + b


class MultiNumConfig(Config):
    x: int
    y: int


@graph_asset
def simple_graph_asset(config: MultiNumConfig) -> int:
    x = plus_one(config=NumConfig(a=config.x))
    y = plus_one(config=NumConfig(a=config.y))

    return add(x, y)


@asset
def same_as_asset(config: MultiNumConfig) -> int:
    return (config.x + 1) + (config.y + 1)


defs = Definitions(assets=[graph_asset, same_as_asset])
```

### Deployment type

Local

### Deployment details

just copy the code example in a file and use `dagster dev -f my_file.py` to run the code

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by dpeng817** [comment]
So I think there's a few things at play here:
1. graph-backed assets do not currently support config to be specified at the graph level - as you've correctly linked in [this issue](https://github.com/dagster-io/dagster/issues/12647). However, you can still provide config either to the job that uses the graph-backed asset, or in the launchpad itself.
2. Nested graphs (as is a graph-backed asset) aren't super well supported by pythonic config. If you have a nested graph, there's no way to use pythonic objects to provide configuration to the underlying ops in that nested graph.

The way config is defined here in your example:
```python
@graph_asset
def simple_graph_asset(config: MultiNumConfig) -> int:
       ...
```
Would be a large design challenge to implement, as it changes the DSL fundementally. I think it more likely we would add the ability to do provide config mapping on the graph-backed asset - as outlined in https://github.com/dagster-io/dagster/issues/12647. Gonna close this issue, since I think that https://github.com/dagster-io/dagster/pull/13900 serves the immediate need.

**Comment by PascalStehling** [comment]
I understand your reasoning and I think its a solution for the problem. But in general I think the problem I have is the term "graph_asset" itself. In my mental model an Asset should behave the the same and take the same inputs, regardless if its created with `@asset` or `@graph_asset`, as the end result is always and Asset and the decorator functions should take care of the internal differences. Im not sure if im the only one with this Problem or if its confusing to more people :D But thanks for your help 👍
