### ISSUE TITLE
UI to backfill all partitions of a set of assets with different root `PartitionsDefinition`s

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#14073]
The backfill UI allows launching backfills over assets with different `PartitionsDefinition`s, but all the root assets of the backfill must have the same `PartitionsDefinition`.

The GraphQL mutation for launching backfills is a little more flexible than the UI. If the `allPartitions` flag is set to true, then the backend can handle selections of assets that have different `PartitionsDefinition`s at the root.

We could update the UI to support this.

### What we've heard:
- Rui Zhang - https://dagster.slack.com/archives/C04KC6XRU8N/p1683070203032799?thread_ts=1683050533.679829&cid=C04KC6XRU8N
  -  It would be nice if a user can select a bunch of assets and toggle a "backfill all partition" option without needing to specify the partitions when launching a backfill.

**Comment by bengotow** [comment]
Hey @sryza! This seems pretty reasonable - I talked about it with @braunjj and I'm wondering if we should hold off on this until we have a preview endpoint that will let us show the number of runs that will be launched and/or a way to implement the "only missing" checkbox for partition mapped asset backfills? It seems like right now, this option would really only be useful once, and then it'd do a lot of extra work each time it was clicked after that.

**Comment by sryza** [comment]
> It seems like right now, this option would really only be useful once, and then it'd do a lot of extra work each time it was clicked after that.

Do you mind expanding on what you mean by this a little bit? Any time that people change the code that derives their assets, they might want to run a backfill over all the partitions.

**Comment by bengotow** [comment]
Ahh sorry, I should have clarified a bit. I was thinking of a graph with a set of mapped time partitions. If I put them all in a group and view it, the UI will let me materialize all for all partitions without making an asset selection. If I come back tomorrow and just need partitions for the new day, I'm sorta stuck - I have to individually select subsets of the graph or "materialize all" again and rebuild everything.

Maybe for users with a schedule or auto-materialize policy this would be ok, since they're rarely going to try to fill in missing materializations? It's just tricky to explain that if you just want the missing day, you need to select subsets with a common root.

**Comment by sryza** [comment]
I think it's fairly rare that users would want to manually materialize the latest partitions of all their assets every day. It's more likely that they'd have some sort of automated process, either via schedules or auto-materialize policies, for doing so. If there are failures in parts of the asset graph, they might select those subsets and manually materialize them.

That said, I definitely agree that there are users who would find it useful to be able launch a backfill that includes root assets with different PartitionsDefinitions and only targets a subset of partitions. I imagine we'll eventually end up adding this, it's just difficult to come up with a design that supports this and not a high priority right now. But seems like, in the mean time, we might be able to support the simpler allPartitions case without to much work?
