### ISSUE TITLE
Dagit loading an individual pipeline seems broken

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1439]
In a branch i just did:

```
dagit -m dagster_examples.airline_demo.solids -n define_handle_from_s3_pipeline
```

where that function is defined as 

```
def define_handle_from_s3_pipeline():
    from dagster import PipelineDefinition

    return PipelineDefinition(name='handle_from_s3_pipeline', solids=[handle_from_s3])

```
Got this error:

![Screenshot 2019-06-05 16 10 31](https://user-images.githubusercontent.com/28738937/58996311-747d3c80-87ac-11e9-8c3b-e3d2f423065b.png)

**Comment by natekupp** [comment]
yeah that's because of https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/cli/load_handle.py#L92-L97 - we assume you're pointing to a function that'll return a RepositoryDefinition by default.

I don't see a good way to anticipate the system getting back the wrong type of thing, but two mitigations we could consider:

* Support loading pipelines from define_pipeline functions in dagit, e.g. with another CLI flag. Currently you need a repository.
* Present an error to the user that's easier to understand what went wrong and what they should do about it

**Comment by schrockn** [comment]
It's sketchy but we could pretty easily coerce that into an ephemeral repo if that function returns a pipeline. Note that all the tutorials are pretty broken because of this.

**Comment by natekupp** [comment]
Fixed by https://dagster.phacility.com/D307
