### ISSUE TITLE
Partitioned assets cannot trigger materialization of downstream non-partitioned  materialization

### ISSUE THREAD

**Issue by elben10** [dagster-io/dagster#14422]
### Dagster version

dagster, version 1!0+dev

### What's the issue?

It seems like non-time partitioned assets can trigger materialization of time partitioned assets, but time partitioned assets cannot trigger materialization of non-time partitioned assets through the `AutoMaterializePolicy` 

### What did you expect to happen?

I expected that asset3 also would have been materialized after asset1 (which trigger the materialization of asset 2, that I thought would trigger the materialization of both asset3 and asset4) has been materialized. I expect that is bug, but please let me know if it is a deliberate design choice. 
![](https://i.ibb.co/DVWNgDq/Screenshot-2023-05-23-at-20-23-44.png)

### How to reproduce?
Run `dagster dev -f def.py` and the materialize asset1
```python
# Content of def.py
from dagster import AutoMaterializePolicy, Definitions, MonthlyPartitionsDefinition, asset


@asset
def asset1() -> None:
    pass


@asset(
    non_argument_deps={"asset1"},
    partitions_def=MonthlyPartitionsDefinition(start_date="2020-01-01"),
    auto_materialize_policy=AutoMaterializePolicy.eager(),
)
def asset2() -> None:
    pass


@asset(non_argument_deps={"asset2"}, auto_materialize_policy=AutoMaterializePolicy.eager(),)
def asset3() -> None:
    pass


@asset(
    non_argument_deps={"asset2"},
    partitions_def=MonthlyPartitionsDefinition(start_date="2020-01-01"),
    auto_materialize_policy=AutoMaterializePolicy.eager(),
)
def asset4() -> None:
    pass


defs = Definitions(assets=[asset1, asset2, asset3, asset4])
```

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by mkleinbort-ic** [comment]
P.S. I have the same issue with static partitions (Dagster 1.3.5) - it's a fairly major annoyance

I'm pretty sure it's being worked on:

https://github.com/dagster-io/dagster/issues/14385
https://github.com/dagster-io/dagster/issues/9374

**Comment by OwenKephart** [comment]
Hi! Sorry this fell through the cracks.

At a high level, there are two things going on here.

First, in cases where an unpartitioned asset (asset3) is downstream of a partitioned asset (asset2), there is an assumed AllPartitionMapping on that edge.

The core assumption is that the downstream asset depends on all partitions of the upstream asset. Therefore, it will not materialize asset3 until all partition of asset2 have been materialized, as this would (in theory) result in asset3 either erroring (because outputs/partitions it expected to exist do not yet) or being in an inconsistent state (as it's supposed to represent a union of all the upstream partitions, but it only contains one of them).

This assumption is partially incorrect in this case, as it seems like your desired behavior would be to have asset3 incorporate whatever data it has available when an upstream partition is materialized, rather than waiting for it all to be ready. This implies that it is possible to execute asset3 without all of the partitions being available.

Second, a similar thing happens at the edge between asset1 and asset2, where it's assumed that all partitions of asset2 depend on the state of asset 1. This would mean that, if asset1 were to be updated, then all partitions of asset2 would be in a state of not having the most up to date data available, and therefore would be expected to be updated (rematerialized) before downstream assets were processed.

This is an "even more" incorrect assumption, and will generally not be the case when mapping between unpartitioned and time-partitioned assets.

Both of these issues are top of mind, and we're actively investigating how to make these behaviors more configurable / intuitive.

@elben10 As an extra data point, how do you view the relationship between asset1 and asset2? As in, is each partition of asset2 some sort of snapshot of the current state of asset1 at a given point in time, or is something else going on there?

**Comment by elben10** [comment]
No worries. I did not know of the assumption `The core assumption is that the downstream asset depends on all partitions of the upstream asset.`. It solves the issue.

**Comment by sryza** [comment]
> No worries. I did not know the assumption The core assumption is that the downstream asset depends on all partitions of the upstream asset.. It solves the issue.


@elben10 out of curiosity, does this assumption match your situation? If not, would you be able to describe the difference? What relationship would you want Dagster to understand between the downstream asset and the partitions of the upstream asset?

**Comment by Haunfelder** [comment]
@sryza, I have a similar pipeline setup where the assumptions makes things tricky. Specifically, I have a date partitioned upstream asset covering a long window of dates. In a testing environment, I would like to make changes to the upstream asset, materialize a view of the dates as a test, and then materialize the downstream asset on any available partitions from the upstream asset. Materializing every date is slow and I would only like to execute them all once when I get to production. Is this possible?
