### ISSUE TITLE
Adding a dynamic partition resets config in launchpad

### ISSUE THREAD

**Issue by slopp** [dagster-io/dagster#14580]
### Dagster version

1.3.7

### What's the issue?

I love the new "scaffold all default config" values in the launchpad. I did notice one weird thing, which is visible around timestamp 7:47 in this video. If you are using dynamic partitions you can add a partition from the launchpad (:heart_eyes: ), but note that if you do that, it resets any other config you might have scaffolded
https://www.loom.com/share/ad38c77796a24e439f33361849c512e9

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by ztessler** [comment]
I'm still experiencing this issue on 1.4.16. PR #15198 changed a file that's since been moved, but looking at what I think is the current location: 

https://github.com/dagster-io/dagster/blob/095f95982a1dcbbea28385ddee18da6de954e71f/js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadSession.tsx#L490

the change in #15198 is not reflected there. Is this a regression?

**Comment by ztessler** [comment]
Ah, I see that commit was reverted. Is there any workaround in the meantime for setting config on a partitioned asset? Any edits in the launchpad config removes the selected partition, and selecting a partition clears the config. Thanks!

**Comment by slopp** [comment]
@ztessler  we'll look at re-opening this

in the meantime, I've found the following sequence works:

- open the launchpad
- change any config settings
- manually select the partition by adding the tag: dagster/partition: <your partition key> (use the edit/add tags button)

sorry for the trouble here, we'll get this resolved

**Comment by ztessler** [comment]
Thanks @slopp! That workaround works
