### ISSUE TITLE
auto-materialize downstream unpartitioned asset even if some upstream partitions are missing

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#14628]
### What we've heard
- https://elementl-workspace.slack.com/archives/C03C3E81TNE/p1685998905529559?thread_ts=1685973263.844479&cid=C03C3E81TNE
  -  yeah, there are often cases where say an asset is partitioned by account or website or something like that and one of the accounts might have no new data for a few days. because our ingestion stores state it won't load any data to (redacted) and we don't yield an asset materialization event. in this case, it's (redacted) data we get from (redacted) and because of issues on their end we aren't getting data for some sites (partitions). we still want to run downstream transformations because there isn't really anything to backfill.

**Comment by sryza** [comment]
Two of the options for where we could handle this are:
- At the auto-materialize policy layer. Somehow indicate that you _should_ auto-materialize an asset even if some upstream data is missing.
- At the partition-mapping layer. Somehow indicate that you _can_ materialize an asset even if some upstream data is missing. Then the auto-materialize layer can just say "I can materialize this, so I will".

**Comment by OwenKephart** [comment]
Of the two options partition-mapping layer feels like a more useful place for this information, as IOManagers would also want to take this into account (so a solution purely in the AMP layer feels too narrow). For example, currently, the UPathIOManager uses a custom (optional) [bit of metadata](https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/python_modules/dagster/dagster/_core/storage/upath_io_manager.py?L24) to determine if it's ok for a partition to be missing or not when we attempt to load it.

Perhaps this was already your intention, but just to formalize: thinking in terms of practical implementation concerns, I think defining a partition mapping that takes into account the current materialization state of the upstream assets is quite dicey, as we'd then need to query the instance whenever we wanted to call `resolve_upstream_partitions_for_partitions` and friends. There's also the time-based weirdness, where the set of partitions that an asset/partition depends on is constantly in flux, which might cause strange things to happen if we want to look at a historical materialization.

So if we were to put this information on the partition mapping, I'd advocate for that to not impact the return value of any of those sorts of partition mapping functions. It'd simply be a property of the PartitionMapping class which could be read in by IOManagers and AutoMaterializeLogic alike

A third option would be to just formalize the "requires_all_upstream_partitions" property of an asset, but that has the disadvantage of not allowing this to be set per-input.

Following from that conclusion, a fourth option would be to have this be a property of the AssetIn. This is nice because:
a) it's input specific
b) in cases where you were happy with the default partition mapping, you don't have to type out that default PartitionMapping manually just to set one property on it (you might not even know the name of the class for your default partition mapping if you've never cared to set it explicitly)

Disadvantages:
a) this property is not currently represented in our serialized AssetGraph, so we'd need to make space for it

**Comment by sryza** [comment]
@OwenKephart that thinking all makes sense to me.  Curious if @clairelin135 has thoughts on including this on the `PartitionMapping` vs. the `AssetIn`.

**Comment by clairelin135** [comment]
I think we should make this property available on the AssetIn
- for unpartitioned assets, this would allow you to materialize a downstream unpartitioned asset if desired when one upstream does not yet exist
- for partitioned assets, the property set on the AssetIn can be passed to the partition mapping, so the partition mapping is still responsible for determining if a partition can be materialized

**Comment by sryza** [comment]
I thought about this a little more, and I'm also leaning more towards the `AssetIn` as a better place for this than `PartitionMapping`, because I think this functionality might end up being useful even in situations where there are no partitions.  E.g. a non-partitioned asset might depend on another non-partitioned asset, but the upstream asset might not need to be present for the downstream asset to be materialized.

We've discussed this a bit elsewhere, but I can't help but wonder if we should be somehow combining this with `allow_nonexistent_upstream_partitions`. "do upstream existent partitions need to be present to materialize this asset?" seems very related to "do upstream nonexistent partitions need to be present to materialize this asset. Thoughts on that?

**Comment by OwenKephart** [comment]
Following up on this conversation, I agree that there's something to combining these two concepts. There are two sorts of non-existent partitions in the time-window partition world:

1. Partition does not exist because the downstream start date is older than the upstream start date (i.e. A -> B, A starts in 2022, B starts in 2020)
2. Partition does not exist because the downstream maps to a range that includes currently non-existent partitions of the upstream (i.e. A -> B, B depends on partitions from the future)

In both cases, setting `allow_nonexistent_upstream_partitions` indicates to our system "you're allowed to execute with whatever data you have available". This seems nearly identical to the user intent when specifying the proposed property on this issue.

Concrete proposal: AssetIn gets a new optional `requires_all_partitions` (name TBD) property, which defaults to True. This property will be used in the following places:

1. AutoMaterialize land, to determine if we can execute an asset even when some dependencies are missing
2. PartitionMapping land, to determine if we should raise an error or not (if a partition does not exist)
3. IOManager land, to determine if we should raise an error or not (if a partition is found to be missing)

**Comment by sryza** [comment]
@prratek can I ask you a couple followup questions about this issue:
- If one of the upstream partitions failed to materialize, would you still want to auto-materialize the downstream asset?
- If you kicked off a backfill that included both the upstream asset and the downstream asset, would you still want to materialize the downstream asset if one of the upstream partitions failed?

**Comment by danielgafni** [comment]
Hey guys!

As I understand, `allow_nonexistent_upstream_partitions` is only present in `TimeWindowPartitionMapping`. I would really like to have it in `AllPartitionMapping` (and the others?).

Also, I would like to have `allow_failed` or similar in `AutoMaterializePolicy`. This would make possible to auto materialize an asset even if some of the upstream assets are in failed state (but others have been updated).

**Comment by sryza** [comment]
> Also, I would like to have allow_failed or similar in AutoMaterializePolicy. This would make possible to auto materialize an asset even if some of the upstream assets are in failed state (but others have been updated).

@danielgafni in this case, what behavior would you want if you manually materialized these assets? Would you want the downstream asset to be materialized if some of the upstreams failed, as long as others materialized successfully?

**Comment by danielgafni** [comment]
Yeah, I would like it to load the latest successful materializations of the upstream assets. This is the current behavior right? 

Another scenario I can think of is loading `None` instead (the argument would have to be `Optional` for it to work)

**Comment by sryza** [comment]
>  This is the current behavior right?

@danielgafni consider this situation:
* Asset C depends on both A and B
* You select A, B, and C and click **Materialize**
* A succeeds and B fails

Currently, Dagster won't execute C, because B failed. Would you want it to?

**Comment by danielgafni** [comment]
oh, I see. Perhaps there should be an additional checkbox for that. By default it should not materialize **C** if **A** or **B** fail.

**Comment by sryza** [comment]
> By default it should not materialize C if A or B fail.

I agree that this should be the default behavior

> Also, I would like to have allow_failed or similar in AutoMaterializePolicy. This would make possible to auto materialize an asset even if some of the upstream assets are in failed state (but others have been updated).

In the case that someone has `allow_failed`, would that be the same as the "additional checkbox" you mentioned? Or is it important to distinguish between the following?
- How failures are handled within auto-materialize
- How failures are handled when you manually launch a set of materializations

**Comment by prratek** [comment]
> @prratek can I ask you a couple followup questions about this issue:
> 
> * If one of the upstream partitions failed to materialize, would you still want to auto-materialize the downstream asset?
> * If you kicked off a backfill that included both the upstream asset and the downstream asset, would you still want to materialize the downstream asset if one of the upstream partitions failed?

* Likely depends from case to case, but often yes
* No

Here's the thought process I'm typically going through - If one or more upstream partitions fail but materializing the downstream asset wouldn't result in "incorrect data" then I want to materialize it. A common example of this is if the upstream asset has one partition per account/user/page and the downstream asset is just doing a union all and maybe some light cleanup, I'm okay with the downstream one having fresh data for some accounts but slightly stale data for others. However, if the downstream logic was say calculating a count of accounts/users/pages then it would be flat out wrong and I wouldn't want to materialize it. So I imagine we'd have to decide on a case-by-base basis but having the flexibility would be great.

With backfills it has no impact on the freshness of the downstream asset since we're likely operating on some slice of historical data. In that scenario, I don't see a benefit to materializing if some partitions are missing or failed to materialize. That just sounds messy

**Comment by sryza** [comment]
@prratek got it - thanks.

**Comment by OwenKephart** [comment]
Hi all, closing this issue, as this should be solved as of a recent release. Two changes in particular are useful here:

1. By default, the "skip_on_parent_missing" AutoMaterializeRule does not factor in missing ancestors (just its immediate parents). This means that if you have `A(partitioned) -> B(unpartitioned) -> C(unpartitioned)`, then `C` will be materialized whenever `B` updates, even if `A` is still missing partitions (however, `B` would not be auto-materialized by default).
2. It is now possible to disable all checks for the presence of parent partitions, using the following:
```python
from dagster import AutoMaterializePolicy, AutoMaterializeRule

my_new_policy = AutoMaterializePolicy.eager().without_rules(
    AutoMaterializeRule.skip_on_parent_missing(),
)
```

This will create a policy that would allow (for example) B to be materialize whenever a partition of A was updated, even if other partitions were missing.
