### ISSUE TITLE
`graph_asset` is missing a `config_mapping` argument

### ISSUE THREAD

**Issue by danielgafni** [dagster-io/dagster#14944]
### Dagster version

1.3.11

### What's the issue?

The title. 

While a workaround with using `AssetsDefinition.from_graph` exists, it adds some unnecessary boilerplate. 

[Slack thread](https://dagster.slack.com/archives/C01U954MEER/p1686765536456289) 

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment]
Thanks for the report, I'll add this.

**Comment by sbquinlan** [comment]
@smackesey can you add support for the rest of the @asset stuff that makes sense? Notably io_manager_key?

Take a look at #15352 if you want a starting point here. I think there's a much bigger opportunity to simply asset_decorator completely so that the graph flavors aren't completely separate implementations considering how much functionality they share.

**Comment by danielgafni** [comment]
Would it be possible to add `config_mapping` to `@asset` too? 
I'm thinking about using `dynamic_partitioned_config` with a dynamically partitioned asset.
I would lake to have a unique config per partition.
