### ISSUE TITLE
`load_assets_from_dbt_project` should allow to bypass IO managers

### ISSUE THREAD

**Issue by aaaaahaaaaa** [dagster-io/dagster#15129]
### What's the use case?

Currently, `load_assets_from_dbt_project` uses the default `io_manager`, unless specified otherwise. However, it makes sense for DBT assets to not relying on any IO Manager since the "materialization" is handled by DBT against the configured data warehouse (e.g. BigQuery). In many cases (most?), it seems to me that there would be no value in having DBT asset materialized by an IO manager.

Not allowing to disable the usage of the IO Manager brings other issues. For example, using the `BigqueryPandasIOManager` as the default `io_manager`, requires the metadata `partition_expr` to be set, otherwise the execution fails. Adding the metadata is useless since the DBT asset doesn't return any object.

### Additional informations

Side question: what is the value in supporting IO managers altogether for DBT assets? I don't see any use case where that makes sense. Upstream assets are based on DBT sources, and there's no object to materialize for downstream assets.

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment]
hey @aaaaahaaaaa the IO managers can be provided so that downstream assets can load the tables that were materialized by dbt. So if you specified the BigQuery IO manager on your dbt assets, it's not being used to store the assets (dbt takes care of that) but it would be used if you were to load one of those tables downstream to do additional work on it. 

So unless you plan on loading the dbt assets in downstream assets, you don't need to specify an io manager. You are correct that the default io manager gets set by default. And that IO manager is technically called after the dbt assets are materialized, but if you're using a dagster provided IO manager, it doesn't do any work (it returns immediately). This is a side effect of the broader dagster architecture, but is something we are looking at changing in the somewhat near future

**Comment by aaaaahaaaaa** [comment]
> if you're using a dagster provided IO manager, it doesn't do any work (it returns immediately)

Right, I understand that the `obj` is null and therefore returns immediately. But "fake" metadata still has to be specified for the execution not to fail:
```
node_info_to_definition_metadata_fn=lambda node_info: {"partition_expr": ""}
```

It's very subjective, but it would make more sense to me if the IO manager could be bypassed entirely for DBT and the Bigquery IO Manager would have to be specified manually for the inputs of the downstream asset.

Anyway, I do understand the constraints of the overall asset architecture.

**Comment by aaaaahaaaaa** [comment]
@jamiedemaria I just realised `Asset` has an `output_required` parameter. Maybe it would make sense to add that parameter to `load_assets_from_dbt_project`?
