### ISSUE TITLE
Show Auto-materialized tag on runs page; and link to the evaluation result

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#15225]
We want to add a tag at the top of the runs page if the run was launched by the auto-materialize policy. 
Hovering over the tag show show a pop-over that exposes a link to the evaluation result for each asset targeted (see mockup below)

@johannkm is working on the backend for this.

![image](https://github.com/dagster-io/dagster/assets/2798333/be21b502-040e-46fc-a6f3-d103fd318a33)

**Comment by hellendag** [comment]
@johannkm Once you've got the backend in place for this, feel free to reassign to me and I'll work on the frontend.

**Comment by johannkm** [comment]
Just landed https://github.com/dagster-io/dagster/pull/15199. You can fetch the `dagster/asset_evaluation_id` tag and use that id in url param for the evaluations ui.

Nit: I'd be in favor of hiding this tag in the UI since it doesn't have any helpful info once we have a built in link. Do we have something built to filter out unnecessary tags? (other than the hidden tags enum, which hides them over the gql layer)

**Comment by hellendag** [comment]
@braunjj Can we avoid showing the names of the assets in the header if we're also going to show this? It's getting pretty crowded up there.

@johannkm will all of the assets for this run be equivalent to the list in `run.assetSelection`, or could there be a discrepancy?

**Comment by braunjj** [comment]
@hellendag do we always show all asset names or do we ever collapse those tags down to a "N assets materialized" tag?

I agree that it's getting crowded but I think it's important to still show the asset tags when the run was not kicked of by auto-materialization.

**Comment by johannkm** [comment]
> @johannkm will all of the assets for this run be equivalent to the list in run.assetSelection, or could there be a discrepancy?

That's the list of assets to use, then the new tag gives the evaluation id to link to for each of them
