### ISSUE TITLE
get_asset_backfill_iteration_materialized_partitions stalls backfill daemon

### ISSUE THREAD

**Issue by paulius-hydrosat** [dagster-io/dagster#15241]
### Dagster version

1.3.13

### What's the issue?

It seems that the backfill daemon is unable to cope with a large canceled backfill. It get's bogged down and fails to send a hearbeat. Debugging lead to `get_asset_backfill_iteration_materialized_partitions` function, that has the following lines:

```
records_in_backfill = [
    record
    for record in records
    if instance_queryer.run_has_tag(
        run_id=record.run_id, tag_key=BACKFILL_ID_TAG, tag_value=backfill_id
    )
]
```

It seems that `run_has_tag` method hits a DB, and hence this loop is very slow. On my end it spins at 30 it/s, which means that in 5 minutes it can go through 9K partitions. My canceled backfill has ~50K.

If I read the code correctly, this could be replaced by a single query `SELECT run_id FROM run_tags WHERE tag_key='dagster/backfill' AND tag_value=backfill_id` followed by an in memory filtering. This should deal with 100Ks of partitions in a matter of seconds.

### How to reproduce?

Unfortunately I do not have a repro at hand. But if you need one to proceed, let me know, I'll try to produce one.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@clairelin135 - mind taking a look at this one?

**Comment by clairelin135** [comment]
@paulius-hydrosat thanks for reporting. I agree that fetching only the runs with the backfill tag should speed this up. I'll take this on in the coming weeks when I get the chance.

**Comment by clairelin135** [comment]
@paulius-hydrosat any chance you still have some sort of profile for this?

This particular query 
```python
records_in_backfill = [
    record
    for record in records
    if instance_queryer.run_has_tag(
        run_id=record.run_id, tag_key=BACKFILL_ID_TAG, tag_value=backfill_id
    )
]
```
runs incrementally--so every 30s, the daemon uses a cursor from its previous evaluation to get materializations since its past iteration. Then, it runs this query on those new materializations. So unless if a very large number of materializations occurred in between iterations, this query shouldn't be deserializing a large number of runs.

I do agree with you that it would likely be more performant to run a single query to fetch run IDs, but I'm surprised this operation in particular would cause the daemon to stop heartbeating.

**Comment by paulius-hydrosat** [comment]
Sorry, I'm not able to reproduce it anymore :(

I'll close this issue and will reopen when (if ever) I have a repro.

**Comment by clairelin135** [comment]
Thanks @paulius-hydrosat! In this week's release (1.4.8) there are additional perf improvements for asset backfill cancellations. They don't include the query that you mentioned, but they should fix the daemon "not running" issue.
