### ISSUE TITLE
`define_asset_job` is missing the `op_retry_policy` parameter

### ISSUE THREAD

**Issue by aaaaahaaaaa** [dagster-io/dagster#15313]
### What's the use case?

`define_asset_job` should be consistent with the `job` annotation and expose the `op_retry_policy` parameter.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by clairelin135** [comment]
@aaaaahaaaaa I agree this would be good to add. If you are open to contributing this fix, I'm happy to answer questions and review the PR. Otherwise, we'll add this to our backlog and get around to this issue when we can. In the meantime, you can define a specific retry policy on a per-asset basis.

Side note: we should probably rename the argument to `asset_retry_policy` instead of `op_retry_policy`.

**Comment by IsaacChanXi** [comment]
This is my first time making a contribution to Dagster but would like to give this issue a shot!

**Comment by Rohxn16** [comment]
This has been quiet for a while, so I guess I will try this

**Comment by Rohxn16** [comment]
Any ideas on which file the change is to be made?
Im new to Open Source and I'm sorry if this is a stupid qs.

**Comment by kennycontreras** [comment]
@Rohxn16 are you still working on this? otherwise, I'd like to take it. Thanks.

**Comment by Rohxn16** [comment]
you can take this up @kennycontreras

**Comment by kennycontreras** [comment]
I guess we can close this one now @sryza @clairelin135 🙇🏻‍♂️
