### ISSUE TITLE
Investigate dagster-pandas performance issues

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1553]
Jack has reported some performance issues.

![Screenshot 2019-07-12 10 45 57](https://user-images.githubusercontent.com/28738937/61147839-41585800-a492-11e9-9d14-21d4edb11558.png)

**Comment by jack-pace** [comment]
Sorry - I did meant to get around to posting an mwe for this! Thanks for creating the issue!!

## The problem
#### MWE using `execute_pipeline` and through `dagit`
```python
import pandas as pd
from dagster import execute_pipeline, lambda_solid, pipeline


@lambda_solid
def pandas_solid():
    return pd.DataFrame(
        columns=[str(i) for i in range(1000)],  # 1000 columns
        index=range(90),  # 90 rows
    )


@pipeline
def pandas_pipeline():
    return pandas_solid()


if __name__ == '__main__':
    result = execute_pipeline(pandas_pipeline)
    print(result.event_list[3].step_success_data)
```

Running the above gives:
> StepSuccessData(duration_ms=286.16667500000403)

Running it in dagit, I get >700ms:
![image](https://user-images.githubusercontent.com/34025206/61283883-bb9c1b80-a7b5-11e9-9ae8-f8d9f4292a14.png)

#### IPython comparison
Comparatively, running it as a normal python function it takes 65ms:
```python
In [1]: import pandas as pd
In [2]: def pandas_solid():
   ...:     return pd.DataFrame(
   ...:         columns=[str(i) for i in range(1000)],  # 1000 columns
   ...:         index=range(90),  # 90 rows
   ...:     )
In [3]: %timeit df = pandas_solid()
65.1 ms ± 142 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

## Possible cause
One observation which might be to blame is that the pandas `__str__` implementation is quite slow:
```python
In [4]: df = pandas_solid()
In [5]: %timeit str(df)
262 ms ± 5.54 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Since it looks like the a truncated version of the string representation is printed in the results in the dagster logs, this explains the whole time difference when running with `execute_pipeline`.

I am not sure however, why it is two to three times slower again using dagit.

**Comment by schrockn** [comment]
https://dagster.phacility.com/D625
