### ISSUE TITLE
Add a button "Materialize with upstream"

### ISSUE THREAD

**Issue by eromoe** [dagster-io/dagster#15714]
### What's the use case?

Manual refresh data/ run jobs . 
Now I have to multiselect many asset by `shift + click` . 

And I tried to create a job
```
stock_feature_job = define_asset_job(name="stock_feature_job", selection="stock_feature")
```
Only show one node `stock_feature` , didn't rerun the upstream node.

I am using dagster as a datapipeline, and becasue usually change the code, and need rerun manually, this feature is needed.
 

### Ideas of implementation

Add a button "Materialize with upstream" would be ideal . 
User no need coding to add a job.
However, add an option `materialize_upstreams=True` is also good.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
@eromoe one option here is to go to the lineage tab on the details page for the asset, use the buttons to select upstream assets, and then hit the materialize button. Would that work for you?

@braunjj @bengotow - maybe there's a way to make this more discoverable.

**Comment by eromoe** [comment]
@sryza Yes it hide too deep. 
click asset -> click `[View in Asset Catalog]`  -> `lineage` -> choose Upsteam tab -> materialize .


Split this button into two button or change to dropdown would be much more convenient.
![image](https://github.com/dagster-io/dagster/assets/3938751/e9365c93-2343-4cd4-8383-393a31462772)

**Comment by bengotow** [comment]
We talked about this in the Core / UI meeting today. 

- I think we want to go ahead and attach the contextual menu to asset nodes so that you can easily access the "View upstream graph" and "View downstream graph" options there.

- We like the idea of having users filter the graph and THEN click Materialize in a separate / second action, because it ensures you always know what you're materializing. Depending on your view (job / group / global), it varies how far upstream "View upstream graph" will go, and having a two step flow makes that explicit.

@salazarm  I think you were working on that context menu already? Going to assign this to you for now!
