### ISSUE TITLE
Show partition mappings in the UI

### ISSUE THREAD

**Issue by tha23rd** [dagster-io/dagster#15720]
### What's the use case?

After defining a partition mapping like is shown here: https://github.com/dagster-io/dagster/discussions/14636

It would be nice to see this mapping somehow in the UI, likely in the Asset Definition page. This not only gives confidence that this mapping has been defined clearly, but also helps users understand how various assets are dependent on one another.

**Comment by bengotow** [comment]
We discussed this on the call today, our plan is to describe partition mapping on the asset details > definition tab. @clairelin135 could you help create a GraphQL resolver for retrieving the partition mapping? It seems like it might actually belong on the dependsOn / dependedBy edge, rather than on the node.

**Comment by clairelin135** [comment]
@bengotow certainly -- I think I can add this sometime this week
