### ISSUE TITLE
Raise exception when multi assets contain asset inputs that are not specified in internal asset dependencies

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#15800]
### Dagster version

1.4.4

### What's the issue?

If a `@multi_asset` has an `AssetIn`, but that `AssetIn`'s `AssetKey` is not captured as a dependency in `internal_asset_deps`, the execution of the `@multi_asset` will fail.

The `@multi_asset` will attempt to execute before it's `AssetIn` has materialized.

### What did you expect to happen?

This behavior should be forbidden.

### How to reproduce?

To minimally reproduce this, consider the following example:

```python
from dagster import AssetOut, Definitions, asset, multi_asset


@asset
def my_upstream_asset() -> int:
    return 1


@multi_asset(outs={"asset_one": AssetOut()}, internal_asset_deps={"asset_one": set()})
def my_multi_asset(context, my_upstream_asset) -> int:
    return my_upstream_asset + 1


defs = Definitions(assets=[my_upstream_asset, my_multi_asset])
```

In the `@dbt_assets` case:

```python
@dbt_assets(manifest=dbt_manifest_path)
def jaffle_shop_dbt_assets(
    context: OpExecutionContext, dbt: DbtCliResource, upstream_asset: dict
):
    yield from dbt.cli(
        ["build", "--vars", json.dumps(upstream_asset)], context=context
    ).stream()
```

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jasonamyers** [comment]
So in our case, we have to determine what kind of data we received and how it affects the current data from a timeframe perspective. So we have a graph that handles the initial loading of the data in a data frame and then determines the overlapping periods using some logic we have defined. Those overlapping periods are a dictionary containing keys like append and replace, which are lists with quarters.  We feed our DBT models the replacement quarters to our DBT model's pre_hook via a variable to handle any quarterly clean-up. Then we directly pass the append quarters to our DBT models so they know what quarters to operate on. Ideally, we can feed the output of our graph/asset graph to our DBT assets so that when they materialize, it has the information it needs to properly clean up before appending the data. We don't have dependable keys, so we can't use a merge operation. We have to delete and insert the data by quarter.
