### ISSUE TITLE
Add docs discussing differences between Dagster and other systems

### ISSUE THREAD

**Issue by pikhovkin** [dagster-io/dagster#1593]
Add an example with the [prefect](https://github.com/PrefectHQ/prefect) DAG

**Comment by schrockn** [comment]
Can you give some more context here? What type of example and what do you want to see compared/contrasted exactly?

**Comment by pikhovkin** [comment]
For example
```
from prefect import task, Task, Flow
import random

@task
def random_number():
    return random.randint(0, 100)

@task
def plus_one(x):
    return x + 1

with Flow('My Functional Flow') as flow:
    r = random_number()
    y = plus_one(x=r)
```
from [here](https://docs.prefect.io/guide/core_concepts/flows.html#overview)

**Comment by natekupp** [comment]
Hi @pikhovkin can you explain more about what you’re looking for? Dagster and Prefect are similar but are different systems, and we don’t currently support running Prefect workflows or vice versa.

**Comment by namdnguyen** [comment]
Not exactly what @pikhovkin is asking, but something that I'm curious about that's not yet answered for me is whether the shortcomings of Airflow mentioned in this article: https://medium.com/the-prefect-blog/why-not-airflow-4cfa423299c4 are also handled by Dagster. Here's some of the use cases mentioned in the article:

- DAGs which need to be run off-schedule or with no schedule at all
- DAGs that run concurrently with the same start time
- DAGs with complicated branching logic
- DAGs with many fast tasks
- DAGs which rely on the exchange of data
- Parametrized DAGs
- Dynamic DAGs

Many of these deal with handling state within the pipeline. I've read the Introducing Dagster article (https://medium.com/@schrockn/introducing-dagster-dbd28442b2b7), but it doesn't touch on these points. 

It becomes difficult to compare workflow orchestrators because Airflow can use Dask for execution, but the scheduling of jobs is handled by a central scheduler in Airflow. Prefect outsources scheduling to Dask, which also uses Dask for execution. 

Dagster supports both Airflow and Dask, but I'm not sure how it differs from the Airflow and Prefect implementations. If I had to guess, it would be using Airflow for scheduling and Dask for job execution. If so, the Airflow shortcomings mentioned by Prefect still apply. Is Airflow the only workflow scheduler for Dagster? Can Dask be used for scheduling or only for execution via Airflow? Should I see Dagster as an abstraction layer above Airflow and others, such that any underlying strengths and weaknesses of each integrations come along with the Dagster packaging or are there other parts of Dagster that mitigates the weaknesses of a component?

One other comment on the README with the list of integrations and cloud providers: it might be helpful to see in a diagram how the pieces could fit together, with integrations separated by class and where they fall within the architecture of a data product. Spark and Dask are close to each other. Pagerduty and Datadog are close to each other. Jupyter would be farther to the right for analysis and presentation. I do see the difficulty with diagramming this though, given how many integrations you have. AWS is under cloud provider, but you could break out EMR to put next to Spark and Dask.

**Comment by natekupp** [comment]
@namdnguyen Apologies for the delayed response, and thanks for the thoughts! Definitely agree that we could use a similar post to articulate some of the ways that we differ from Airflow and other workflow systems like Prefect.

In the interim, I wanted to address some of your questions here—and we'll follow up with that more in-depth post soon.

- **Scheduling:** With Dagster, we've intentionally kept scheduling separate from the core programming model, for similar reasons as raised in the Prefect post. Airflow's tight coupling of DAGs and scheduling is tough for beginners and not a good fit for many use cases that don't require a regular schedule interval.
- **Execution Targets:** The high-level Dagster programming model is intended to be decoupled from physical execution. This enables us to support a variety of execution substrates; we compile pipelines of solids into an internal representation that we call an _execution plan_, comprised of _execution steps_. To date, we've implemented Airflow and Dask as execution targets, but supporting other targets is straightforward and something we plan in the future. However, I'll note that our relationship with Dask and Airflow are quite different; for the former, we simply delegate physical execution of execution steps to Dask workers. For the latter, Airflow expects to control scheduling and execution of the full pipeline. So, in our Airflow integration there is an isomorphism between the full Dagster execution plan and the Airflow DAG we synthesize; each Airflow task execution will invoke a bundle of Dagster execution steps on Airflow's executors.
- **Strengths/Weaknesses**: I think the answer here really depends on the use case; if you're already a company that's heavily invested in Airflow, we see our integration as a way to gain access to the strengths of Dagster—a sane local development story, great tools (Dagit), testability, our GraphQL API, etc.—while continuing to use all of your existing infrastructure for existing DAGs and for ops. For teams that haven't yet adopted a workflow system, Dagster + Dask (or even just execution with vanilla Dagster) can likely work well without the heavyweight introduction of Airflow.
- **Integrations**: This is good feedback; we can definitely improve how we position Dagster w.r.t. third-party integrations in the README and documentation. It seems to me that the most important point to clarify is where Dagster sits in this ecosystem: a layer of abstraction above existing systems.

Hope that helps, and feel free to reach out here or [in our Slack](https://tinyurl.com/dagsterslack) with any follow-up questions!

**Comment by namdnguyen** [comment]
No worries, @natekupp! Thank you for the great reply. It clarifies things for me. I'm even more excited to try out Dagster!

**Comment by talebzeghmi** [comment]
Could the differences between Dagster, Dask ML Pipelines and Kubeflow also be elaborated upon?

thank you!

**Comment by mgasner** [comment]
#1931

**Comment by mgasner** [comment]
One comparison project is https://github.com/bmedx/analytics-pipeline-rubric

**Comment by mgasner** [comment]
You might also be interested in this comparison that @flowersw did: https://medium.com/@will_flwrs/python-data-engineering-tools-the-next-generation-354e00f2f060

**Comment by schrockn** [comment]
Dagster Airflow comparison: https://dagster.io/blog/dagster-airflow

**Comment by sryza** [comment]
Closing this on the basis of the above comparison
