### ISSUE TITLE
[Errno 28] inotify watch limit reached

### ISSUE THREAD

**Issue by Interesting6** [dagster-io/dagster#15953]
### Dagster version

dagster, version 1.4.5

### What's the issue?

Operation name: PipelineRunLogsSubscription

Message: [Errno 28] inotify watch limit reached

Path: 

Locations: 

<img width="1430" alt="image" src="https://github.com/dagster-io/dagster/assets/22903497/4421c4a3-7666-4d60-8bde-5277cbe18b3f">

### What did you expect to happen?

normal run.

### How to reproduce?

a practice copy from 'https://www.youtube.com/watch?v=UrjHVJ2GZN0'

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
Have not been able to reproduce or root cause this, but it seems localized to the particular deployment. In another case, toggling on the `Disable WebSockets` option in `User settings` fixed it:

![Screenshot 2024-04-01 at 11 50 48](https://github.com/dagster-io/dagster/assets/50636644/01eb0fa9-8fcd-489b-8dec-91e8271b6c68)

![Screenshot 2024-04-01 at 11 51 01](https://github.com/dagster-io/dagster/assets/50636644/cb60c8a9-903f-4a0d-b79c-28be805f64a4)
