### ISSUE TITLE
Audit fix for column resizing issue

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1615]
[Dagit Column Resizing.zip](https://github.com/dagster-io/dagster/files/3438737/Dagit.Column.Resizing.zip)

**Comment by schrockn** [comment]
Download and see the attached movie. When you resize the columns the UI can become borderline unusable.

**Comment by mgasner** [comment]
https://dagster.phacility.com/D719

**Comment by mgasner** [comment]
@bengotow would love your eyes on this fix; I am uneasy about the `(evt as unknown) as React.MouseEvent<HTMLDivElement>` cast to resolve these incompatible types. alternatives that come to mind include extending the WindowEventMap, which feels a little dangerous/weird. i couldn't figure out a way to use instanceof checks, etc., to accomplish this.

i'm also wondering whether at ll. 83-84 it might make more sense to set a global state variable (perhaps on `window`, or on a context provider) instead of using document.addEventListener / document.removeEventListener to manage state -- my intuition for the costs here is bad, but it feels like manually attaching and detaching event listeners is probably higher overhead than switching on a bool in a listener which is always attached.
