### ISSUE TITLE
dagster workflow to CWL export

### ISSUE THREAD

**Issue by shivamsaxena17493** [dagster-io/dagster#1640]
Export mechanism of file which holds the Dagster dag workflow (tasks to be executed ) and gets visualization in Dagit UI. 

Can it be exported as Common Workflow Language or any other Workflow standard language specification.

Ref:
https://www.commonwl.org/index.html

**Comment by mgasner** [comment]
@shivamsaxena17493 can you provide some color on the use case you have in mind here?

**Comment by catherinewu** [comment]
stale issue, closing

**Comment by ricardo-re-azevedo** [comment]
Hi All, 

I would like to reopen this. CWL is a common language for designing workflows using yaml that is growing in popularity as people move to DAG based execution schemas. The idea is to have a workflow-engine neutral method of defining workflows so that people using different execution systems can still understand what is going on.

It would be great to have support for this format as it does appear to be a growing standard and is being used by various workflow execution systems.

**Comment by davidelbert** [comment]
@ricardo-re-azevedo are you still interested in this?  My group uses dagster but we are finding more traction for CWL and I am wondering about making CWL workflows workable in Dagster.  I was considering suggesting wrapping CWL workflows in a Dagster op (or asset) and then letting Dagster handle orchestration, scheduling, retries, lineage, and data asset cataloging while CWL is just a way that people can define and execute the compute parts. I think it would mostly be just putting a CWL runner (probably cwltool?)  inside a Dagster op, capture outputs, and materialize them as Dagster assets.  Wondering what others think.
