### ISSUE TITLE
Issues I faced with pytest and building docs while setting up the dev environment.

### ISSUE THREAD

**Issue by SRITANU** [dagster-io/dagster#1641]
Two things I faced while setting up the dev environment: (edited) 

1. `pytest python_modules/dagster/dagster_tests` was giving a lot of import module errors. Using `python -m pytest python_modules/dagster/dagster_tests` made it run successfully. 
![image](https://user-images.githubusercontent.com/5100536/62419045-36f63c00-b695-11e9-82ab-fd8903f31363.png)

2. I had to separately install `sphinx-autobuild` to run `make livehtml` successfully.

Did I do something wrong or the docs should be updated?

**Comment by alangenfeld** [comment]
> pytest python_modules/dagster/dagster_tests was giving a lot of import module errors. Using python -m pytest python_modules/dagster/dagster_tests made it run successfully.

This can be a problem depending on which `pytest` binary your shell ends up resolving to. Looking at your screenshot pytest is running 3.7 but it looks like you set things up for a 3.6 venv. We could update the docs to say `python -m pytest` since that should consistently do the right thing.

> I had to separately install sphinx-autobuild to run make livehtml successfully.

good catch -  https://dagster.phacility.com/D763

**Comment by SRITANU** [comment]
Shall I take this issue up?

**Comment by alangenfeld** [comment]
if you want to update the docs that would be greatly appreciated :D

**Comment by SRITANU** [comment]
Sure, I'd do that.

**Comment by alangenfeld** [comment]
thanks for the help!
