### ISSUE TITLE
[dagster] validate args in @input_hydration_config decorated fn

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#1690]
probably other decorators too, but we should do the same validation that we do for `solid` such as ensuring the first arg is context

**Comment by themissinghlink** [comment]
QQ to understand the context and scope for this issue. 

So my mental model is that a solid's decorated function must pass the following checks:

1. Solid keyword arguments need to have input definitions.
2. missing name validation
3. missing context positional argument

My mental model for a input hydration config is that the decorated function must pass the following checks:

1. The first arg must be context
2. .....that's it? I mean let's say that the decorated function has 0 extra arguments outside of context, do we want to error out? It would be kinda silly because why have a input config schema when you don't have inputs to configure? Do we want to call this out?

If we don't want to do the later, the former is not super hard to implement: 

```
def input_hydration_config(config_cls):
    '''
    A decorator for annotating a function that can turn a ``config_value`` in to
    an instance of a custom type.

    Args:
        config_cls (Any):
    '''
    # validate_decorated_fn
    config_type = resolve_config_cls_arg(config_cls)

    def wrapper(func):
        try:
            validate_decorated_fn(func, {}, [('context',)])
            return _create_input_schema(config_type, func)
        except FunctionValidationError:
            # Error Stuff which should mirror applicable parts of validate_solid_fn
    return wrapper
```

I took `resolve_config_cls_arg` from `dagster.core.definitions.decorators`, it was originally a "private function" which I am proposing we expose. However, I am noticing that a lot of the Error stuff starts to get replicated. Should we clean that up so that these validations and exceptions are scoped at the granularity of a decorator than the granularity of a solid? Should we do this refactor in a different issue?

**Comment by alangenfeld** [comment]
> The first arg must be context .....that's it?

For `@input_hydration_config(T)` decorated functions the first argument is `context` and the second argument is where the value (of type T) will be passed in from the config. Don't think we need to enforce a name for the value arg but it should be present.

> Should we clean that up so that these validations and exceptions are scoped at the granularity of a decorator than the granularity of a solid? Should we do this refactor in a different issue?

Yep the meat of this task is refactoring out the useful to share validation code.

**Comment by themissinghlink** [comment]
Cool! I am first gonna refactor out the validation code from the solid code and get a MVP proposal out. If it looks good, I will throw the applicable validation code into the @input_hydration_config and other applicable decorators! Thanks Alex!
