### ISSUE TITLE
Annotation checking for context doesn't work with future annotations in python 3.11

### ISSUE THREAD

**Issue by Tanguy-LeFloch** [dagster-io/dagster#16972]
### Dagster version

dagster, version 1.5.0

### What's the issue?

The issue appeared after updating to `1.5.0`.

We are currently using python3.11 and `from __future__ import annotations` in a file defining several dagster ops.

It seems that without the future, the annotations stay python objects and Dagster checks them against its own classes in `dagster/_core/definitions/op_definition.py` line 525->527.
However, when using the future behavior (which may be the case in python3.12), those annotations (in `fct.__annotations__`) end up as strings, thus checks like `params[0].annotation is not OpExecutionContext` fail.

### What did you expect to happen?

No error to be raised, the type annotation is correct.

### How to reproduce?

In python3.11:

```python
from __future__ import annotations

from dagster import OpExecutionContext, op


@op
def my_op(context: OpExecutionContext) -> None:
    ...

```

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by yuhan** [comment]
@smackesey mind taking a look?

**Comment by smackesey** [comment]
>However, when using the future behavior (which may be the case in python3.12), those annotations (in fct.__annotations__) end up as strings, thus checks like params[0].annotation is not OpExecutionContext fail.

Hi @Tanguy-LeFloch, it is known to us that `from __future__ import annotations` does not play nice with Dagster. It's unfortunate and I'm sorry you ran into this difficulty. We should probably enhance our docs around this issue. If you want the dirty details on the situation, you can read here: https://github.com/dagster-io/dagster/pull/14675

I am not sure why this appeared when you upgraded to 1.5.0, but in general, Dagster definitions like `@op` will not _reliably_ work with string annotation values (and `from __future__ import annotations` sets _all_ annotations in the module to strings), so you should avoid using `from __future__ import annotations` in files where there are Dagster definitions.

Note that Dagster is not alone as a framework in having issues with string annotations-- Pydantic and others do too. For that reason I believe `from __future__ import annotations` is being deprecated and the future behavior in 3.12 will likely be to have annotations as lambda values rather than strings. There are more details in the PR I linked.

**Comment by Tanguy-LeFloch** [comment]
Hello @smackesey ,

Okay, thanks for the explanation.
I guess we have been lucky not run into issues so far as we are using `pydantic` extensively and future annotations often.
