### ISSUE TITLE
After reloading definitions, checks don't show up on asset graph nodes until refreshing page

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#17015]
To reproduce:
- Load an asset graph with a single asset
- Add a check to it in Python
- Click the button to Reload definitions
- Notice the the check doesn't show up
- Refresh the page
- Notice the check shows up

**Comment by bengotow** [comment]
Hmm I think the issue here is that the checks (and their statuses) are part of the "live data" on the asset graph so the checks don't appear until that data is ready. I've also noticed this is annoying because the checks section of the sidebar can be missing for a while. Maybe we fetch just the check names alongside the definitions as well.
