### ISSUE TITLE
RunsRoot should subscribe in addition to running a query so that the runs view can update live

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1753]

**Comment by prha** [comment]
I think the runs view is already live in the sense that we poll every 15 seconds (so that we can pick up any run state changes).

@mgasner, unless you mean switching it up so that we use a push-based subscriptions, along with some sort of cursor that keeps track of any run state changes for in-flight runs?

**Comment by prha** [comment]
Also, duplicate #1675

**Comment by natekupp** [comment]
Polling is fine for now (cc @mgasner )
