### ISSUE TITLE
CI for py38

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1758]

**Comment by mgasner** [comment]
https://github.com/dagster-io/dagster/tree/ci-38

**Comment by mgasner** [comment]
likely that airflow will not work for now. we will probably also need to fork the integration image dockerfile, since the docker image for py38 is on buster, there is no supported jdk8 for buster, spark 2.4 won't work on jdk11 (but 3.0 beta should)

**Comment by mgasner** [comment]
cc @natekupp

**Comment by natekupp** [comment]
Summary after poking at Python 3.8 for a few minutes: `scipy` is now built for 3.8 (progress!) but following upstream dependencies don’t yet work:

- `airflow` (due to `psutil` wheels missing)
- `scikit-learn` (See [this issue](https://github.com/scikit-learn/scikit-learn/issues/15328))
- `dask` 
- `snowflake` (`pyarrow` doesn’t build wheels anymore)
- `dagster-examples` (`pyproj` wheel missing, but [coming soon](https://github.com/pyproj4/pyproj-wheels/pull/20))

**Comment by schrockn** [comment]
we could at least do it for core libraries

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by mgasner** [comment]
yes i believe it is important to know what does and doesn't work on 3.8

**Comment by natekupp** [comment]
Quick status update: `scikit-learn` wheels are published and `snowflake-connector-python` installs successfully. Only remaining issues are `airflow` / `dask` due to `psutil` wheels missing.

Biggest issue w/ turning on CI is going to be @mgasner's comment above re: getting jdk8 on buster for the CI images.

**Comment by mgasner** [comment]
closing in favor of #1960
