### ISSUE TITLE
Model the additional dependencies of dbt relationship tests in asset checks

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#17628]
Requires checks that depend on multiple assets

**Comment by aksestok** [comment]
I see the body here is lacking a bit of detail, but I'm running into this issue when I have a fact table that I want to make sure has a referential integrity towards a dimension table.

Just to throw it out there, I would also be satisfied (in the shorter term) with skipped tests when the dependent models haven't been materialized yet.

**Comment by rexledesma** [comment]
This was implemented in https://github.com/dagster-io/dagster/pull/19319 and was released starting `dagster-dbt==0.22.3` (February 1, 2024).

**Comment by toddy86** [comment]
Note, the relational integrity tests aren't guaranteed to work if you have a mixture of partitioned and non-partitioned dbt assets in a job. In short, because there is a mixture of partitioned and non-partitioned assets, the dbt assets will be materialized in separate steps in the job. Which under certain conditions can mean that the test between e.g. Asset A which has a relationship to Asset B can fail, as Asset A is materialized and tested in a separate step. 

Linked discussion [here](https://github.com/dagster-io/dagster/discussions/19218#discussioncomment-8652248)
