### ISSUE TITLE
SqlTypeHandler

### ISSUE THREAD

**Issue by jrstats** [dagster-io/dagster#17804]
> Or should I just be writing a new type handler for my IO manager where the `obj` is the query?

As all of the required context/metadata/etc. exists within the IO managers, it makes sense to me to create a `SqlTypeHandler` to add to the IO manager.

I have worked on this today and it solves our needs without any changes to the APIs, but I think it is also a really cool bit of functionality. Would you be interested in a PR for it? Or is there a reason you haven't added one before?

_Originally posted by @jrstats in https://github.com/dagster-io/dagster/discussions/17595#discussioncomment-7490452_

**Comment by jamiedemaria** [comment]
One of the main reasons we haven't added something like this is the maintenance burden. Basically any time we need to change anything with the database I/O managers, we often need to make some changes to the type handlers. This results in a lot of cascading work (num db io managers x num type handlers). Another reason is that it still hides some logic from the user (what SQL commands are run before/after the user's command? Do we pass any args to the client?). And finally, we felt that it was significantly different from the other paths that use I/O managers (returning a query vs returning data) that we weren't confident adding it as a fully supported feature (especially since we wanted to improve the ergonomics around not using I/O managers)

However, I do think some users would be interested in this feature. It might be a good candidate to write a "Show and tell" discussion and share the code for the type handler. If there's lots of interest and usage, then we can reconsider adding it as a fully supported feature https://github.com/dagster-io/dagster/discussions/new?category=show-and-tell

**Comment by jrstats** [comment]
Thanks for the feedback @jamiedemaria . I agree that it is different to the other IO managers - it is kind of half way between the resource and the IO manager. But it mimics the behaviour of the other IO managers (deleting then inserting, selecting only the appropriate partitions and columns for upstream dependencies) so hit should feel familiar to dagster users.

I will definitely write up a show and tell, as I would expect other users to be interested in it, especially non-dbt users like ourselves and I think it's a really powerful piece of functionality, especially in conjunction with the other type handlers.

**Comment by sryza** [comment]
Closing this based on @jamiedemaria 's comment - I agree that this makes more sense as a show-and-tell than as something that gets maintained as as part of DBIOManagers, at least at this time.
