### ISSUE TITLE
Dagster generated static site 

### ISSUE THREAD

**Issue by davidgasquez** [dagster-io/dagster#17807]
### What's the use case?

Hey there! Would be awesome if Dagster could generate a simple static site surfacing the DAG, assets descriptions and perhaps even [linking to dbt docs](https://github.com/dagster-io/dagster/issues/15913).

This would be helpful as a way to surface relationships and the catalog when working with stakeholders. 

Right now, I'm relying on dbt Docs as a workaround but having docs at the Dagster level would be much better.

### Ideas of implementation

Perhaps something like `dagster docs generate`?

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by davidgasquez** [comment]
Yes! I've been using that as a workaround but I was thinking about being able to provide the Dagster UI experience to end users via, say, GitHub Pages.

**Comment by davidgasquez** [comment]
Hey there! Curious if there are any updates on this one. 

Totally uderstand if is not a priority, just wanted to make sure I'm not missing anything!

**Comment by butterlyn** [comment]
Hello, here to say I'm interested in this as a feature as well! There are similar features for other orchestrators, like Kedro [`kedro viz build`](https://docs.kedro.org/projects/kedro-viz/en/stable/share_kedro_viz.html) and dbt [`dbt docs generate`](https://docs.getdbt.com/docs/collaborate/documentation).

**Comment by rexledesma** [comment]
See https://github.com/dagster-io/dagster/issues/15913#issuecomment-1998728605: we now surface a ton of this information in our new Dagster Catalog. The an asset in the catalog displays metadata like asset descriptions, latest materializations, owners, tags, etc. This is available in open source.

In Dagster+, you can also optionally enable Catalog mode for your viewers so that they have a more condensed view of the Dagster Catalog. See our [video recap](https://www.youtube.com/watch?v=ef65uXzZwHM) for more information.
