### ISSUE TITLE
Ability to export the table of assets at http://{url}/assets to csv or similar.

### ISSUE THREAD

**Issue by mkleinbort-ic** [dagster-io/dagster#17894]
### What's the use case?

The assets shown in http://localhost:3000/assets are a very useful "data catalogue", but it's hard to share it / analyze it with other tools.

It'd be great to add an "export" button - either to csv, excel, or at least pdf/html/png.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by hellendag** [comment]
cc @sryza in case you have thoughts here.

**Comment by bengotow** [comment]
Hey @mkleinbort-ic! This is a good question -- It'd be fairly low level, but you could potentially export fields you're interested in directly from Dagster's GraphQL layer (using an app like GraphiQL and giving it the URL http://localhost:3000/graphql). Something like that might be helpful, but the output is fairly unpleasant JSON rather than a CSV.

I think if there's enough interest we could build a CSV exporter, but several of the columns (like status, etc) would need new plain text rendering. Are there specific things you'd be interested in seeing in an export?

**Comment by mkleinbort** [comment]
I'm pretty happy with working with the JSON output, I'll share the code afterwards should anyone be interested. 

Do you have a code snippet for hitting the graphql API for the asset data?
