### ISSUE TITLE
Dagster fails upon adding new model to dbt cloud

### ISSUE THREAD

**Issue by bramrodenburg** [dagster-io/dagster#17989]
### Dagster version

1.5.4

### What's the issue?

Jobs in Dagster start to fail when a dbt model is added or removed to a dbt cloud job that Dagster orchestrates.

Error message:
```
dagster._core.errors.DagsterInvariantViolationError: Core compute for op "dbt_cloud_job_<xxxxx>" returned an output "<dbt model name>" that does not exist. The available outputs are: [... <list of dbt models> ]
```

### What did you expect to happen?

That it works just fine. Ideally it should just add/remove the corresponding asset.

### How to reproduce?

- Setup dagster with dbt cloud
- Configure a dbt cloud job
- Run it in Dagster
- Update the dbt cloud job to build another model
- Run it again in Dagster

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gnilrets** [comment]
I started getting this issue yesterday when I upgraded from `dagster-cloud==1.4.17` to `dagster-cloud[serverless]==1.4.17`

cc @prha

**Comment by prha** [comment]
@gnilrets that's strange... the only difference between `dagster-cloud` and `dagster-cloud[serverless]` is an unpinned `boto3` dependency

**Comment by gnilrets** [comment]
I'm wondering if it could have something to do with saving the materializations?

**Comment by Minderwinter** [comment]
Did this ever get resolved? I'm also having this issue.

**Comment by gnilrets** [comment]
The following workflow seems to have solved it once for me, but I haven't encountered this issue enough to be certain.   The error is happening because the dbt job has new dbt models.  Dagster cloud didn’t know about these models.  In order to fix it, I had to:

1. Run the dbt job with the new dbt models so a new manifest file was generated
2. Update the [dagster cache](https://docs.dagster.io/integrations/dbt-cloud#step-43-test-the-cache-locally) 
3. Re-deploy the Dagster code location

Not sure if step 2 is really necessary.

**Comment by Minderwinter** [comment]
Ah, yeah seems like generating the new manifest is what I was missing. Thanks!
