### ISSUE TITLE
Create solid with a dynamic set of arguments

### ISSUE THREAD

**Issue by pikhovkin** [dagster-io/dagster#1817]
How to create "solid" with a dynamic set of arguments?

I want to convert Dask's DAG (it is dict struct) to Dagster's DAG for Dagit, but I get error `Solid functions should only have keyword arguments that match input names and a first positional parameter named 'context'.` i.e. I cannot create solid func like `def func(_, *args):...`
How can I get around this restriction?

**Comment by alangenfeld** [comment]
> How can I get around this restriction?

If you manually construct a `SolidDefinition` I don't believe we do any additional validation on the `compute_fn` arg passed there, so that could unblock you.

That said, the only way to get data passed in to the solid (ie `*args`) is for Dagster to be aware of it so I worry you may run in to further issues depending on what exactly you are trying to do.

**Comment by mgasner** [comment]
@pikhovkin Can you elaborate at all on what you'd like the solid to do? Is this to handle an input that could be expressed as a list?

**Comment by pikhovkin** [comment]
Yes, input could be expressed as a list.
It seems to me that there should be an alternative way to describe dependencies for DAGs that is not as strict as it is now.

**Comment by mgasner** [comment]
#462

**Comment by catherinewu** [comment]
Going to close; dagster tries to model and type the data produced and consumed by each step and this would go against that design objective
