### ISSUE TITLE
Support undo in the config editor

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1821]

**Comment by bengotow** [comment]
Hmm so this one is interesting—the config editor does support undo/redo as long as the config editor has focus (eg: insertion point is flashing and it's receiving the events).

It looks like it /doesn't/ support undo when you drop in a preset though because we destroy and re-create the entire CodeMirror context. Will see if I can fix that.

**Comment by bengotow** [comment]
Ahh, it also looks like if you switch tabs in the top navigation, you lose your undo/redo stack in the other tab.

**Comment by bengotow** [comment]
Well... CodeMirror exposes a getHistory / setHistory API, but the history objects seem to be coupled to it's "document" model which is not deterministic. A simple test of the following does not work:

```
v = cm.getValue()
h = cm.getHistory()
// move to another tab
cm.setValue(v)
cm.setHistory(h)
// undo does nothing
```

Their official stance on this (at least as of... 2012) was "Is there a reason you're not just keeping your editor instance around, hiding it and creating a new one for the other document?" This is actually not a terrible suggestion, given that we only have a handful of tabs, but may take a bit of hackery given how React sees the world.

https://github.com/codemirror/CodeMirror/pull/247

**Comment by hellendag** [comment]
I don't think we're going to fix this specific issue, at least not while we're using CodeMirror. Undo/redo should be working fine within the editor as described above.
