### ISSUE TITLE
Dagster run fail on openshift, access denied to /opt/dagster

### ISSUE THREAD

**Issue by andrescolodrero** [dagster-io/dagster#18919]
### Dagster version

1.5.13

### What's the issue?

After deploy Dagster Helm on OPenshift, i try to execute a run:
PermissionError: [Errno 13] Permission denied: '/opt/dagster'

### What did you expect to happen?

Job should run.

### How to reproduce?

Deploy Dagster Helm into openshift.
I didnt specify any sort of securityContext

Dagster-daemon is running with user 100099000
dagster-run is running with same user.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by dpeng817** [comment]
As I understand it, openshift doesn't default you to the root user, which is why you're likely running into this issue. This is something that probably needs to be handled at the cluster level, and is probably not therefore not a dagster bug.

**Comment by andrescolodrero** [comment]
Hi,
But this is an issue that could we handle in the settings/parameters of Helm Chart?

**Comment by dpeng817** [comment]
Since it's an issue specific to one deployment environment - I think we probably want to avoid exposing it at the top level. From a stackoverflow search it seems like using a [custom image](https://stackoverflow.com/questions/42363105/permission-denied-mkdir-in-container-on-openshift) for your deployment that explicitly adds permissions for certain directories could help.

**Comment by andrescolodrero** [comment]
I tested several approaches with SecuryContext, but i just ended mounting another volume and setting dagster_home in this new volume
