### ISSUE TITLE
Update Dagster Airbyte to use the new Airbyte API

### ISSUE THREAD

**Issue by spazylbekova** [dagster-io/dagster#19096]
### What's the use case?

Airbyte transitions from [the configuration API](https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html) to [the new API](https://reference.airbyte.com/reference/start). Airbyte does not have active commitments to support configuration API long-term. I was wondering if there are any plans to support the new Airbyte API. We are struggling to make configuration API work for us since we use Okta for webapp. 

API documentation 
https://docs.airbyte.com/api-documentation

### Ideas of implementation

Update [dagster-airbyte](https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-airbyte/dagster_airbyte) library to support [the new Airbyte API](https://reference.airbyte.com/reference/start)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tangos974** [comment]
Hi, I'd like to follow up on this issue, as per the [airbyte docs](https://reference.airbyte.com/reference/portalairbytecom-deprecation):

"To increase security, Airbyte is migrating to use in-app Applications to secure access to the Airbyte API. As a result, we're removing the portal.airbyte.com site, which has previously been used for API key management.

API keys generated from the previous Portal will stop working on August 15, 2024."


So that means two things:
- People (like me) who haven't generated an airbyte api key the old way (before portal.airbyte.com was removed) cannot use the dagster_airbyte library to create an airbyte asset in dagster - i.e. we can't pilot airbyte from dagster at all without sacrificing a lot of the functionalities that made us choose dagster in the first place.

- In 2 weeks from now, all keys generated that way will stop working. That means that the amount of people in my case will grow substantially overnight.

Is there an ETA for updating the `dagster_airbyte` library to support the new Airbyte API? Should my team and I begin working on a workaround, or is there an update planned for the next release?

Thanks in advance.

**Comment by garethbrickman** [comment]
@tangos974 https://github.com/dagster-io/dagster/pull/23451
