### ISSUE TITLE
Dagster Helm Chart: Configure SideCar container in user-code deployment

### ISSUE THREAD

**Issue by andrescolodrero** [dagster-io/dagster#19189]
### What's the use case?

Be able to setup sidecar containers running aside each code-location server.

### Ideas of implementation
add the key "containers" and attach a sidecar to the code-location-server

`dagster-user-deployments:
  deployments:
      containers:
    - name: "k8s-example-user-code-1"
        image: # User code Location Server
            repository: "docker.io/dagster/user-code-example"
            tag: ~
            pullPolicy: Always
         .....
     - name: mysidecar
       image:
         repository: mysidecar
`

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by craustin** [comment]
These changes are working for me:
https://github.com/dagster-io/dagster/pull/19192/files

**Comment by andrescolodrero** [comment]
Excellent @craustin I was searching for "sidecar", but didnt see this feature about init containers and extra containers.

**Comment by craustin** [comment]
I added those two keys (`extraInitContainers ` and `extraContainers`) to the `dagster-user-deployments` chart, so you'll have to fork or otherwise copy the Helm chart in order to add those two - but the changes aren't huge. It could be worth keeping this issue open until Dagster accepts the PR or makes similar changes themselves.
