### ISSUE TITLE
[Documentation Feedback] Problem on /integrations/dbt/using-dbt-with-dagster/load-dbt-models page

### ISSUE THREAD

**Issue by danrapp-ipg** [dagster-io/dagster#19325]
following the tutorial to the point of running this command in shell caused a problem. 

DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=1 dagster dev

for reference i am building in VS Code in a virtual environment running in an integrated PS terminal

**Comment by danrapp-ipg** [comment]
error to include...

DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=1 : The term 'DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and  
try again.
At line:1 char:1
+ DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=1 dagster dev
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by garethbrickman** [comment]
I think the issue is that Microsoft PowerShell (PS) handles the setting of environment variables differently to a Unix shell. Can you try setting the env var first as below and then running `dagster dev` after that:

1.
```
$env:DAGSTER_DBT_PARSE_PROJECT_ON_LOAD = "1"
```
2.
```
dagster dev
```

Let me know if successful and I'll make a PR to note this difference in the docs👍

**Comment by danrapp-ipg** [comment]
Yes, that did the trick!
