### ISSUE TITLE
Periodic failures in examples py35

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1941]
see https://buildkite.com/dagster/dagster/builds/7383#baea290b-c674-40a8-9e3a-9ea65a79b063

```

def validate_columns_in_dataframe(self, dataframe):
--
  | for mandatory_column_name, mandatory_column_config in self.invariant_config.items():
  | if mandatory_column_name not in dataframe.columns:
  | return TypeCheck(
  | success=False,
  | description='Dataframe should have {} columns. Currently missing {}'.format(
  | self.invariant_config.keys(), mandatory_column_name
  | ),
  | )
  | if ValidationTypes.CATEGORIES in mandatory_column_config:
  | valid_column_mask = dataframe[mandatory_column_name].isin(
  | >                   mandatory_column_config['catagories']
  | )
  | E               KeyError: 'catagories'



```

Quite mystifying

**Comment by schrockn** [comment]
Confirmed this is periodic. Retry on master fail worked.

**Comment by asingh16** [comment]
Oh no. I fucked this up. So this is def a regression, but what I don't understand is how the retry worked, or more precisely how this errored out in the first place because my tests work locally. Regaurdless, let me push up a fix

**Comment by asingh16** [comment]
Oooooooh I know what happened. So the config has indeterminate ordering because it's a dictionary. It turns out that my example is failing validation for a different reason but because I am just checking to see if the type checking fails, the test "succeeds" before we can actually validate the bucket. It just so happened that the test validated the columns in a different order which surfaced the bug!
