### ISSUE TITLE
Auto-materialize in inconsistent state after discarding partitions

### ISSUE THREAD

**Issue by maxfirman** [dagster-io/dagster#19527]
### Dagster version

1.6.0

### What's the issue?

Any asset partitions that get discarded in an auto materialisation tick end up in an inconsistent state and require manual intervention to materialise. For example, if an unmaterialized partition is discarded it will no longer appear in the "Materialization is missing" rule in subsequent auto-materialize ticks. This is counter intuitive. 

According to the [documentation](https://docs.dagster.io/concepts/assets/asset-auto-execution#auto-materialization-and-partitions) this is the expected behaviour, and a suggested workaround is to bump up the `max_materializations_per_minute`. 

### What did you expect to happen?

The `max_materializations_per_minute` should be respected on a per tick basis, however discarded partitions should not end up being ignored in subsequent automaterialize ticks.

### How to reproduce?

Simultaneously materialise multiple upstream partitions to a partitioned asset such that the number of partitions to be materialised in an auto-materialize tick exceeds the `max_materializations_per_minute`. Observe that any discarded partitions no longer get considered in subsequent ticks.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
Hi @maxfirman - definitely understand that it might not be ideal for your use case, but this is the expected behavior for how "discard" works, so I'm going to close this issue. We're currently planning a set of changes that, among other things, will eliminate discard rules and provide more out of the box rules for controlling this behavior: https://www.notion.so/dagster/Public-RFC-auto-materialize-changes-6f8b7ffdd92847cfa96f2ed171293cb4?pvs=4#a57bbae508684a56aa468a58957e314e.
