### ISSUE TITLE
Partitioned observable source assets always show 0 materialized partitions in the Asset table

### ISSUE THREAD

**Issue by smackesey** [dagster-io/dagster#19614]
Define an observable source asset:

```
from dagster import (
    AssetExecutionContext,
    DataVersionsByPartition,
    Definitions,
    StaticPartitionsDefinition,
    observable_source_asset
)

parts = StaticPartitionsDefinition(["a", "b", "c"])

@observable_source_asset(partitions_def=parts)
def foo_obs(context: AssetExecutionContext):
    return DataVersionsByPartition(
        {
            "a": "1",
            "b": "2",
            "c": "3",
        }
    )



defs = Definitions(
    assets=[foo_obs],
)
```

Observe it once and then look at the Assets table:

<img width="1349" alt="image" src="https://github.com/dagster-io/dagster/assets/1531373/b65a9a5b-943f-4b4d-a6fe-f2425574bd73">

It says 0 materialized partitions-- this should just be blank for observable source assets, since there is no concept of "materialization status" for any source asset.

cc @bengotow

**Comment by stigmarl** [comment]
I've noticed something similar for a partitioned observable source asset, as I'm able to navigate into the partitions overview from the "Events" tab of the asset. Even though the asset have been observed for these dates, the "materialization status" will never update: 

![image](https://github.com/dagster-io/dagster/assets/1974988/cfc16c19-b495-4230-bc69-6c6e0c9e944a)

Note that there's no "Partitions" tab, as would be the case for regular assets. 

I think we're looking at different symptoms in the UI arising from the same root cause.

**Comment by bengotow** [comment]
Hey folks, I'm able to reproduce both these issues, will get it fixed!
