### ISSUE TITLE
Revisit use of read_namespaced_pod_log

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1968]
Right now we use the k8s `read_namespaced_pod_log` to extract the GraphQL response printed by `dagster-graphql` to stdout—see [here](https://github.com/dagster-io/dagster/blob/120269fb3b29b8c5e8943624df4b971e04f59b92/python_modules/dagster-graphql/dagster_graphql/cli.py#L105)

We should probably find a less fragile way to accomplish this; it's not clear to me that this API is designed for durability / reliable reads of pod outputs

**Comment by mgasner** [comment]
https://dagster.phacility.com/D1856

https://github.com/kubernetes-client/python/issues/811#issuecomment-535588805

**Comment by natekupp** [comment]
@catherinewu FYI this may end up being important for Airflow users on K8s

**Comment by natekupp** [comment]
See `parse_raw_log_lines()` in in `dagster_graphql.client.util`

**Comment by mgasner** [comment]
this will presumably still be a thing if we move to grpc or the api cli

**Comment by mgasner** [comment]
consider tailing the event log storage or using a shared volume

**Comment by natekupp** [comment]
per conversation this morning with @catherinewu, we could instead just have the containers write directly to the instance database and remove this `parse_raw_log_lines` entirely. If the containers had access to the instance, we could also remove passing tags over the graphql interface; see https://dagster.phacility.com/D4017

**Comment by johannkm** [comment]
Current status: we still use `retrieve_pod_logs`, though now it's parsed directly to dagster events (`filter_dagster_events_from_pod_logs`) since the logs are from a dagster cli invocation rather than graphql.

I think that using the event store should become the default, since we now assume that step executions will have db access. Reading events over logs could still be supported especially for multi-process executor, as it should be more performant. In any case we should refactor the logic around it. Currently each executor has a fair bit of redundant messy code.

**Comment by johannkm** [comment]
We've solved this with the `k8s_job_executor`, it persists with the `celery_k8s_job_executor`
