### ISSUE TITLE
DbtCliEventMessage Unable to Handle Sources

### ISSUE THREAD

**Issue by cwe5590** [dagster-io/dagster#20262]
### Dagster version

1.6.7

### What's the issue?

When running freshness checks using the DbtCliResource (dbt source freshness), the events can no longer be processed. This is because we are only looking at nodes when processing DbtCliEventMessage not other types of objects (see below).

https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py#L152 

This fixes it, but I'm sure there is a more elegant way to fix it:

`dbt_resource_props = manifest["nodes"][unique_id] -> dbt_resource_props = (manifest["nodes"] | manifest["sources"])[unique_id]`

### What did you expect to happen?

Events created from source freshness checks should be able to be processed. This worked correctly in 1.6.1.

### How to reproduce?

Run DbtCliResource with the following command and freshness checks setup: `source freshness`

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment]
You're probably doing something like:

```python
@dbt_assets(manifest=...)
def my_dbt_assets(context: AssetExecutionContext, dbt: DbtCliResource):
    ...
    yield from dbt.cli(["source", "freshness"], raise_on_error=False).stream()
```

But we're not supposed to yield any events from `dbt source freshness` anyways since those are related to dbt sources. We only want to yield events on dbt model materializations and dbt tests.

As a workaround, you could just call `.wait()` instead. This way, your dbt command is still invoked, but no events are yielded.

```python
@dbt_assets(manifest=...)
def my_dbt_assets(context: AssetExecutionContext, dbt: DbtCliResource):
    ...
    dbt.cli(["source", "freshness"], raise_on_error=False).wait()
```

In the future, we still want the `.stream()` to work with `dbt source freshness`, even though it will do nothing. https://github.com/dagster-io/dagster/pull/20315 will resolve that.

**Comment by cwe5590** [comment]
Thanks Rex. I missed that and glad that was merged!
