### ISSUE TITLE
Add Polars Pandera support

### ISSUE THREAD

**Issue by pbower** [dagster-io/dagster#20584]
### What's the use case?

As per **Dagster**'s _Pandera_ documentation [here](https://docs.dagster.io/_apidocs/libraries/dagster-pandera) that it only supports _Pandas_ at this time, requesting _Polars_ support as supported here [Pandera](https://github.com/unionai-oss/pandera).

### Ideas of implementation

Seamless integration.

### Additional information

Hoping it's not too difficult. Thanks!

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by keithkam-yk** [comment]
Hi folks, we want to do something along these lines shortly. Is this planned in the upcoming backlog? Thanks!

**Comment by garethbrickman** [comment]
@keithkam-yk This feature is not roadmapped in the foreseeable future

**Comment by danielgafni** [comment]
Hey, I started working on this feature as part of [dagster-polars ](https://docs.dagster.io/_apidocs/libraries/dagster-polars)

**Comment by danielgafni** [comment]
Hey @smackesey ! 

It seems like this check can simply be removed in order to support `Polars` DataFrames in `dagster-pandera`. 

Pandera now supports multiple backends and not just Pandas.

**Comment by garethbrickman** [comment]
@danielgafni I think you meant to comment that in the PR?

**Comment by danielgafni** [comment]
No, my PR was started for dagster/polars. At that time I was thinking to do validation in the IOManager. 

However, the lack of Generic annotations support makes this not really possible yet. 

Another way to do validation is inside a DagsterType. dagster-pandera provides a function which converts Pandera schemas to DagsterTypes. 

This code was written by @smackesey, that's why I asked his opinion about it. 

I'll have to start another PR for this (small) change to dagster-pandera.

**Comment by danielgafni** [comment]
Let's wait for pandera to resolve [this](https://github.com/unionai-oss/pandera/issues/1724) issue first
