### ISSUE TITLE
Rethink system storage "is_persistent" flag

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2132]
Right now the docstring is:

```
        is_persistent (bool): Whether the storage is persistent in a way that can cross process/node
            boundaries. Execution with, for example, the multiprocess executor, or with
            dagster-airflow, requires a persistent storage mode.
```

However, our filesystem storage is marked as persistent, which may or may not support crossing node boundaries (e.g., locally-mounted NFS yes, local disk no).

For our storage, we should differentiate between "this will outlast the Dagster process" vs. "this will be accessible across machine boundaries"

**Comment by schrockn** [comment]
I've been thinking about this a bit and I actually think @alangenfeld 's diff https://dagster.phacility.com/D1956 that adds a generic post process step may be a good place to improve the user experience here. At the top level environment, we could check both the storage and the execution config to ensure that they are compatible, providing config-time feedback with a high quality error message.

**Comment by alangenfeld** [comment]
we also need to allow someone to override that a `filesystem` storage is actually safe to use since its for example a mounted NFS

**Comment by sryza** [comment]
I'd like to argue that, aside from catching particular errors that we've observed come up frequently, we should back off from trying to model the interaction between executors and storages.

I think this can get infinitely complicated:
* Executors could place steps in sandboxed environments that don't have access to the outside world.
* Executors could place steps in environments that don't have access to a particular storage system, e.g. if that storage system is an HDFS that can only be accessed from inside the cluster.
* Executors could place steps in environments that are missing the required configuration to access a particular storage system, e.g. AWS credentials for S3.

The approach we've taken with the asset store says "if someone is using a non-single process executor with the default mem_asset_store, raise an informative error.  otherwise, let the user face the error at execution time."  I think this covers the most common case of a user trying to do out-of-process execution but not being aware that there's a storage abstraction this interferes this. If we observe confusion in other settings, we could widen this.

So going to close this, but feel free to open if you feel otherwise.
