### ISSUE TITLE
Dagster does not allow to specify time zone along cron in scheduled partitioned jobs

### ISSUE THREAD

**Issue by OmranKaddah** [dagster-io/dagster#21697]
### Dagster version

1.7.3

### What's the issue?

```
job_scheduler = build_schedule_from_partitioned_job(my_job, 
                                                                name="the_job",
                                                                hour_of_day=12,
                                                                minute_of_hour=30,
                                                                execution_timezone="Europe/Berlin")
```

E   dagster._check.CheckError: Invariant failed. Description: Cannot provide both cron_schedule / execution_timezone parameters and day_of_month / day_of_week / hour_of_day / minute_of_hour parameters to build_schedule_from_partitioned_job.

I find it absurd that I cannot specify the timezone

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment]
The reason you cannot specify both the `cron_schedule/execution_timezone` parameters and the `day_of_month/day_of_week/hour_of_day/minute_of_hour` parameters at the same time when creating a schedule from a partitioned job is due to the design of the Dagster scheduling system. The `build_schedule_from_partitioned_job` function is designed to create a schedule that aligns with the partitioning of the job. This means that the schedule's frequency and timing should match the intervals defined by the job's partitions.

When you define a partitioned job, you are effectively setting up a structure for how the data should be processed over time. For example, if you have a job that processes data daily, you would set up daily partitions. The schedule for this job should then naturally run once per day to process each partition.

The `day_of_month`, `day_of_week`, `hour_of_day`, and `minute_of_hour` parameters are used to specify the exact time within the partition's interval when the job should run. These parameters are meant to provide a convenient way to set the schedule based on the partition's natural frequency without having to manually calculate the corresponding cron expression.

On the other hand, the `cron_schedule parameter` allows you to specify a custom cron expression that defines the schedule's frequency and timing in a more granular and flexible way. The `execution_timezone` parameter is used in conjunction with `cron_schedule` to ensure that the schedule runs at the correct local time, taking into account time zone differences.

Allowing both sets of parameters to be specified would create ambiguity and potential conflicts in the scheduling logic. For instance, if you set a daily partition but then provide a cron expression that runs every hour, it would be unclear how the schedule should reconcile the hourly cron expression with the daily partitioning of the job.

To maintain clarity and prevent such conflicts, Dagster requires you to use either the partition-based parameters or the cron-based parameters , but not both. This ensures that the schedule is consistent with the partitioning of the job and that there is a single source of truth for when and how often the job should run.

**Comment by OmranKaddah** [comment]
Just a note to those who are reading this and wondering what to do about the time zone. This can be set in DailyPartitionsDefinition. @garethbrickman thanks for the detailed explanation.
