### ISSUE TITLE
deep link to step in run

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2177]
add a way to deep link to a step with-in a run which puts that step in to the "focused" state

**Comment by mgasner** [comment]
cf #2226

**Comment by bengotow** [comment]
This is actually possible already! We allow you to link to a run with the log filter box prefilled via the `?q=<filter>` syntax. Because we currently implement step selection via a filter (admittedly kind of a hack), you can do this:

http://localhost:3000/runs/airline_demo_ingest_pipeline/6c8af9f5-bd90-414a-8641-460fd6b46ce4?q=step:ingest_q2_sfo_weather.compute

And that'll focus the step in the gaant view and filter the logs to that step. Does that do the trick?

**Comment by natekupp** [comment]
@alangenfeld can I close this?

**Comment by schrockn** [comment]
I think the interesting question is where you want the deep link to from

**Comment by catherinewu** [comment]
going to mark as closed, @alangenfeld / @schrockn feel free to re-open if there is further work here?
