### ISSUE TITLE
Fix inconsistencies between timezones on scheduling page and runs page 

### ISSUE THREAD

**Issue by helloworld** [dagster-io/dagster#2188]
On the scheduling screen, the schedule time is in UTC time but the run screen shows the time in local time

**Comment by yuhan** [comment]
I executed a run at 15:52 PST. Here's what I got in each screen
- Runs: 3/19/2020, 8:52:32 AM 
- Event timestamp: 22:52:31.084
- Schedule: local schedule

Seems like schedule time is in local time, event timestamp is in UTC.
- I think it's ok to have schedule time in local time because this is how cron gets configured. 
- I believe event timestamp should be in UTC, i.e. all meta data should be in UTC

But time on "Runs" screen seems incorrect in any time zone.
- Looks like it thought "15:52" was UTC, then converted to local, and showed "8:52"
![image](https://user-images.githubusercontent.com/4531914/77122376-afc6c000-69fa-11ea-83bf-d3d82465e421.png)

**Comment by helloworld** [comment]
This seems like a problem, but I'm a bit confused. Could I see what your schedule looks like?

**Comment by helloworld** [comment]
Also for context, we store most timestamps using unix time, and render them in Dagit using `unixTimestampToString`: https://dagster.phacility.com/source/dagster/browse/master/js_modules/dagit/src/Util.tsx$4-9

**Comment by yuhan** [comment]
I just kicked off a scheduling job. It's scheduled for 04:35 PM (local)
Schedule shows local time
![image](https://user-images.githubusercontent.com/4531914/77124386-f36ff880-69ff-11ea-9eac-aab8bf2ab1a5.png)

Runs shows a weird time 9:35 AM
![image](https://user-images.githubusercontent.com/4531914/77124368-ee12ae00-69ff-11ea-8294-7595d4a7dc23.png)

UTS is supposed to be 23:35
![image](https://user-images.githubusercontent.com/4531914/77124453-25815a80-6a00-11ea-94dd-0953c2c95aa4.png)

**Comment by yuhan** [comment]
![image](https://user-images.githubusercontent.com/4531914/77578013-061d7e00-6e95-11ea-8e92-0e50dedf27ca.png)
Unfortunately, the problem was in the storage layer -- we didn't storage the run's start_time and end_time in UTC before. So, we had to make this change backwards incompatible, meaning:

**all the runs created after this change will have correct timestamp stored, but the runs before would still keep the wrong timezone shift.**

**Comment by yuhan** [comment]
Potential followup:
We may need to do a DB migration to make the historical timestamp right
