### ISSUE TITLE
Inaccurate timing for resource spinup (probably) in airline demo

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2223]
The resource init time for the spark context is not being capture by the new events. This is single proc in the global event stream.

![Screenshot 2020-02-28 09 28 20](https://user-images.githubusercontent.com/28738937/75570819-ccc82e80-5a0c-11ea-994e-607293705929.png)

**Comment by prha** [comment]
Yeah, this is just because the spark resources are lazily spun up...

Here's a screenshot of a pipeline that just runs the same simple spark solid twice in a row (creating a single row dataframe):

![Screenshot 2020-02-28 10 24 11](https://user-images.githubusercontent.com/1040172/75575204-91c9f900-5a14-11ea-8c1b-def52c2ec36f.png)

**Comment by prha** [comment]
I suppose in the resource config, we could add an option to force explicit spin up (by doing something trivial like spinning up a single row dataframe).

**Comment by prha** [comment]
fixed in https://dagster.phacility.com/D2165
