### ISSUE TITLE
Deep links to solids seem to be borked in dagit

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2226]
when i run dagit on the inputs pipeline, i.e. from the `intro_tutorial` directory run `dagit -f inputs.py -n inputs_pipeline -p 3005`, if i then just load the url `dagit/pipeline/inputs_pipeline:/read_csv/`, i get a console error that reads `Error: Parent solid is not a composite - how did this happen?` but, if i load the url `pipeline/inputs_pipeline` and then click on the `read_csv` solid (which appears to navigate to the same url as above), no error and everything displays as expected

**Comment by bengotow** [comment]
Looking in to this!

**Comment by bengotow** [comment]
Ahhh ok I see what's happening, at first I thought this was a data loading / caching issue but `read_csv` isn't a composite.

It's a little bit nasty but Dagit differentiates between the path with the trailing slash and without. The last path component is the selection, and a trailing `/` indicates it should be "inside" the solid with nothing selected.

eg:
# at root level with read_csv selected
http://localhost:3000/pipeline/inputs_pipeline:/read_csv

# at read_csv level with nothing selected
http://localhost:3000/pipeline/inputs_pipeline:/read_csv/

I will change the behavior a bit so that if it finds itself with a trailing slash that is incorrect / impossible, it just backs out a level.

**Comment by bengotow** [comment]
Fixed by https://dagster.phacility.com/D3220!
