### ISSUE TITLE
Dagster CLI `--log-level` behavior to match dagster.yaml `python_log_level`

### ISSUE THREAD

**Issue by cmpadden** [dagster-io/dagster#22333]
### Dagster version

dagster, version 1.7.3

### What's the issue?

Setting the `--log-level` and `--code-server-log-level` flags does not suppress logging in `context.log` messages.

```
"""
USAGE
    dagster dev -f dagster-logging-example.py --code-server-log-level warning --log-level warning
"""

from dagster import AssetExecutionContext, Definitions, asset


@asset
def example_asset(context: AssetExecutionContext):
    context.log.info(":wave:")


defs = Definitions(assets=[example_asset])
```

```
2024-06-06 12:57:33 -0400 - dagster - DEBUG - __ASSET_JOB - 4f851bde-ef71-4ae9-8994-92d08d3147bb - 79853 - LOGS_CAPTURED - Started capturing logs in process (pid: 79853).
2024-06-06 12:57:33 -0400 - dagster - DEBUG - __ASSET_JOB - 4f851bde-ef71-4ae9-8994-92d08d3147bb - 79853 - example_asset - STEP_START - Started execution of step "example_asset".
2024-06-06 12:57:33 -0400 - dagster - INFO - __ASSET_JOB - 4f851bde-ef71-4ae9-8994-92d08d3147bb - example_asset - :wave:
2024-06-06 12:57:33 -0400 - dagster - DEBUG - __ASSET_JOB - 4f851bde-ef71-4ae9-8994-92d08d3147bb - 79853 - example_asset - STEP_OUTPUT - Yielded output "result" of type "Any". (Type check passed).
```

However, setting `python_log_level` in `dagster.yaml` works as expected.

```
$ cat dagster.yaml
python_logs:
  python_log_level: WARNING

$ export DAGSTER_HOME=$(pwd)

$ echo $DAGSTER_HOME
/Users/colton/src/example_project

$ dagster dev -f dagster-logging-example.py
```

Is this intended behavior, or a possible bug?

### What did you expect to happen?

I would expect setting `--log-level warning` on the CLI would suppress `INFO` level statements.

### Deployment type

Local

### Additional information

See Slack conversation here:
https://dagster.slack.com/archives/C01U954MEER/p1717678439716179

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by cmpadden** [comment]
It's very possible that this is a simple misunderstanding on how `--log-level` should function, but I wanted to get clarification. Thanks.

https://docs.dagster.io/_apidocs/cli#cmdoption-dagster-dev-log-level

**Comment by mattjmcelroy** [comment]
According to what I'm seeing in the code base, it's likely this is intended behavior when logging step, job, and resource events.  I reproduced this behavior during asset materialization.

The log_step_event(), log_job_event(), and log_resource() functions each log using the log_dagster_event() function in the DagsterLogManager class.

DagsterLogManager inherits from Python's logging.Logger class and overrides the log() function.

Within this overridden function, we see that the previous authors intended to log Dagster events regardless of level by adding the "or" clause to what is usually a simple check to determine whether the log level is enabled for the logger.

From line 421 in [python_modules/dagster/dagster/_core/log_manager.py](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/log_manager.py):
```     
        # log DagsterEvents regardless of level
        if self.isEnabledFor(level) or (
            "extra" in kwargs and LOG_RECORD_EVENT_ATTR in kwargs["extra"]
        ):
            self._log(level, msg, args, **kwargs)
```

Based on this observation, I recommend this ticket be closed if this is, in fact, the intended behavior.

**Comment by cmpadden** [comment]
Thanks for that research, @mattjmcelroy.

@OwenKephart I see that you worked on this section of code way back in 2021. Would you be able to confirm that this is expected behavior? If so, I can close this one out. Thanks!

**Comment by OwenKephart** [comment]
@mattjmcelroy is correct that this was intended behavior, although I don't believe it's a true technical constraint of the system. We do use the logging machinery to wire dagster events through to the core instance storage methods, and so that certainly needs to be invoked regardless of the level of the message, but I could imagine a scheme that only invokes that specific handler, rather than the ones that just emit to stdout.

So I'll leave it up to you @cmpadden if you want to leave this open, as I do think there's likely a way to "fix" this behavior. In essence, it was intended, but the original intention is not really "binding".

**Comment by cmpadden** [comment]
Gotcha, thanks for the further clarification! I'll go ahead and close this for now, but if someone stumbles on this issue in their searching, feel free to comment if you feel otherwise. Thanks!

**Comment by mattjmcelroy** [comment]
Sounds like there is possibly some tribal knowledge that could be beneficial if documented, given that the current behavior isn't obvious from the docs or code.  Here are a few choices if we choose to improve further:

1. Invoke a specific handler per @OwenKephart and omit events from stdout so they are only wired through the core instance storage methods.  Only log to stdout if DEBUG is set.
2. Simply update the log section of the docs to specify that DEBUG event logs may appear regardless of the log level currently set.
3. Add a CLI switch with accompanying logic to omit event logs to stdout unless DEBUG is set (and docs in log section to explain).  Maintain current behavior if switch not present.

The biggest problem I see with option 1 is that clients may be unknowingly depending on the event logs or simply expect them.  Could be disruptive if they suddenly disappear after a release.

Option 2 would be the minimum - @OwenKephart you seem to know a lot about this so that decision is yours.

Option 3 may be the optimal solution.  However, it would require the most work and I'm assuming priority is low.
