### ISSUE TITLE
Really noisy project “releases”

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#2330]
It looks like a CI system started continuously producing [releases](https://github.com/dagster-io/dagster/releases) on this repo a while ago. As a user, this makes it really hard to find actual releases like [0.7.5](https://github.com/dagster-io/dagster/releases/tag/0.7.5) among the endless stream of intermediate “releases”. I also use [newreleases.io](https://newreleases.io) to subscribe to project releases, and the constant stream of “releases” for dagster has made it useless for this project.

Can the stream of releases be reconsidered? I think releases should be used for actual version releases, not for every CI build.

**Comment by mgasner** [comment]
It doesn't seem like every one of our tags should also be marked a release.

**Comment by mgasner** [comment]
There is an open feature request with GitHub https://github.community/t5/How-to-use-Git-and-GitHub/Tag-without-release/m-p/7906 -- but even though all our tags show up as releases in the Github UI, they don't show up in the GitHub GraphQL API results if you query, e.g.:

```
{
  repository(name: "dagster", owner: "dagster-io") {
    releases(first: 100) {
      nodes {
        id
        publishedAt
        description
        tagName
      }
    }
  }
}
```

It's tricky -- the UI is clearly unusable, this is a known issue (for about 5 years) and no one at Github cares -- and it's also probable that newreleases.io is using the wrong API to find new releases.

PyPI has the correct list:  https://pypi.org/project/dagster/#history

Note that not all of these are "releases" in the GitHub API sense because we aren't doing anything to create and tag the releases on GitHub as part of our release automation.

**Comment by mgasner** [comment]
We could try something like https://github.com/dagster-io/dagster/releases/tag/__placeholder, but I think we will have to keep refreshing it

**Comment by mgasner** [comment]
phab tags do get cleaned up, maybe only on weeknights?

**Comment by alangenfeld** [comment]
alright fixed this by changing the phabricator staging area - releases page is now functional
