### ISSUE TITLE
Error on dagit UI

### ISSUE THREAD

**Issue by ChocoletMousse** [dagster-io/dagster#2357]
I encountered this issue while following the Dagster [guide](https://docs.dagster.io/latest/learn/guides/partitioning/date_partition_set) to create partitioned sets:

![image](https://user-images.githubusercontent.com/40128954/78808240-0d787780-79bd-11ea-92bd-b8972d60261a.png)

This is the error message: 

_Message: Cannot query field "field" on type "EvaluationStackPathEntry". Did you mean "fieldName"?_
_Path:_ 
_Locations: [{"line":92,"column":13}]_

I'm using:
dagster 0.7.4
dagit 0.7.4
dagster-cron 0.7.4

I don't have this issue when I use dagster 0.7.3 and I'm able to see (and use) the Start Execution button unlike above.

**Comment by schrockn** [comment]
Hey @ChocoletMousse! Could you see if this repros on the latest version? 0.7.6?

**Comment by ChocoletMousse** [comment]
Hey @schrockn, just tried with 0.7.6 and unfortunately I get the same issue.

**Comment by schrockn** [comment]
Ok thanks we will look into it. Thank you for the report!

**Comment by schrockn** [comment]
And to be clear both dagit, dagster, and dagster-graphql are 0.7.6?

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by ChocoletMousse** [comment]
Yes, all three are on 0.7.6. It runs fine on 0.7.3

**Comment by prha** [comment]
Hi @ChocoletMousse ... 

I don't see any reference to `field` as a part of `EvaluationStackPathEntry` in the `0.7.4` (or later) releases.

I suspect that either a rogue process running `0.7.3` is running the `dagit` frontend or the browser has cached this request for some reason.  Can you check to see what python processes you have running?  Alternatively, what happens if you clear your browser cache?  Do either of those resolve the issue?

I'm happy to help debug live if you want to hop in our slack and direct message me (@prha)...

**Comment by ChocoletMousse** [comment]
Hey @prha ,

Clearing my browser cache fixed the issue, everything is working as expected.

Thanks for the help.
