### ISSUE TITLE
Running build of test image should warn (not fail) without GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2364]
```
$ ./.buildkite/images/docker/test_project/build.sh 3.6.8
+ PYTHON_VERSION=3.6.8
+ pushd /Users/yuhan/dev/dagster/.buildkite/images/docker/test_project
~/dev/dagster/.buildkite/images/docker/test_project ~/dev/dagster
+ mkdir -p build_cache
./.buildkite/images/docker/test_project/build.sh: line 28: GOOGLE_APPLICATION_CREDENTIALS: unbound variable
```

**Comment by yuhan** [comment]
but GOOGLE_APPLICATION_CREDENTIALS is still a requirement right? 
Should we just print out some message when it is not set or are you suggesting skip it and still build the image?

**Comment by yuhan** [comment]
Per offline discussion, dagster-airflow is still using gcp (https://github.com/dagster-io/dagster/search?q=test_gcs_storage&unscoped_q=test_gcs_storage), which makes it harder to get rid of the gcp cred in test image.

We may be able to mock GCP without loading real creds, then we could point those tests at the mocks instead of putting GOOGLE_APPLICATION_CREDENTIALS in test image

**Comment by natekupp** [comment]
given revised image building infrastructure I don't think this important to fix; closing
