### ISSUE TITLE
Equivalent of log level configuration for Dagster+

### ISSUE THREAD

**Issue by zyd14** [dagster-io/dagster#23979]
### What's the issue or suggestion?

Is there an equivalent for the logging configurations described [here](https://docs.dagster.io/concepts/logging/python-logging#configuring-global-log-levels-) for Dagster+ users? All the examples use `dagster.yaml`, which obviously doesn't exist in Dagster+. It would generally be helpful for the docs to note that these examples don't apply to Dagster+, and provide links to any docs that show how to configure logging in Dagster+

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi zach - dagster.yaml actually does exist on your agent in Dagster+, and you can use this same field there. Here's the corresponding helm chart configuration field if you're using a kubernetes agent, for example: https://artifacthub.io/packages/helm/dagster-cloud/dagster-cloud-agent?modal=values&path=pythonLogs

Point very much taken about improving these docs so that they clearly explain how to do this in both Dagster OSS and Dagster+.

**Comment by zyd14** [comment]
Ah okay great, yeah it was unclear to me if the config parameters passed into the agent were the same as the normal `dagster.yaml` file. Thanks for following up!
