### ISSUE TITLE
Dagit should truncate long solid names with ...

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2421]
See under the search box

![image](https://user-images.githubusercontent.com/609349/80822816-5a043c80-8b90-11ea-8d9a-80b2c9f437cb.png)

**Comment by natekupp** [comment]
and pipeline names:

![image](https://user-images.githubusercontent.com/609349/80822973-9899f700-8b90-11ea-9702-1168b665c881.png)

**Comment by natekupp** [comment]
and in playground

![image](https://user-images.githubusercontent.com/609349/80823027-afd8e480-8b90-11ea-8177-37740be12138.png)

**Comment by bengotow** [comment]
This is actually largely mitigated by the new layout since we have more control over the appearance of the pipeline names in the sidebar. I did a quick audit and found that the new pipeline nav was not truncating properly, and also found that typing the pipeline name into the runs filter bar would make it a zillion pixels wide and I fixed both of those.

![image](https://user-images.githubusercontent.com/1037212/83555554-0e68e980-a4d4-11ea-8f3c-b1b2fcf1f53b.png)

Also fixed this problem solid names and a similar issue in the run preview of the execution panel:
![image](https://user-images.githubusercontent.com/1037212/83555757-60117400-a4d4-11ea-8e50-9c372473eb02.png)
![image](https://user-images.githubusercontent.com/1037212/83557232-e929aa80-a4d6-11ea-83d5-86f3f45131bb.png)

**Comment by schrockn** [comment]
what about tool tip over a solid to get name? would help in zoomed out contexts too? just on mouseover not on selection

**Comment by bengotow** [comment]
yeah... I guess it's time for a nice way to do these custom tooltips. It's a bit tricky because this is an SVG so some DOM / React options don't apply, but let me see what I can rig up :)

**Comment by bengotow** [comment]
Ok should be addressed in https://dagster.phacility.com/D3229!
