### ISSUE TITLE
Stream events back from EMR to driver process when using step launcher

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2443]
Just tracking this so we don't forget it. I think we should have a solution to this by the time we push 0.8.0

**Comment by sryza** [comment]
Before diving in here, wanted to outline the challenges and what a potential solution could look like.

Challenges:
* We can't expect a process on EMR to be able to hit an endpoint in the plan process, because the plan process might be behind someone's home internet.
* We can't expect the plan process to be able to hit an endpoint in the process on EMR, because EMR is often behind a VPC.
* S3 is eventually consistent and doesn't support appends
* S3 can be slow, so we'd prefer the compute_fn not to block on writing to it. 

Proposal:
* Background thread in the EMR process periodically rewrites an events file on S3, containing all events that have been yielded by the step so far.
* A background thread in the plan process periodically reads that file, checks whether it contains any events that the plan process hasn't received so far, and, if it does, yields them.  (A foreground thread might also work, but need to interleave it with polling EMR to see if the job is done).

If there were a bajillion events, this would not be an ideal approach, because each event gets written to S3 multiple times, and both the plan process and EMR process need to buffer all events.  I don't think there are a bajillion events though, so should probably be fine?

@schrockn - thoughts? also @natekupp

**Comment by schrockn** [comment]
I think the assumption here is that the number of events written to the event stream in during a single step will *likely* be on the order of dozens, hundreds at most. I suppose if a user created thousands of files in a step a thousand materializations would be emitted.

Users can do whatever they want and could potentially yield a huge number events, but that is not really what the system is designed for. The number of events written should be orders of magnitude less than, say, raw logging. 

The common case will be a small number of events, and I think we should it get working for that at first. I think you could get away from an occasional synchronous write from the EMR process and everything would be fine.

**Comment by natekupp** [comment]
I think this proposal sounds good; the S3 eventual consistency is unfortunately going to make things feel flaky sometimes (I've seen stale reads on the order of many seconds) but I don't know of any other viable alternative here.

For the record, the other approach I've seen (e.g. in Yelp's mrjob) is to scp logs back from the EMR master, but that requires SSH access, which I don't think is something we should depend on.

**Comment by sryza** [comment]
Cool - I think a thousand events would be fine here.  Will go with the approach described.

**Comment by sryza** [comment]
Read side: https://dagster.phacility.com/D2990
Write side: https://dagster.phacility.com/D2968

**Comment by natekupp** [comment]
@sryza given your recent work, closing
