### ISSUE TITLE
selecting steps in the Dagit run viewer using the DSL doesn't correctly filter the log pane

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2472]
![Screen Shot 2020-05-18 at 8 57 09 AM](https://user-images.githubusercontent.com/427016/82233999-a61be480-98e5-11ea-9ca0-6c38c0303240.png)

**Comment by yuhan** [comment]
Do we want to tie the log filter input to the DSL tho? I personally would prefer to separate them, or at least when the log filter changes I don’t want to see the DSL/step selection to change

**Comment by yuhan** [comment]
Because the log filter currently only supports `single step AND single type AND free text`, making it follow the multi-step selection will require to let log filter take multiple steps as well. It surfaces the question of whether we do AND or OR in the log filter. 
I'm thinking of this way: `(step: solid_1.compute OR step: solid_2.compute) AND (type: materialization)`, meaning multiple keys in the same token type will be OR while different token types will be AND.

Beside, it should be that log filter will follow the DSL change but DSL shouldn't follow the log filter changes.
