### ISSUE TITLE
Introduce @repository, eliminate repository.yaml

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2474]
repository.yaml is a liability. It is difficult to explain and adds another varietal of yaml config to our system.

To replace it we produce an `@repository` decorator, similar in spirit to `@pipeline` and friends.

e.g.

```
# in my_repo.py
@repository
def my_repo():
   return [my_pipeline]
```

This would define an object in global scope. Likely RepositoryDefinition.

Our tools would point to a python module (e.g. file). 

The tool would the module and then load the repository in scope.

dagit my_repo.py

By default it would load `__init__.py` so you could just type `dagit` at the root of package where your dagster code lives.

We could even make a special consideration for opening in the enclosing folder (e.g. the folder that contains setup.py) but that is "extra credit."

We may also want to consider eliminating the trick of loading a single pipeline and require a repository.

We can now explain the repository more easily, saying that it's entire purpose is to be the function run when a host process runs the user process. Users could instrument this function with logging or any other custom tooling/systems.

**Comment by schrockn** [comment]
cc: @alangenfeld feel free to add more context

**Comment by mgasner** [comment]
i'm going to break the `__init__.py` behavior into a follow-on diff

**Comment by mgasner** [comment]
additionally dagster-aws up should not use repository.yaml

**Comment by mgasner** [comment]
sigh, couple notes on this --

we may not be able to evade implementing the desired `__init__.py` behavior on the first pass, since all our container-based stuff (k8s, airflow, celery-k8s) relies on being able to just run `dagster-graphql` as the entrypoint. in a run launcher we do not have a reconstructable repo available, so we can't easily pass the cli args through. that means we will need some other kind of default behavior.

i think the `__init__.py` is a little less attractive than it looks b/c it's very tuned to a model where you git clone a source repository or use `COPY` to get it into a docker image -- even then, it's quite unnatural to have `my-package/my_package` be the workdir for the image. what about installing from pip/local pip? then we have something like `WORKDIR /obscure/path/to/python3.7/site-packages/my-package/`? what about installing from wheels?

i also don't think the setup.py approach is likely to be very robust, since setup.py may be costly to run (real code runs in and before the `setup()` function, and it's not at all clear where to look for a top-level repository object (could be any of `packages` or `py_modules`...)

**Comment by alangenfeld** [comment]
So while `dagster` will no longer have a `yaml` entry point with the removal of `repository.yaml`,  we're still going to need a `yaml` entrypoint for `dagster-graphql` / `dagit` - "host processes" in general. This `entrypoint.yaml`, `environtments.yaml`, whatever will act very similar to `repository.yaml` but the purpose will be to specify a number of `dagster` environments to load (and I think give them names).

I imagine something like:

```
foo_module:
  module: pip.installed.module
foo_file:
  file: relative/path/to/python_file
foo_image:
  image: "images.com/dagster-foo:latest"
foo_one_thing:
  file: relative/path/to/file
  fn: define_thing
```

**Comment by alangenfeld** [comment]
Coming from `repository.yaml` - I think that after the initial load - nothing else in the codebase should know bout the `entrypoint.yaml`. It should simply hold on to the individual relevant entry derived from the `yaml`. Currently I imagine the `CodePointer`-esque data tacked on to the `EnvironmentHandle`.

**Comment by mgasner** [comment]
so this will look something like `dagster-graphql -y whatever.yaml`, or by default look for an `entrypoin.yaml` in pwd

**Comment by schrockn** [comment]
We settled on workspace.yaml

https://dagster.phacility.com/D3253
