### ISSUE TITLE
Unexpected GraphQL error: Operation name: PipelineRunLogsSubscription Message: BaseObserver.schedule() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by TzorAL** [dagster-io/dagster#24869]
### Dagster version

dagster, version 1.6.3

### What's the issue?

Operation name: PipelineRunLogsSubscription

Message: BaseObserver.schedule() takes 3 positional arguments but 4 were given

Path: 

Locations: 

### What did you expect to happen?

I'm writing a a docker container for a dagster pipeline I'm making. 
When a specific run is being executed, I get an "**Unexpected GraphQL error**"  
Note, the run is successful, however till the run is complete, I can't see the run logs in real time from the UI  

### How to reproduce?

The code is quite elaborate to provide, however the only difference between this error appearing and not is that Ive transfered my enviromental variables from .env file to the docker compose yaml file 

### Deployment type

Docker Compose

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tobiplay** [comment]
This was resolved in one of the current releases. Bump your version to at least 1.8.4 (core), maybe even 1.8.5. I think that the stack trace hinted at a problem with Watchdog. You can find the changelog [here](https://docs.dagster.io/changelog). Note that there have been a couple of breaking API changes around experimental features since 1.6.5 (core), so you may potentially have to refactor quite a bit of code.

**Comment by gibsondan** [comment]
Merging with https://github.com/dagster-io/dagster/issues/23957 which is the same issue - you can also add a "watchdog<5" pin to your setup.py or requirements.txt to resolve this.
