### ISSUE TITLE
Declarative Automation - materialize only if all parents of an asset have been materialized since the latest materialization

### ISSUE THREAD

**Issue by ske94** [dagster-io/dagster#25145]
### What's the use case?

Right now, we're playing around with ne new declarative automation approach and we really like the new style of defining rules and conditions. It is a bit rough to get started so please excuse me if the requested use case is already possible. 

One of our goals with declarative automation is to materialize assets only if all of its parents have been materialized since the latest materialization of the asset that is targeted by the declarative automation.

Imagine the following scenario (time interval is only exemplary - other time intervals can also occur, it is only important that the time interval of the source assets is different): we have a target asset (which is targeted by declarative automation) with 2 sources which are both updating on a regular basis (one is updated daily and the other one weekly).

What we want to achieve is the following: the target asset should wait with materialization until **both** source assets have been materialized again **after** its latest materialization:

This diagram should sum that up again, making it easier to understand:
![image](https://github.com/user-attachments/assets/d86471c4-5e5c-4319-ab8b-6903303fc67b)

### Ideas of implementation

What we tried to do, is the following...

**Assumption**: Assets are not partitioned and should not be partitioned in our actual scenario

1. We have setup a minimal example (explained below)
2. We tried to use the _on_missing_ condition 
3. We tried to use _newly_updated_ with _since_last_handled_
4. We tried to use the _on_cron_ condition
5. We've defined an automation condition which is mostly based on eager but we've swapped the any_deps_match to all_deps_match.
```python
def get_all_parents_automation_condition() -> AutomationCondition:

    never_materialized_or_all_parents_updated = (
        AutomationCondition.missing().with_label("target was never materialized")
        | AutomationCondition.all_deps_match(
            AutomationCondition.newly_updated()
            | AutomationCondition.will_be_requested()
        ).with_label("all parents updated")
    ).with_label("target was never materilaized or all parents updated")

    any_parents_missing = AutomationCondition.any_deps_match(
        AutomationCondition.missing() & ~AutomationCondition.will_be_requested()
    ).with_label("any parents missing")

    any_parents_in_progress = AutomationCondition.any_deps_match(
        AutomationCondition.in_progress()
    ).with_label("any parents in progress")

    any_parents_failed = AutomationCondition.any_deps_match(
        AutomationCondition.failed()
    ).with_label("any parents failed")

    return (
        never_materialized_or_all_parents_updated.since(
            AutomationCondition.newly_updated()
        )
        & ~any_parents_missing
        & ~any_parents_failed
        & ~any_parents_in_progress
        & ~AutomationCondition.in_progress()
    ).with_label("Materialize on all parents updated")
```

Our minimal example:
```python
@asset()
def source1(context: AssetExecutionContext):
    context.log.info("I'm source 1")


@asset()
def source2(context: AssetExecutionContext):
    context.log.info("I'm source 2")


@asset(
    deps=[source1, source2], automation_condition=get_all_parents_automation_condition()
)
def target(context: AssetExecutionContext):
    context.log.info("I'm target")


defs = Definitions(assets=[source1, source2, target])
```

**What is the outcome?**

Regarding 1 & 2)
It didn’t work as expected and we feel like this approach is really focussed towards partitioned assets?

Regarding 3)
With _on_cron_ we’re able to atleast partially achieve the desired outcome, but we don’t like the fact that it is bound to a fixed ‚lookback‘ schedule.

Regarding 4) 
We have discovered that the time reference point of the condition is the last tick of the sensor. If both updates are recognized in the same sensor tick, we achieve the desired outcome. If not (e.g. source 2 was materialized 5 minutes after source 1) it looks like this:

First sensor tick (right after source 1 was materialized):
![image](https://github.com/user-attachments/assets/d4c1a846-f0dc-4bbc-ba1a-82a83da06109)

Second sensor tick (right after source 2 was materialized):
![image](https://github.com/user-attachments/assets/224ef56e-be94-41bf-bd4f-31470232d5c9)

**Conclusion**
For us it would be really helpful to be able to build a _AutomationCondition_ that checks if the dependencies of an asset have been updated **since** the **last materialization** of the targeted asset. So basically something like newly_updated, but with reference to the last update of an asset and not the sensor tick.

### Additional information

Generally, we feel like the approach is a bit focussed towards partitions. We feel like that in a partition based scenario it would be easier to achieve this setup by using the _on_missing_ condition. Is this the case or is the aim to enable both partitioned and unpartitioned assets?

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
Hi @ske94 ! Thanks for the detailed writeup here.

In general, we discourage this type of setup, as it is very easy to get into a bad / confusing state.

To give an example timeline, imagine we start off in a "good" state -- the the weekly and daily assets have just updated, and the downstream was kicked off in response.

From here, things proceed through the start of the week as usual, the daily source keeps updating, but the downstream continues to wait for the weekly, as expected.

Then, for whatever reason (perhaps a backfill), the weekly is updated in the middle of the week. Because the daily has updated already, this leads to the downstream immediately kicking off, which is not what you want here.

But worse than this single unwanted run is that this desynchronization issue can persist. Imagine you actually have two weekly upstreams instead of one weekly and one daily. Now, when you do this backfill in the middle of the week, the downstream doesn't kick off (as the other weekly asset wasn't backfilled). But then, at the start of next week, the other weekly asset happens to materialize before the one you backfilled. Now, the downstream will immediately kick off, even though one of its parents doesn't yet have the newest data.

When the second weekly asset fills in, the downstream won't kick off again, leading to an essentially continuously out-of-sync downstream.

For this reason, we recommend using the `on_cron` condition instead, as the cron condition forces a certain amount of synchronization (and I acknowledge that, as you say, this forces you into a fixed lookback schedule as a consequence).

However, if you definitely need this behavior, the key piece here would be:

```python
AutomationCondition.all_deps_match(
    AutomationCondition.newly_updated().since(
        AutomationCondition.asset_matches(<target_asset_key>, AutomationCondition.handled())
    )
)
```

This lets you individually track each upstream dependency and ensure that it's been updated more recently than the target asset. We don't currently have a built-in way to point a condition at the asset key a condition is applied to, so you'd need to hard-code that key in the `asset_matches()` condition.
