### ISSUE TITLE
fan_in_fan_out pipeline does not render properly during execution

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2562]
![Screenshot 2020-06-10 08 19 04](https://user-images.githubusercontent.com/28738937/84286088-1851a480-aaf3-11ea-9afd-f4d42c9ded99.png)

**Comment by catherinewu** [comment]
This seems like a rendering issue as the pipeline does succeed on the backend, @bengotow?

**Comment by catherinewu** [comment]
Narrowed down cause to gaant chart rendering. If I remove the gaant chart, the pipeline run logs show up as expected and pipeline succeeds. 
<img width="1792" alt="Screen Shot 2020-06-10 at 11 48 30 PM" src="https://user-images.githubusercontent.com/6024687/84353967-f6990180-ab74-11ea-8daa-9b63dc277524.png">

**Comment by catherinewu** [comment]
Adding time.sleep(500) to the body of each solid still leads to a state where the gaant chart and pipeline logs both dont render

**Comment by catherinewu** [comment]
tried using the react profiler but the profiler can't even initialize. leading me to believe that theres something wrong with initial load (as opposed to streaming events). weird thing is i have loaded /ran similarly large pipelines recently

**Comment by bengotow** [comment]
Ahh ok... I did some investigation here this evening and it looks like this test case is causing near-infinite recursion in this section of the layout algorithm because there are so many paths through the DAG and it's trying to ensure the gaant chart is left => right. I think I already fixed this somewhere else in Dagit using a presort to limit the search space, will see if we can do this again!

<img width="664" alt="image" src="https://user-images.githubusercontent.com/1037212/84858914-b97bb600-b031-11ea-815c-3f6604e2b959.png">

**Comment by bengotow** [comment]
This should be resolved by https://dagster.phacility.com/D3534
