### ISSUE TITLE
Generate unique names for ephemeral repos

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2594]
Maybe this is working as designed, but it was jarring to have a mode-less pipeline and then add my first mode to the pipeline def and see this:

![image](https://user-images.githubusercontent.com/609349/84520780-eeca8180-ac88-11ea-9ceb-aaee208df85f.png)

**Comment by natekupp** [comment]
ok, this is a real issue—we preserve mode even when I switch files I'm pointing to:

`dagit -f file_one.py` <- with mode "prod" - select prod in drop down

`dagit -f file_two.py` <- with no modes defined - drop down is now red (I assume because "prod" is preserved)

**Comment by schrockn** [comment]
I would suspect that either a) local storage is key'ed off pipeline name 2) or it is key'ed off the full handle "location.repo.pipeline" but collide because we generate names for ephemeral repos that are identical.

If the latter is true then we can kill two birds with one stone by changing the name of ephemeral repos to include the pipeline name (or even the snapshot id)

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by hellendag** [comment]
This surfaces as an issue in the Playground UI, but is caused by repository name conflicts for ephemeral repos. Is it possible to hash the filename or something like that, to avoid this collision?

**Comment by natekupp** [comment]
cc @gibsondan  did the default naming changes fix this?

**Comment by yuhan** [comment]
@gibsondan bumping ^ is this still an issue?
