### ISSUE TITLE
Build a Celery-less K8s deployment

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2611]
* build a `K8sJobEngine` that submits jobs per step directly
* support `resource` settings on all `Executor` and `RunLauncher` submitting jobs

**Comment by ikendoit** [comment]
This maybe exactly what I have been looking for. 
Currently, running Celery machines adds more complexity to our cluster. 

What I have in mind is: 
Dagster -> submits GKE Job ( with configurable resource limits )-> run the entire pipeline with that GKE job. 

Very similar to GCP Cloud Run. 

Currently in my project, we are having 5 high-mem Celery workers running 24/7, and it is expensive (imo). Sometimes, the workers stay idle due to lack of jobs. Implementing a custom horizontal-pod-auto-scaler is doable but it requires some maintenance that we don't have bandwidth for atm. 

Not sure if this is what Travis was thinking about on the Slack channel. But this is how I understand "celery-less k8s deployment".

**Comment by alangenfeld** [comment]
@ikendoit if you set the `executor` to `multiprocess` in your run config instead of using `celery` or `celery-k8s`, I think you may be able to achieve what you are looking for today. Provided that works as expected, you can turn off the celery queues in your helm chart by setting `celery.enabled` to false.

**Comment by ikendoit** [comment]
That is fascinating, I will try it tonight and let you know how it goes!!

**Comment by ikendoit** [comment]
Hello @alangenfeld ,

Unfortunately, it doesn't work. I got the error "dagster.check.CheckError: Invariant failed. Description: celery-k8s execution must be configured in pipeline execution config to launch runs with CeleryK8sRunLauncher"

My Pipeline is currently using CeleryK8sRunLauncher so that I can configure resource-limits for the job-run, which K8sRunLauncher is not providing at the moment ( to my understanding ).

**Comment by alangenfeld** [comment]
Ah I see, adding supporting that to the list of things to do.

**Comment by ikendoit** [comment]
That is awesome, thank you Max!
Can't wait to try it out!!
