### ISSUE TITLE
throw useful error when alias is invoked on solid output

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2670]
Currently If someone accidentally does

```
@pipeline
def example():
  my_solid().alias('rename_my_solid') # should be my_solid.alias('rename_my_solid')()
```

They get an error message that is pretty difficult to decipher. Since we control the object returned by solid invocation in composition functions, we could override `alias` and throw a good error message to help people find the issue.

**Comment by iKintosh** [comment]
Hi, @alangenfeld 
Thinking to give it a try as a new contributor. Is there anything I should know besides https://docs.dagster.io/docs/community/contributing ?

**Comment by alangenfeld** [comment]
That should cover the basics. Take a look at https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_composition.py for examples of how we do tests against expected error messages

**Comment by iKintosh** [comment]
**Updates:**
Found interesting behavior. If you run 
```python
@pipeline
def example():
  my_solid

execute_pipeline(example)
```
or 
```python
@pipeline
def example():
  my_solid.alias('something')

execute_pipeline(example)
```

It does not do anything at all. 
Also according to Dagster, it is not an error, since uninvoked solids does not make it to `_invocations` attribute of `InProgressCompositionContext` https://github.com/dagster-io/dagster/blob/baead6ca754b7f89fdea3b6822168444985ee48c/python_modules/dagster/dagster/core/definitions/composition.py#L195-L197

As I understand it cannot be checked the same way as https://github.com/dagster-io/dagster/blob/baead6ca754b7f89fdea3b6822168444985ee48c/python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_composition.py#L615-L622
since it uses https://github.com/dagster-io/dagster/blob/baead6ca754b7f89fdea3b6822168444985ee48c/python_modules/dagster/dagster/core/definitions/composition.py#L251-L253
which requests that `return_one` must be called before calling `add_one` for `_process_argument_node` to check the instance of `return_one` output.

**Comment by alangenfeld** [comment]
Ya that problem is real tough to detect (maybe impossible?). 

Just to clarify, this particular issue is about calling `.alias` on `InvokedSolidOutputHandle` which would happen is someone accidentally invoked the solid before calling alias, as in `solid().alias('oops')`
