### ISSUE TITLE
Tutorial examples should be runnable 

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2820]
We omitted the import here: https://dagster.slack.com/archives/CCCR6P2UR/p1597505605469100

However, in this case the original file: https://github.com/dagster-io/dagster/blob/master/examples/docs_snippets/docs_snippets/intro_tutorial/advanced/solids/reusable_solids.py include a `if typing.TYPE_CHECKING` branch, which is a little rough for inclusion in an example

**Comment by nancydyc** [comment]
> We omitted the import here: https://dagster.slack.com/archives/CCCR6P2UR/p1597505605469100

The code snippets the user provided is Advanced: Solids instead of Basics of Solids. The [multiple_outputs.py](https://github.com/dagster-io/dagster/blob/master/examples/docs_snippets/docs_snippets/intro_tutorial/basics/e02_solids/multiple_outputs.py) is runnable now.

> if typing.TYPE_CHECKING branch
seems like a recap for the previous chapter [Mypy Compliance](https://docs.dagster.io/tutorial/types#mypy-compliance)

**Comment by sryza** [comment]
I believe the mentioned examples are now runnable, so going to close this
