### ISSUE TITLE
Celery executor does not work with gRPC server

### ISSUE THREAD

**Issue by thedmi** [dagster-io/dagster#2823]
Sample that reproduces the problem: https://github.com/thedmi/dagster-celery-docker-example/tree/celery-with-grpc-server

The docker compose setup of above repository contains a infrastructure, a GRPC server, dagit and celery workers. Dagit is able to successfully list the pipelines that the GRPC server returns. However, when running a pipeline, the worker fails with the following exception:

```
worker-generic_1  | [2020-08-17 11:27:23,218: ERROR/ForkPoolWorker-8] Task execute_plan[158517d4-a072-4ae5-9ce0-079bd864015a] raised unexpected: FileNotFoundError(2, 'No such file or directory')
worker-generic_1  | Traceback (most recent call last):
worker-generic_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
worker-generic_1  |     R = retval = fun(*args, **kwargs)
worker-generic_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
worker-generic_1  |     return self.run(*args, **kwargs)
worker-generic_1  |   File "/usr/local/lib/python3.8/site-packages/dagster_celery/tasks.py", line 32, in _execute_plan
worker-generic_1  |     execution_plan = create_execution_plan(
worker-generic_1  |   File "/usr/local/lib/python3.8/site-packages/dagster/core/execution/api.py", line 558, in create_execution_plan
worker-generic_1  |     pipeline_def = pipeline.get_definition()
worker-generic_1  |   File "/usr/local/lib/python3.8/site-packages/dagster/core/definitions/reconstructable.py", line 98, in get_definition
worker-generic_1  |     self.repository.get_definition()
worker-generic_1  |   File "/usr/local/lib/python3.8/site-packages/dagster/core/definitions/reconstructable.py", line 37, in get_definition
worker-generic_1  |     return repository_def_from_pointer(self.pointer)
worker-generic_1  |   File "/usr/local/lib/python3.8/site-packages/dagster/core/definitions/reconstructable.py", line 341, in repository_def_from_pointer
worker-generic_1  |     target = def_from_pointer(pointer)
worker-generic_1  |   File "/usr/local/lib/python3.8/site-packages/dagster/core/definitions/reconstructable.py", line 290, in def_from_pointer
worker-generic_1  |     target = pointer.load_target()
worker-generic_1  |   File "/usr/local/lib/python3.8/site-packages/dagster/core/code_pointer.py", line 250, in load_target
worker-generic_1  |     module = load_python_file(self.python_file, self.working_directory)
worker-generic_1  |   File "/usr/local/lib/python3.8/site-packages/dagster/core/code_pointer.py", line 129, in load_python_file
worker-generic_1  |     module = import_module_from_path(module_name, python_file)
worker-generic_1  |   File "/usr/local/lib/python3.8/site-packages/dagster/seven/__init__.py", line 115, in import_module_from_path
worker-generic_1  |     spec.loader.exec_module(module)
worker-generic_1  |   File "<frozen importlib._bootstrap_external>", line 779, in exec_module
worker-generic_1  |   File "<frozen importlib._bootstrap_external>", line 915, in get_code
worker-generic_1  |   File "<frozen importlib._bootstrap_external>", line 972, in get_data
worker-generic_1  | FileNotFoundError: [Errno 2] No such file or directory: 'dagster_pipeline.py'
```

It appears that the celery worker does not pick up the workspace.yaml where the connection to the GRPC server is defined. The fact that the `dagster-celery CLI` does not support a  `--workspace` switch supports this assumption.

**Comment by gibsondan** [comment]
Hi! As you observed, the dagster-celery workers don't currently operate in terms of workspaces. Since they perform the actual execution, they take in the file or module that needs to be executed - so they need to have access to the dagster_pipeline.py file.

I was able to get your example working by combining the deployment-files and workflows directories, so that the celery workers have access to the volume with the pipeline file.

Is that different than what you were expecting? If so let us know, we're still determining how these systems should interact.

**Comment by thedmi** [comment]
Hi, thanks for the quick response. I understand that bind-mounting the `workflows` directory on the workers solves the problem. However, it only solves it in the sample. The "real" deployment will consist of multiple machines that run the workers, and they don't have a shared volume.

I think this is one of the main challenges that people face when moving to production with their workloads. I find the approach with the gRPC server very good, much better than Prefect's mechanism of distributing workflow code (I found it to be quite brittle). And I think the distributed cases (Dagster/Celery, Dagster/Dask, etc) benefit most from it.

Is this something that is planned to be supported in Dagster Celery? If not, what is the suggested alternative? A shared network drive (an often suggested solution) is unfortunately not possible for us.

**Comment by gibsondan** [comment]
Interesting. I think how we proceed here depends on what exactly you want the celery workers to be doing / where exactly you want the execution to be happening.

Currently the gRPC server is able to either execute the pipeline itself via an API call (which could be triggered from a celery worker, but the actual execution would still be happening on the gRPC server), or expose a code pointer for the celery worker to execute - but we don't have a way for the worker to run the execution without access to the code, since the steps in the pipeline execution could involve arbitrary Python code.

Also happy to talk more in #general on our Slack if that's faster: https://dagster-slackin.herokuapp.com/

**Comment by thedmi** [comment]
As discussed on Slack: I thought gRPC could be used to share code between workers, but that's not the case. Thanks for clarifying!
