### ISSUE TITLE
Import error running dagster pipeline execute -m

### ISSUE THREAD

**Issue by jamespatrikrichards** [dagster-io/dagster#2833]
```
WORKS:
dagster pipeline execute -f module1/submodule1/submodule2/submodule3.py
                         -a my_fancy_repo 
                         -p my_fancy_pipeline
                         --mode some_mode
                         -c config.yaml

IMPORT ERROR: no module named module1
dagster pipeline execute -m module1.submodule1.submodule2.submodule3
                         -a my_fancy_repo 
                         -p my_fancy_pipeline
                         --mode some_mode
                         -c config.yaml
```

Running from the root folder containing `module1`. All cross imports in submodules are of the format `from module1.submodule1.... import a, b, c`.

Tried to use `-d` but get `Error: Invalid set of CLI arguments for loading repository/pipeline. See --help for details.`

Dagster version 0.9.1

**Comment by catherinewu** [comment]
linking slack discussion for context: https://dagster.slack.com/archives/CCCR6P2UR/p1597853088491000

**Comment by catherinewu** [comment]
Copy and pasting from slack: "...this is because we disabled using the current working directory to resolve modules. We should consider allowing you to explicitly specify the working directory though. ideally [module flag] would work on its own, but this has downstream effects on how the scheduled executions are stored and run. Would want to avoid creating multiple copies of the same schedule, just invoked from different directories"

**Comment by alangenfeld** [comment]
we no have working directory setting support
