### ISSUE TITLE
Dagit should special case handling of "invalid config error" when launching a run

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#2842]
e.g., by popping back to the playground with the error displayed there

Steps to repro:
- Run a pipeline
- Change the config schema
- Hit reexecute

**Comment by sryza** [comment]
FWIW, I don't think the config editor is the right place to direct people in many scenarios where they'd hit this kind of error.  For example, if the run was kicked off via a schedule, the right solution is probably to fix code, not go to the playground.

**Comment by bengotow** [comment]
Hey folks! It sounds like there's not a clear direction for dev on this one so I'm going to go ahead and close it.

Since this was filed, we've also added the ability to "Open in Launchpad...", which I think offers a better way to "adjust config and run again" with proper error handling in place.

<img width="302" alt="image" src="https://user-images.githubusercontent.com/1037212/156261752-b2edd692-0eeb-40db-ba16-acbfa24ae121.png">
