### ISSUE TITLE
Create public, helper API for checking for valid run config in isolation

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2875]
From slack:

"Hi dagster team!
We are using dagster in our production pipeline. Our pipelines have different yaml files depending on the environment (e.g. staging, production). Currently we are facing a problem when changing our yaml files for the run config. It already happened some times that our yaml files aren’t valid, but we only discovered it when the pipeline was executed in production.
Is there any possibility to check for each pipeline if the yaml files contain valid configurations for the pipeline before the pipeline is executed?"

This section of code from EnvironmentConfig.build could easily be it's own function:

```
        mode = mode or pipeline_def.get_default_mode_name()
        environment_type = create_environment_type(pipeline_def, mode)

        config_evr = process_config(environment_type, run_config)
        if not config_evr.success:
            raise DagsterInvalidConfigError(
                "Error in config for pipeline {}".format(pipeline_def.name),
                config_evr.errors,
                run_config,
            
```

**Comment by ministrike3** [comment]
Hey Nick -- I've been following Dagster for a while and would love to start contributing! Does this seem like a reasonable plan of attack: 
1) Make a new function [for the EnvironmentConfig class ](https://github.com/dagster-io/dagster/blob/4a91c9d09b50db93e9174c93a4ada0e138e3a046/python_modules/dagster/dagster/core/system_config/objects.py#L75)
2) Add test [function to system_config_tests](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster_tests/core_tests/system_config_tests/test_system_config.py)

**Comment by sryza** [comment]
Hey @ministrike3 - thanks for offering to help, we would definitely appreciate the contribution!

It probably makes the most sense to define a standalone function, because the `EnvironmentConfig` class is internal.

An interesting question to think through is what happens with "config-mapping".  Some objects in Dagster, e.g. configured resources and composite solids, accept config and then produce "sub config", which also needs to be validated.   https://docs.dagster.io/overview/configuration/#configured explains how this works.  A lot of the logic in `EnvironmentConfig.build` is for handling these cases.

**Comment by OwenKephart** [comment]
https://docs.dagster.io/_apidocs/execution#dagster.validate_run_config
