### ISSUE TITLE
SyntaxErrors / errors triggered from the ExternalRepository API call are rough

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2879]
I was actively iterating on a pipeline, and using the `reload repository` button to incorporate my new changes. With a clear problem in my definition I get this monster:

![Screen Shot 2020-09-03 at 3 51 56 PM](https://user-images.githubusercontent.com/202219/92166003-814c6e00-edfd-11ea-97a6-6aeac510fae3.png)

There has to be a way for us to improve this experience

**Comment by alangenfeld** [comment]
syntax error even more brutal since there is no pointer to where the error is 

![Screen Shot 2020-09-03 at 3 56 29 PM](https://user-images.githubusercontent.com/202219/92166319-0cc5ff00-edfe-11ea-849c-422c040d5420.png)

**Comment by gibsondan** [comment]
For the first thing, sounds like we might need a version of https://dagster.phacility.com/D4087 but for the ExternalRepository call, not just the ListRepositories call. I'm a little surprised to hear this is worse in gRPC vs. CliApi though?

For the second thing, we may need to special case the error output in some way as per https://stackoverflow.com/questions/28836078/how-to-get-the-line-number-of-an-error-from-exec-or-execfile-in-python

**Comment by gibsondan** [comment]
@alangenfeld I'm confused how you managed to hit this issue in an ExternalRepository callsite (and not a LIstRepositories callsite). When I add a bogus required resource key to a solid and hit "Reload Repositories", I get a much more reasonable stack trace, originating from ListRepositories. You'd have to be a real quick-draw to manage to introduce an error between ListRepositories and ExternalRepository so I wonder if some other change has moved the error earlier since this was first filed.

**Comment by gibsondan** [comment]
What I see now in dagit: https://dagster.phacility.com/P93
