### ISSUE TITLE
[dagit] Determine how to disambiguate conflicting pipeline/repo names

### ISSUE THREAD

**Issue by hellendag** [dagster-io/dagster#2933]
Related to the second point in https://github.com/dagster-io/dagster/issues/2923.

It appears that it is currently possible to have pipeline and repo names that conflict, and possibly insufficient disambiguation within dagit to emphasize which pipeline/repo is being worked on at a given time.

- The active URL displays only the pipeline name (and snapshot ID, if applicable), but no information about the repo or repo location. There is therefore no ability to permalink to a specific location-repo-pipeline item, which I could envision being valuable.
- The repo chooser indicates which repo is active, but it might be easy to overlook.

Would it be worth considering permalinks that incorporate repo/location/pipeline to allow direct navigation, and perhaps some more visible distinguishing factor to clarify which repo is being worked on, e.g. breadcrumbs?

cc @bengotow since I'm new in these parts and don't have all the context.

**Comment by helloworld** [comment]
I think adding the repo + location to the URL is a great idea. 

From the other issue:

> Relatedly - we should probably show a context menu to disambiuate if you have multiple matches, such as loading the same pipeline in different repository locations (virtual envs / docker images)

How could you accurately disambiguate if two pipelines in different repository locations are the same? 

I know that adding the repo + location to the URL would remove the actual need to since the're no ambiguity and the state of the selector doesn't matter anymore,  but I'm curious if we could actually match them up. I don't think we could just use the snapshot ids. If we could, it would still be helpful to have a hint such as "This pipeline also exists in these other repository locations: X, Y, Z"

**Comment by hellendag** [comment]
URL changes have landed, closing.
