### ISSUE TITLE
Resolve performance problems on initial load of the Asset Manager

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2978]
Some of our users are seeing very bad performance when loading the asset manager homepage.  

This is possibly because this ends up doing a table scan in `get_all_asset_keys` of the `AssetAwareSqlEventLogStorage`. We may need to paginate this.

**Comment by schrockn** [comment]
cc: @dwallace0723 this is the issue you are seeing

**Comment by sryza** [comment]
We're currently scanning every single asset _materialization_ when we want to fetch the list of asset keys, and there could be many materializations per key.  Pagination would reduce the memory burden, but it still seems potentially prohibitive to scan every event since the beginning of time.

We might be able to address this by taking advantage of the index we already have on asset keys.  E.g. querying with a `select distinct" - https://dba.stackexchange.com/questions/93158/how-to-speed-up-select-distinct.

**Comment by schrockn** [comment]
sandy it does a select distinct

```
query = db.select ( http://db.select/ ) ([SqlEventLogStorageTable.c.asset_key]).distinct()
```

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by alangenfeld** [comment]
> We should not query all asset keys when loading asset root.

I think its more likely the problem is not the initial fetch of all keys but what we are fetching per asset-key. Currently that is the last materialization for its timestamp. Paginating the set of asset keys is one solution, but changing what we fetch per key is also a possible solution.

**Comment by schrockn** [comment]
Rewording issue to describe user-facing behavior rather than projected fix.

**Comment by sryza** [comment]
It does a distinct to get the asset keys, but then it does a `select ... order by timestamp limit 1` to get the timestamps.  Because there's no index on timestamp, that requires scanning and sorting every materialization.

**Comment by sryza** [comment]
@prha is this work still ongoing?
