### ISSUE TITLE
[k8s] figure out solution for deploying flower

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#3052]
Celery 5 is not currently supported by Flower

https://github.com/mher/flower/issues/1029

**Comment by alangenfeld** [comment]
One solution seems to be using a fixed flower image, such as `mher/flower:0.9.5` in our deployment instead of the `template "dagster.celery_image"`

**Comment by chenbobby** [comment]
Resolved by [this diff #5394](https://dagster.phacility.com/D5394)

Due to Flower being incompatible with Celery 5.0, deploying dagster with our public helm chart would create a broken Flower pod.

This change uses "mher/flower:0.9.5" as the default image for the Flower pod. Previously, the "dagster/k8s-celery-worker" was used.
