### ISSUE TITLE
indicate which solid or step generated historical AssetMaterializations

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3091]
We display this for the last materialization, but not for historical materializations

**Comment by hellendag** [comment]
Hey @sryza, can you provide more details about what you have in mind here? Would this be in the "Details" column of the latest materialization event on an asset page? Or elsewhere in Dagit?

**Comment by sryza** [comment]
Yeah - I was thinking the asset page.  I think the details column is really for metadata entries given by the user.  I think what I would probably do is rename Run to "Run Step" or something, have the text under there include the step name, and have the link take you to the page for that run with a filter on events for the relevant step.

**Comment by catherinewu** [comment]
This came up in the emerald meeting again. Their ask was to keep the pipeline run status but also add the solid status since there are often cases where the pipeline run fails and the solid succeeds. Even after the pipeline run is retried from failure, the latest Asset will still look "failed" since the step that produced it previously succeeded and thus isn't retried (so a new Asset isn't generated)

**Comment by bengotow** [comment]
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/1037212/156255466-583198ed-8568-4189-8466-3cb8edbef95e.png">

I think this is largely addressed by 0.14.0 now - we show the step that generated each materialization.
