### ISSUE TITLE
Env vars in user code deployment pods should be available in run coordinator + step jobs

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3102]
current workaround: 
The env vars set under the deployments section of the helm chart are currently only available to the user code deployment pod via this configmap `{{ template "dagster.fullname" $ }}-{{ $deployment.name }}-user-env`. For now, this config map can be passed to the run launcher pod via the executor config's env_config_maps field

**Comment by pietercusters** [comment]
In our use case we want to set different values for certain env vars depending on the repo it is launched from. In the proposed workaround the values for the env vars are the exact same for every job in every repo that is launched by one of the run launcher pods.

Our current workaround is to set the env vars directly in the Docker container, but that is very inconvenient since we have to rebuild the container for every TAP environment we deploy to (the env vars might differ per environment as well).

Do you consider picking up this issue?

**Comment by gibsondan** [comment]
This will be possible in 0.14.10 later this week and the default behavior starting in 0.15.0 - there's an `includeConfigInLaunchedRuns` param that can be set on the user code deployment that will cause the env vars to be passed through automatically to the launched run pods.
