### ISSUE TITLE
Charting issues with longitudinal asset views

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3154]
![Screen Shot 2020-10-27 at 9 57 10 AM](https://user-images.githubusercontent.com/427016/97368354-f7061080-1867-11eb-8ad6-b9cba0d333ae.png)

This view could use some attention. Specifically, there is no legend, the choice between "Execution Time" and "By Partition" is confusing (especially when "By Partition" is greyed out), with no tooltips to help, "values" and "Value" are strange. There are going to be all kinds of multi-axis issues when we have values that have different scales. I think "Execution time" is a difficult name also, in this example one of the values being recorded is also "Execution time".

**Comment by catherinewu** [comment]
Wanted to add that the smoothed "line" in the chart can be misleading since the "line" between adjacent points can be more "extreme" than the points themselves. More formally: for temporally adjacent data points A_x, A_y and B_x, B_y, I would expect all points P_x, P_y on the "line" connecting A and B to satisfy P_x /in [A_x, B_x] and P_y /in [A_y, B_y]. This condition isn't satisfied above(for example: all lines between 9:35am-9:37am, pink line between 9:09am and 9:12am, etc). 

Prezi has previous reported that this was confusing since some expectation graph "lines" would be higher than their total number of expectations and sometimes the "lines" would go below zero

**Comment by mgasner** [comment]
Yes, i agree, the interpolation is often distracting

**Comment by bengotow** [comment]
Hey folks! I will remove the interpolation today - I think the other confusion here (`values` / `value` being vague, etc) has been largely addressed in the new design. Thanks!

**Comment by bengotow** [comment]
Interpolation removed by https://dagster.phacility.com/D5298
