### ISSUE TITLE
Failure percentage math seems wrong

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#3233]
![image](https://user-images.githubusercontent.com/609349/99343388-9d7b7b00-2842-11eb-9415-8bc7b73ecfdc.png)

I only have one green partition & run for the `jobs` solid, and many failed runs—some of the red partitions were retried several times, so not sure where the 27% is coming from

**Comment by bengotow** [comment]
Hey! I revisited how this works this AM and the 27% is because there are 8 partitions with failures out of the 30 displayed (8/30=0.266) I think it'd be much more correct (especially when filtering to a backfill) to say 8/9 failed given that there were no runs for the other partitions, so I'll change this to use "partitions with at least one run" as the denominator!

**Comment by bengotow** [comment]
Addressed in https://dagster.phacility.com/D5346
