### ISSUE TITLE
Backfill Management Tooling/UI

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3246]
## Use Case
Chatted with a team that regularly runs backfills with 100+ runs. 

They currently filter by backfill id on the runs page, but would love a way to get summary information (without clicking through multiple pages of runs to manually summarize) and to apply actions on runs within a backfill. Specific use cases include:
- ability to "force" cancel an entire backfill (and have a cancel state that is distinct from the terminate state)
- monitor what % of runs are in finished state (ie progress bar?), monitor % of runs in running / queued / failed / etc
- ability to re-execute all failed runs within a backfill id.

## Ideas of Implementation
This sounds like the beginnings of a backfill management ui?

**Comment by natekupp** [comment]
cc @hellendag this might be a more fleshed out example of what we were discussing earlier today

**Comment by sryza** [comment]
I believe our existing backfill UI already has the ability to re-execute all the runs in a backfills from failure.  The other two definitely seems useful.  I'm going to file separate issues for them so we can track them on our own.

In terms of adding a "backfill management UI", our partition UI + a backfill filter aims to serve this function, as a backfill in Dagster is essentially a set of runs with the same tag.  I suspect that we'd be able to fit the cancelling into the existing partition UI by adding a button to cancel all runs that match the current filter.

The progress one is a little trickier, because currently Dagster models a backfill as a handful of runs.

**Comment by catherinewu** [comment]
re "I believe our existing backfill UI already has the ability to re-execute all the runs in a backfills from failure." --> I think currently users would have to somehow reconstruct which partitions were selected in the last backfill and enter it manually; would be nice to accept a backfill id/tag instead

**Comment by schrockn** [comment]
Re: these features, we were discussing this in the run scheduling meeting. We could actually build a more generic "bounded run set" UI component that implements all of those features (% complete, mass cancellation, etc) that operates over any set of runs. Since a backfill set of runs, this UI component could be embedded relatively easily.

This component combined with the ability to see the list of backfills (just a list of IDs) applied to a given partition would be a great start

**Comment by catherinewu** [comment]
sandy split these two points into: https://github.com/dagster-io/dagster/issues/3259 https://github.com/dagster-io/dagster/issues/3260
