### ISSUE TITLE
[dagster_airflow] run (containerized) dagster pipeline as a airflow task

### ISSUE THREAD

**Issue by amarrella** [dagster-io/dagster#3247]
## Use Case

Hi, currently dagster_airflow seems to only support converting dagster pipelines into tasks, but currently dagster pipelines can only be compiled to airflow dags.

Due to the airflow problems with SubDAGs (deadlocks), it would be much easier to integrate a dagster pipeline into airflow dags if it was possible to compile it to a task. This would also facilitate progressive migration where we start using dagster for part of the pipeline, and then we progressively add more task to it and remove them from the original airflow dag.

## Ideas of Implementation

Similarly to the current `make_airflow_dag` and `make_airflow_dag_containerized` it would be nice to have a `make_airflow_task` and `make_airflow_task_containerized` which in turn create a PythonOperator and a KubernetesPodOperator.

## Additional Info

While we would lose the granularity and control from Airflow by using this function, this would make it easier to integrate dagster pipelines with hybrid airflow dags.

**Comment by catherinewu** [comment]
hey @amarrella! Thanks for sharing this interesting use case. To clarify my understanding, are you thinking of individually wrapping dagster solids in `make_airflow_task_containerized` so that the pipeline can be migrated one task at a time instead of the entire pipeline at once?

Agreed about SubDAGs. We find that users tend to compile an entire pipeline and then put sensors between the dagster pipeline and airflow dag when needed (although airflow sensors are tricky too). We're launching dagster sensors in 0.10.0 so that could be interesting to use.

We haven't planned more work on this integration. Would love to see if you could try the following, which may work for you:
```
def make_airflow_task(
    solid,
    module_name,
    pipeline_name,
    run_config=None,
    mode=None,
    instance=None,
    dag_id=None,
    dag_description=None,
    dag_kwargs=None,
    op_kwargs=None):

    recon_repo = ReconstructableRepository.for_module(module_name, pipeline_name)
    instance = (
        check.inst_param(instance, "instance", DagsterInstance)
        if instance
        else DagsterInstance.get(fallback_storage=seven.get_system_temp_directory())
    )
    pipeline = recon_repo.get_definition().get_pipeline(pipeline_name)
    execution_plan = create_execution_plan(pipeline, run_config, mode=mode)

    operator_parameters = DagsterOperatorParameters(
        recon_repo=recon_repo,
        pipeline_name=pipeline_name,
        run_config=run_config,
        mode=mode,
        task_id=solid.name, # might need to tinker here
        step_keys=[solid.name + ".compute"], # might need to tinker here
        dag=dag,
        instance_ref=instance.get_ref(),
        op_kwargs=op_kwargs,
        pipeline_snapshot=pipeline.get_pipeline_snapshot(), # this is probably fine to leave out
        execution_plan_snapshot=snapshot_from_execution_plan(
            execution_plan, pipeline_snapshot_id=pipeline.get_pipeline_snapshot_id()
        ), # this is probably fine to leave out
    )
    task = operator(operator_parameters)

    return task

```
where `operator` is either DagsterPythonOperator or DagsterDockerOperator

I haven't actually run the above code. Would love to hear if something like ^ would work for you. Happy to iterate on any errors you encounter and if it's useful to you, add it back into the dagster-airflow integration

**Comment by catherinewu** [comment]
I'll also mention that `make_airflow_dag` returns `(airflow.models.DAG, List[airflow.models.BaseOperator])` so you should be able to retrieve the airflow task directly from this result

**Comment by amarrella** [comment]
Hi @catherinewu thanks for your reply! I'll try that out, also I didn't notice that `make_airflow_dag` returns a list of tasks, that might be enough for what i'm trying to achieve, so thanks for highlighing it.

The "sensors" is very good news to me, as maybe I can completely decouple the airflow and the dagster codebases and the above wouldn't be necessary anymore. Could you share more about them? Is a Google PubSub sensor in the works by any chance?

Thanks again for your help and for the incredible work you and the team are doing with Dagster!

**Comment by catherinewu** [comment]
Hey @amarrella, cool I'll mark this issue as closed for now. Feel free to re-open if you run into any issues!

Here is our 11/08/2020 community update on sensors: https://youtu.be/6nKCd2TaXik?t=2432. I don't think we have plans to create a library of sensor integrations, but will definitely note the interest in google pubsub.

Thank you!

**Comment by sryza** [comment]
Looks like this was meant to be closed, but didn't actually end up closed.  Closing now.
