### ISSUE TITLE
Celery-less K8s deployment that offers step-level isolation

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3287]
## Use Case
Investigate whether this might be a reasonable deployment option?

Currently, the two K8s options are to either (1) Execute entire pipeline run within one pod (limits parallelism + resource use, no step-level isolation) or (2) Execute each step in its own pod, but this requires enqueueing step in Celery queue.

**Comment by alangenfeld** [comment]
Yea this is worth doing and it should be pretty easy to build a `K8sJobExecutor`

**Comment by ikendoit** [comment]
Hello, I just wanted to say this feature can be very helpful to my work.

My use case is that we have a pipeline, 
- First solid is very heavy and require lots of CPU/Memory, 
- Second solid is just polling data, so it requires little resources. 
- Third solid is triggered once second solid finishes polling. This one also requires lots of resources for computation. 

I understand that we currently can use Celery-k8s-run-launcher for this use case, where we can have 2 queues like "low_resource" and "high_resource", 
But I am not too eager to use Celery and RabbitMQ, because:
- Celery requires a static set of workers always running, which can be expensive given that we have multiple clusters for developments. 
- Celery doesn't make horizontal auto scaling easy. My pipelines may have 0 jobs for 6 days, and 100s of jobs for 1 day. 
- Extra dependencies to care for ( Celery, RabbitMQ/Redis and Flower ) 

So having this `K8sJobExecutor` can greatly save us cost and complexity/maintenance on the Kubernetes Cluster.

**Comment by zblz** [comment]
An additional feature that would make dagster a very valuable k8s orchestration tool would be the ability to select per-solid images. As @ikendoit mentioned different solids might need very different resources, but also might need very different software. Bundling the dependencies for all tasks into a single Python environment might result in dependency incompatibilities and very large images (I'm not sure whether it would be feasible to run a solid in a different Python env, but it introduces complexity). 
In addition, it would allow to use upstream images for hard to install software. In one of our pipelines, we use OpenSFM to build a 3D model out of images processed in a previous solid, and because it uses several non-Python libraries it would be extremely useful if we could use public docker images to run that solid.

**Comment by johannkm** [comment]
This is available in the recent 0.11.10 as an experimental executor. It is not recommended for production use, but feel free to test it out!

```python
from dagster_k8s.executor import dagster_k8s_executor

@pipeline(
        mode_defs=[
            ModeDefinition(
                executor_defs=[dagster_k8s_executor]
            )
        ]
    )
...
```

**Comment by johannkm** [comment]
Dagster now offers the `k8s_job_executor`, which executes solids in separate kubernetes jobs. This addition means that you can now choose at runtime between single pod and multi-pod isolation for solids in your run.

Previously this was only configurable for the entire deployment- you could either use the K8sRunLauncher with the default executors (inprocess and multiprocess) for low isolation, or you could use the CeleryK8sRunLauncher with the celery_k8s_job_executor for pod-level isolation. Now, your instance can be configured with the K8sRunLauncher and you can choose between the default executors or the k8s_job_executor.

Looking forwards to getting your feedback on this!

Api docs: https://docs.dagster.io/master/_apidocs/libraries/dagster-k8s#dagster_k8s.k8s_job_executor
Choosing an executor for your k8s deployment: https://docs.dagster.io/master/deployment/guides/kubernetes/deploying-with-helm#executor

**Comment by johannkm** [comment]
cc @rdeepk @JeffThorslund @harvhundal @Jsturgeo since you had expressed interest in this

**Comment by nicklofaso** [comment]
Thanks for adding this great feature!

@johannkm Is there plans to support different images per solid as @zblz [mentioned](https://github.com/dagster-io/dagster/issues/3287#issuecomment-762848070) above?

That would be of tremendous use to us. We have various teams working on different steps on a single computationally intensive physics workflow. Each step has different languages/dependencies (e.g. python, R, Fortran, C++, etc.), and trying to combine all of that into a single container image would be very difficult.

**Comment by johannkm** [comment]
Hi @nicklofaso (and cc @zblz )- I described some possible approaches in a separate issue [here](https://github.com/dagster-io/dagster/issues/4277). Would love to get your thoughts.
