### ISSUE TITLE
Add the ability to delete or hide an asset key from the asset catalog

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3356]
## Use Case

The asset catalog indexes streams of immutable events which has some nice properties. Having a tidy catalog is not one of those properties. It is very easy to create errant keys and then hard to delete them, especially in prod. I think we should have a facility in the UI to do this.

**Comment by schrockn** [comment]
This is another thing to consider in the asset catalog. Not super hi-pri but definitely nice-to-have.

**Comment by sryza** [comment]
@prha @bengotow does this seem doable in the 0.11.0 timeframe?  I think the asset catalog becomes an order of magnitude  more valuable if users can trust that it contains a curated set of assets.  I have personally found our dogfood asset catalogs difficult to navigate because of all the old abandoned assets floating around.

**Comment by prha** [comment]
yeah, I have this in a branch... will put up in a diff in the next day or two.

**Comment by sryza** [comment]
Awesome!

**Comment by hellendag** [comment]
@prha what's the status of this?

**Comment by prha** [comment]
this is done
