### ISSUE TITLE
[helm] test coverage should cover ingress.yaml errors

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3370]
## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by chenbobby** [comment]
Prompted by a whitespacing issue in [line 34 of `helm/dagster/templates/ingress.yaml`](https://github.com/dagster-io/dagster/blob/70fe24ff0d5abe234e59f34b409010abd521b6a9/helm/dagster/templates/ingress.yaml#L34).

#### Description
An "if" directive in the Helm template ingress.yaml used `-}} `instead of `}}`.

Using `-}}` will remove all whitespace that immediately follows the "if" directive.

If .Values.flower.enabled, then the generated YAML for the Ingress resource will be malformed.

#### Solution Tracking
[A WIP diff (#5484) for this can be found here.](https://dagster.phacility.com/D5484)

**Comment by chenbobby** [comment]
Resolved by [this diff D5603](https://dagster.phacility.com/D5603)
