### ISSUE TITLE
[Helm] Flower, Dagit, and Daemon require startupProbe which is only supported by K8s 1.16+

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3406]
## Summary

Flower requires startupProbe, which is not compat with Kubernetes <1.16

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by natekupp** [comment]
We actually have `startupProbe` specified for `flower`, `dagsterDaemon`, and `dagit`. 

Note that the comments in the helm chart for these:

```
  # Startup probe (available in kubernetes v1.16+) is used at pod startup. Once it has succeeded,
  # then liveness probe takes over.
  # If on kubernetes < v1.16, then comment out `startupProbe` lines and comment in
  # `initialDelaySeconds: 60` under `livenessProbe`
```

won't work, because Helm will always use the defaults in the chart-provided values.yaml where `startupProbe` is uncommented.

We can comment out `startupProbe` in the chart values.yaml, but then a k8s 1.16+ user will need to explicitly specify all three startup probes which is kind of a bummer.

@catherinewu thoughts?
