### ISSUE TITLE
Default k8s resource requests/limits

### ISSUE THREAD

**Issue by mrdavidlaing** [dagster-io/dagster#3483]
## Use Case
When installing Dagster - via the [Dagster Helm chart](https://github.com/dagster-io/dagster/tree/master/helm) -  on a resource constrained (or autoscaling) K8s cluster, having resource requests/limits set for all k8s containers is useful to:

(a) prevent accidental overcommit / OOM errors and 
(b) trigger (GKE) autoscaling rules. 

## Ideas of Implementation
1. A default install (via the Helm chart; with no additional user config) should configure all k8s containers to have sane minimum resource limits - eg:

    ```yaml
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 200m
          memory: 256Mi
    ```

      This should include all containers created by the initial install and those created via Pipeline Runs

1. It should be possible to override these defaults on a case by case basis via any of the existing mechanisms (eg; extra Helm values config or `tags = {   'dagster-k8s/config': {}}` on any of the `@solid`s

## Additional Info
* This handy bit of `kubectl` shows all the configured resource requests/limits for all pods in the `dagster` namespace
    ```
    kubectl --namespace dagster get pods \
    -o custom-columns=NAME:.metadata.name,IMAGE:.spec.containers[0].image,STATUS:.status.phase,\
    'CPU(request)':{.spec.containers[*].resources.requests.cpu},'CPU(limit)':{.spec.containers[*].resources.limits.cpu},\
    'MEMORY(request)':{.spec.containers[*].resources.requests.memory},'MEMORY(limit)':{.spec.containers[*].resources.limits.memory}
    ```
* It may be possible to configure defaults by adding a [LimitRange object to the namespace](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/) - I'd be happy to submit a PR with a ["works on my GKE cluster" implementation](https://github.com/mrdavidlaing/software-releases-dwh/blob/main/dagster_instances/gcp_eu-west1/helm_values.yaml) if this seems like a sane approach

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by natekupp** [comment]
when testing this change, we should also test to confirm that we gracefully handle when we hit CPU/memory resource limits

**Comment by mrdavidlaing** [comment]
@natekupp With no container limits set (and running on a memory constrained K8s node) I experienced some extremely weird behaviour - including the k8s services on the node dying and the node dropping out of the K8s cluster.

When setting the container memory limits too low (eg 128MB) I observed some pods (especially the celery ones) fail to start (due to OOM errors).

I struggled to find relevant error messages; so perhaps there is opportunity for improvements there (at the very least w.r.t extra documentation with guidance on how to detect hitting CPU/memory resource limits.

**Comment by natekupp** [comment]
Great, thanks for the context and for the bug report! @chenbobby is looking at this and we're aiming to have resource limits in place at least for the initial install w/ our release this week; we need to discuss a bit more about how to do this cleanly for pipeline run pods

**Comment by mrdavidlaing** [comment]
Thanks!  Let me know if I can help in any way

**Comment by chenbobby** [comment]
Exposing a LimitRange object to the Helm chart would be a useful feature, but I would argue against setting default values for resource constraints (Ideas for Implementation 1) in either `helm/dagster/values.yaml` or one of the templates YAML. This is because such constraints can vary across different deployments.

I did a bit of research on other public Helm charts, and in general, resource constraints are exposed in the helm chart’s `values.yaml`, but only explicitly set by users (by modifying values.yaml, for example). This practice is shared by [many](https://github.com/helm/charts/blob/2f030a8e9db3e451e8030b12d2658371f5708f7d/stable/zetcd/values.yaml#L15-L25) [other](https://github.com/helm/charts/blob/2f030a8e9db3e451e8030b12d2658371f5708f7d/incubator/spark/values.yaml#L52-L62) [public](https://github.com/helm/charts/blob/2f030a8e9db3e451e8030b12d2658371f5708f7d/stable/mariadb/values.yaml#L293) [Helm](https://github.com/helm/charts/blob/2f030a8e9db3e451e8030b12d2658371f5708f7d/incubator/docker-registry/values.yaml#L52-L62) [charts](https://github.com/helm/charts/blob/2f030a8e9db3e451e8030b12d2658371f5708f7d/stable/logstash/values.yaml#L80-L90) 🧐 

If the default Dagster helm chart is setting resources _limits_ and causing Out-Of-Memory problems, then I think this is a bug. 

As for error messages, I think you are right that Dagster/Dagit doesn't expose alerts when celery workers are down. Currently, monitoring the resource usage by celery worker pods would need to come from the [k8s dashboard](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/), some other [monitoring service like Prometheus](https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/), or the classic `kubectl get pods` 😓 

@mrdavidlaing, please let me know your thoughts. also, feel free to add me as a reviewer if you decide to make a PR for the LimitRange object (or any other improvements for that matter) 😃 👍 

---

Regarding [Ideas for Implementation 2], you currently can use pipeline tags and solid tags to specify resource constraints. For example, on a pipeline:
```python
@pipeline(
    ...,
    tags={
        "dagster-k8s/config": {
            "container_config": {
                "resources": {
                    "requests": {
                        "cpu": "1",
                        "memory": "1Gi"
                    },
                    "limits": {
                        "cpu": "2",
                        "memory": "2Gi"
                    },
                },
                "ports": [
                    {
                        "name": "grpc",
                        "containerPort": 3030,
                        "protocol": "TCP"
                    },
                    {
                        "name": "anotherport",
                        "containerPort": 4040,
                        "protocol": "TCP",
                    },
                ],
            }
        },
    },
)
def example_pipe():
	pass
```
You should be able to the above method in a `@solid` decorator, too. Moreover, these should override any resource constraints that are explicitly defined in your own `values.yaml`. We have a task on the backlog to improve documentation on this method of overriding k8s config, and this issue will def push it up the priority queue 😅

**Comment by mrdavidlaing** [comment]
@chenbobby Thanks for the thoughts - I'll take a stab at a PR; but might only get to it this weekend.

**Comment by mrdavidlaing** [comment]
@chenbobby Given the changes above; I think we should close this issue.

WDYT?
