### ISSUE TITLE
Example of deploying Dagit + Daemon in a single Docker container

### ISSUE THREAD

**Issue by chenbobby** [dagster-io/dagster#3571]
## Use Case
If a user would prefer not to use docker-compose or would prefer to simply have a single Docker container to deploy, it would be nice to have an example of deploying Dagit + Daemon from a single container image.

This example is primarily motivated by simplicity. For advanced use cases, users should bias towards separating the Dagit and Daemon process into multiple containers.

## Ideas of Implementation
From [Docker documentation](https://docs.docker.com/config/containers/multi-service_container/), one way to implement multiple services in a single container is to use a wrapper Bash script to kick-off the Daemon process in the background and then run the Dagit process.

## Additional Info
Prompted by [this Slack thread](https://dagster.slack.com/archives/CCCR6P2UR/p1610795625048100) in #general

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by johannkm** [comment]
I think it would make sense to link to the docker docs https://docs.docker.com/config/containers/multi-service_container/, but I would hesitate to put an explicit example because I don't think we really endorse this approach. An alternative that we've also considered would be to add a flag on the Dagit CLI to ask it to spin up the daemon as a child. This would potentially make deployment simpler both on a bare host and inside a container. @gibsondan thoughts?

**Comment by yuhan** [comment]
@johannkm (cc @gibsondan) do we have a decision about this content piece? i.e. a single-container example in the docker guide VS code changes + a short explanation

**Comment by yuhan** [comment]
Closing as this isn't an approach we would highly recommend. Can open/revisit if we ever go down this route
