### ISSUE TITLE
QueuedRunCoordinator Docker APIError

### ISSUE THREAD

**Issue by kstadler** [dagster-io/dagster#3589]
## Summary
I've tried to migrate the docker compose example to my own example project.
After some work I finally got all the services running, but when I actually launch a run in dagit I get the following error in the daemon process:

```
2021-01-23 19:10:55 - QueuedRunCoordinatorDaemon - INFO - Retrieved 1 queued runs, checking limits.
2021-01-23 19:10:55 - dagster-daemon - ERROR - Caught error in DaemonType.QUEUED_RUN_COORDINATOR:
SerializableErrorInfo(message='docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/create: Bad Request ("invalid reference format")\n', stack=['  File "/usr/local/lib/python3.7/site-packages/dagster/daemon/controller.py", line 97, in run_iteration\n    next(generator)\n', '  File "/usr/local/lib/python3.7/site-packages/dagster/daemon/run_coordinator/queued_run_coordinator_daemon.py", line 172, in run_iteration\n    self._dequeue_run(run, location_manager)\n', '  File "/usr/local/lib/python3.7/site-packages/dagster/daemon/run_coordinator/queued_run_coordinator_daemon.py", line 234, in _dequeue_run\n    self._instance.launch_run(run.run_id, external_pipeline)\n', '  File "/usr/local/lib/python3.7/site-packages/dagster/core/instance/__init__.py", line 1223, in launch_run\n    self._run_launcher.launch_run(self, run, external_pipeline=external_pipeline)\n', '  File "/usr/local/lib/python3.7/site-packages/dagster_docker/docker_run_launcher.py", line 128, in launch_run\n    network=self._network,\n', '  File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 870, in create\n    resp = self.client.api.create_container(**create_kwargs)\n', '  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 430, in create_container\n    return self.create_container_from_config(config, name)\n', '  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 441, in create_container_from_config\n    return self._result(res, True)\n', '  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 274, in _result\n    self._raise_for_status(response)\n', '  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status\n    raise create_api_error_from_http_exception(e)\n', '  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception\n    raise cls(e, response=response, explanation=explanation)\n'], cls_name='APIError', cause=None)
2021-01-23 19:11:00 - QueuedRunCoordinatorDaemon - INFO - Poll returned no queued runs.
2021-01-23 19:11:00 - QueuedRunCoordinatorDaemon - INFO - Launched 0 runs.
```

## Reproduction
clone repo at https://github.com/kstadler/dagster-exchangerates and run docker compose in docker subdirectory.

## Dagit UI/UX Issue Screenshots
![image](https://user-images.githubusercontent.com/2895122/105611869-47820100-5db8-11eb-95fc-e3b36884756f.png)

## Additional Info about Your Environment
I've moved my dagster definitions to a module in the same project.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Will take a look (Monday at the latest). One question that will help investigate - does the deploy_docker example in github work for you out of the box (i.e. using the example instance and simple pipeline provided there with no changes, are you able to launch a run from dagit?) That will help understand if the issue is with the example not working in different Docker environments, or if there was a problem migrating from the example to your project.

**Comment by gibsondan** [comment]
OK, I think I see the problem. There's a .env file that's included in the example that isn't in your repo: https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/examples/deploy_docker/.env#L1:1

which is responsible for setting the COMPOSE_PROJECT_NAME variable that docker-compose uses to name any containers that it builds (and which we reference to tell the run launcher the name of the built container that it should launch runs in). Adding that file in should make your runs launch (worked for me locally).

My guess is the error here is because it's trying to launch a container name that Docker can't find - we should be able to throw a better error message in DockerRunLauncher to make this more clear.

**Comment by kstadler** [comment]
Thanks, that has been the cause for the error!
Moving the .env to the same directory as the docker-compose.yml and changing its value solved the problem.
