### ISSUE TITLE
Re-executing a run from a sensor with a run_key set causes the daemon loop for that job to fail

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3594]
## Summary

On https://demo.elementl.show/workspace/elementl_data@elementl-data/sensors/s3_sensor

Running into

<img width="883" alt="Screen Shot 2021-01-24 at 7 23 31 AM" src="https://user-images.githubusercontent.com/28738937/105633340-39160280-5e15-11eb-913b-955da471978b.png">

At minimum we should have a better error message but this seems like a deeper error.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Do you have a link to the specific run / remember roughly what time it was? I see lots of failed runs for that sensor but most of them appear to be the config error that has a separate issue filed.

**Comment by gibsondan** [comment]
Oh I see, it's in the tick failure, not a specific run.

**Comment by gibsondan** [comment]
Ah, what happened is that when the 'dagster.png' run was retried (I assume manually), it left us with two runs for that sensor with the 'dagster.png' run key, which the sensor loop is not expecting to be possible. The scheduler probably has a similar issue.

(As a temporary workaround, I deleted the older failed 'dagster.png' run, and the tick loop is now running again.)

The likely fix is to change the scheduler/sensor loop to look at the most recent run with that run key, instead of invarianting that there is exactly one run with that sensor+run key combo.

Side-note: We would probably run into a similar issue if there were two sensors with the same name (and using the same run keys) in different repositories.

**Comment by gibsondan** [comment]
Fix will roll out in 0.10.2
