### ISSUE TITLE
Inconsistent labeling around dagit of "Started" versus "Running" versus "Executing"

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3707]
## Summary

We are a bit all over the place with language.

![Screen Shot 2021-02-18 at 9 24 39 PM](https://user-images.githubusercontent.com/28738937/108457621-38179b80-7230-11eb-9399-2f5969a2befc.png)

Even on this page we using "Running" and "Started". 

IMO started is a bit misleading because in a state transition diagram "started" would become before "running" as a state.

In fact in the runs viewer typeahead there is no running or started status.

![Screen Shot 2021-02-18 at 9 27 40 PM](https://user-images.githubusercontent.com/28738937/108457744-6bf2c100-7230-11eb-8355-f263cbc96264.png)

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
`STARTED` is available in that filter, we just currently limit the filtered options list for `status:` and this one falls off the end of the alphabetical list. (Not great.) We should change this to show all of the available options.

- It may make sense for the tags to match the Python enum, as we did with the log filter. This seems like it would be okay, and would be more consistent.
- The `STARTED` status seems like it would more appropriately be `RUNNING` or `EXECUTING`, since "Started" makes it sound like the run is just barely underway. There may be others that could benefit from clarification too.

**Comment by hellendag** [comment]
Landed the change to make it match the Python enum in Dagit. Passing to Core for discuss or triage `STARTED` vs. `RUNNING`/`EXECUTING`.

**Comment by sryza** [comment]
Closing this because the main issue was addressed.  Filing a couple issues:
* Consider renaming "Started" to "Running" - https://github.com/dagster-io/dagster/issues/4016
* runs viewer typeahead has no STARTED status - https://github.com/dagster-io/dagster/issues/4017
