### ISSUE TITLE
Every other tick disappearing in sensor timeline view

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3713]
## Summary

This is firing every 30 seconds, but historically they only seem to be rendered once-per-minute. However future ticks are registered correctly.

![Screen Shot 2021-02-19 at 8 09 18 AM](https://user-images.githubusercontent.com/28738937/108522242-dc79fc00-7289-11eb-9796-2ad11afcb81c.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by prha** [comment]
@schrockn is this local or on prod?  Just checking to see if the daemon is configured differently...

**Comment by schrockn** [comment]
saw on go/prod

**Comment by prha** [comment]
This has to do with the way we implemented minimum interval seconds, along with the default daemon interval....

The daemon runs every 30 seconds and we're now enforcing a minimum sensor interval at the individual sensor level, so that users can customize the interval.  Thinking about the right solution...

**Comment by prha** [comment]
Fixed by http://dagster.phacility.com/D6646
