### ISSUE TITLE
Surface current version of schema migration in Dagit

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#3752]
## Use Case
I want to know whether I should run `dagster instance migrate` within Dagit. I can make this decision if I know the current version of my schema, how many revisions behind I am, and also a short summary of each revision.

## Ideas of Implementation
Surface information in `/instance` details page.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hey @rexledesma! I'm not sure that this is a valid state? If you have migrations to apply, you really shouldn't launch dagit until they're run since the GraphQL resolvers could fail in random + unexpected ways? I'd expect Dagit to exit at launch with a "Please run migrations before launching Dagit" message?

**Comment by bengotow** [comment]
Per discussion with Rex we'll try to do this as a dagit CLI warning instead of a big banner in Dagit. It sounds like this could be a bit annoying for folks that subscribe to our patch releases, but forcing them to run the command after deploying would be better than a banner + misc instability in dagit.
