### ISSUE TITLE
square in step-partition matrix is green even when latest run failed

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#3792]
## Summary

Squares in the step-partition matrix should reflect the state of the latest run, but sometimes seem to reflect earlier states.

![image](https://user-images.githubusercontent.com/654855/110156760-36a3b280-7d9c-11eb-8e3f-3791fd32bcf3.png)

![image](https://user-images.githubusercontent.com/654855/110156802-402d1a80-7d9c-11eb-9afc-a2f8e07dc434.png)

## Reproduction

* Go to the partitions page for the longitudinal pipeline in the toy repo
* Run a backfill over like 10 partitions (steps will fail randomly)
* Run another backfill over the same partitions (steps will fail randomly)
* By clicking into squares, observe that some of the squares have a failed run after a successful run, but still appear green

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment]
Hey @sryza hmm I can fix this ASAP. I know this was intentional though - we consider success the "final" square state and ignore whatever happens after that. The goal was to make the squares reflect the overall success / failure of the partition so the green squares accumulate from all the runs and re-runs on that day. 

One related note: if you run A, B, C and C fails, and re-run C and it succeeds, we still show the successes in A + B even though they were not executed as part of the last run to fix C.  Technically, if we just show the latest run over top of the previous runs, they should go back to being gray?

Alternatively we could adopt the half red/ half green square design (which currently means "1+ failures and then success") and have a version for "success and then failures", but I believe we hide that functionality behind a display option now...

**Comment by sryza** [comment]
Ah, didn't realize this is intentional.

Here's how I'm thinking about it:  Ultimately, when someone is scanning the step-partition matrix, what they're ultimately trying to figure out is "what step-partitions need to be backfilled?"  Green means all good.  Red or gray means "needs to be backfilled."  If the most recent run for a step-partition failed, that almost always means it needs to be backfilled.

> Technically, if we just show the latest run over top of the previous runs, they should go back to being gray?

Here's how I'm imagining we'd explain the meaning of the color of a square: "The color of a step-partition square reflects the outcome of the most recent execution of that step for that partition.  If there have never been executions for that step for that partition, the square is colored gray."  My guess is that this is what users would expect (it would definitely match what they see in similar UIs from other orchestrators).  This would mean that A and B would remain green after re-executing C.

Thoughts?

**Comment by bengotow** [comment]
Ok I like that meaning! It's definitely a bit simpler to explain than our current "did this step succeed in any run of this partition". Will change this and we can play around with it 👍

**Comment by bengotow** [comment]
This should be resolved by https://dagster.phacility.com/D7377
