### ISSUE TITLE
Unhelpful error message when missing intermediate_storage config for multiprocessing

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3988]
Steps to reproduce:

1. `dagit -f examples/docs_snippets/docs_snippets/concepts/solids_pipelines/dynamic_pipeline/dynamic_pipeline.py`

2. Execute pipeline with config:
```
execution:
  multiprocess:
```

Error reads:

```dagster.core.errors.DagsterUnmetExecutorRequirementsError: You have attempted to use an executor that uses multiple processes, but your pipeline includes solid outputs that will not be stored somewhere where other processes canretrieve them. Please make sure that your pipeline definition includes a ModeDefinition whose resource_keys assign the "io_manager" key to an IOManager resource that stores outputs outside of the process, such as the fs_io_manager.```

This implies it is necessary to change the pipeline definition, but the actual resolution is to execute with the following config:

```
execution:
  multiprocess:
intermediate_storage:
  filesystem:
```

**Comment by sryza** [comment]
Intermediate storage is deprecated, so the config-based solution is no longer recommended.

Here's a diff to fix the missing space in the error message: https://dagster.phacility.com/D7269.

**Comment by schrockn** [comment]
This is still a bit of a usability issue. When initially experimenting with the platform and you don't understand I/O managers and you want to understand retries etc. In order to get those to work you need to set the io_manager to a filesystem one. This in turn requires you to understand resources, modes, i/o managers to exercise a basic capability. At least with intermediate_storage you can just do a config-driven thing out of the box.

My recommendation would be to make the default i/o manager executor dependent, OR to default to filesystem.

**Comment by sryza** [comment]
> This is still a bit of a usability issue.

I think that's fair.

One direction that @dpeng817 and I have been talking about with the local testing APIs would be that `execute_in_process`(or some API) ignores IO managers and just uses in-memory for intermediates.  If we went that direction, then that could make it more sensible for the default IO manager to be filesystem.

**Comment by sryza** [comment]
I'm going to track the usability issue that Nick brought up in a separate list of approachability issues.

I'm going to take a stab at including some code in the error message (in the diff I linked above) to make it more informative and then close this issue when that diff goes in.
