### ISSUE TITLE
Custom IO Manager does not process composite solid's output

### ISSUE THREAD

**Issue by martimpassos** [dagster-io/dagster#4130]
## Summary

The output of a composite solid is processed with the default `io_manager` even if `OutputDefinition` tells otherwise. I had to move the definition to the last solid in the composite for it to work.

## Reproduction

```
@solid
def solid_a(_):
    return 1
@solid
def solid_b(_, x):
    return x
@composite_solid(output_defs=[OutputDefinition(io_manager_key="my_io_manager")])
def my_composite_solid():
    x = solid_a()
    x = solid_b(x)
    # this output will still be processed with the default io_manager
    return x
@pipeline(mode_defs=[ModeDefinition(resource_defs={"my_io_manager": fs_io_manager})])
def my_pipeline():
    my_composite_solid()
```

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by yuhan** [comment]
https://dagster.phacility.com/D8365 should address this:
we recently made changes so we will error on `io_manager_key` that is set on composite solids, but instead respect the io managers set on solids inside a composite.

It means in this case, we will have the "my_io_manager" to be set on the solid_b's output def (as my_composite_solid's output is mapped to solid_b's output)

```python
@solid
def solid_a(_):
    return 1

@solid(output_defs=[OutputDefinition(io_manager_key="my_io_manager")])
def solid_b(_, x):
    return x

@composite_solid
def my_composite_solid():
    x = solid_a()
    x = solid_b(x)
    return x
```

The change will be out in next week's release. Feel free to reopen if this issue is still valid.
