### ISSUE TITLE
[Documentation Feedback] Tutorial test example is broken

### ISSUE THREAD

**Issue by eltbus** [dagster-io/dagster#4192]
Problem on /tutorial/intro-tutorial/single-solid-pipeline#executing-our-first-pipeline page

"hello_cereal" should return cereal.

Otherwise, test tutorial will fail.

**Comment by eltbus** [comment]
```python
import csv
import requests

from dagster import execute_pipeline, execute_solid, pipeline, solid


@solid
def hello_cereal(context):
    response = requests.get("https://docs.dagster.io/assets/cereal.csv")
    lines = response.text.split("\n")
    cereals = [row for row in csv.DictReader(lines)]
    context.log.info(f"Found {len(cereals)} cereals")
    return cereals  # this is missing in the tutorial


@pipeline
def hello_cereal_pipeline():
    hello_cereal()


if __name__ == "__main__":
    result = execute_pipeline(hello_cereal_pipeline)
    assert result.success


# start_hello_cereal_with_tests_marker_0
def test_hello_cereal_solid():
    res = execute_solid(hello_cereal)
    assert res.success
    assert len(res.output_value()) == 77


def test_hello_cereal_pipeline():
    res = execute_pipeline(hello_cereal_pipeline)
    assert res.success
    assert len(res.result_for_solid("hello_cereal").output_value()) == 77
```

**Comment by eltbus** [comment]
![pic-selected-210520-0032-49](https://user-images.githubusercontent.com/33374178/118893612-fcf63880-b902-11eb-9fce-0b6aea1baf0a.png)

**Comment by sryza** [comment]
Thanks for reporting this @eltbus.  Definitely seems like an issue.

I'm hesitant to add a return statement to the initial `hello_cereal` solid, because readers should have a chance to absorb a basic solid before absorbing the fact that they have inputs and outputs.  One approach could be to include a test for one of the other solids in the tutorial that already has an output.  E.g. `find_highest_protein_cereal` on the "Connecting Solids" page.

**Comment by dpeng817** [comment]
This has been solved since https://github.com/dagster-io/dagster/commit/1a38217b7e0014d4ad6eb1240ec8d145682aee51.
