### ISSUE TITLE
Turning on schedules shows them off/on again in Dagit

### ISSUE THREAD

**Issue by joshuataylor** [dagster-io/dagster#4270]
## Summary
When turning on multiple schedules, clicking "On" and going down the list will show the previous entries as off. Sometimes it corrects itself, othertimes it remains off.

## Reproduction
1. Go to /dagit/instance/schedules
2. Turn on some schedules
3. It will show this

It might be because I'm about 260ms away from the server, so there could be latency reasons around the optimistic UI for this?

## Dagit UI/UX Issue Screenshots
https://user-images.githubusercontent.com/225131/121357775-a5c51000-c964-11eb-9a03-601697b4360b.mp4

## Additional Info about Your Environment
Dagster 0.11.12

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
Thanks for the report, taking a look.

**Comment by hellendag** [comment]
It's a strange bug, because the UI isn't optimistic right now -- we don't switch to "on" until the schedule status is updated on the server.

After playing with this a bit, I'm actually going to put up a diff that switches it to a disabled "on" state while it's waiting to start, in an effort to make it a little _more_ optimistic than it currently is. But that won't help avoid the odd behavior of the switch turning back off and on again, which is no doubt a bug.

I'd like to find out if there are any rogue queries or mutations occurring here that are affecting the cached state of the schedules. If you have a moment, would you mind doing the following:

- Turn on "Debug Console Logging" at `/flags` in Dagit
- Go to `/instance/schedules` and repeat the same steps as in the video, with the browser dev tools open
- Copy the log output with the list of queries and mutations

Feel free to message me on Slack if there's anything you prefer not to post on GitHub.

Thanks!

**Comment by hellendag** [comment]
Closing as stale. Please reopen if you're able to repro this reliably!
