### ISSUE TITLE
Trying to use helm to deploy dagster at version 0.11.5 deploys 0.11.14rc3

### ISSUE THREAD

**Issue by blissman** [dagster-io/dagster#4279]
## Summary

Trying to use helm to deploy dagster following the instructions on this page: https://docs.dagster.io/deployment/guides/kubernetes/deploying-with-helm does not work as expected. Passing the desired version (in this case 0.11.5) deploys the latest version. The only version that deploys correctly seems to be 0.11.13.

On investigation, only 0.11.13 is listed in the dagster chart repo here: https://dagster-io.github.io/helm

## Reproduction

`helm upgrade --install --version 0.11.5 dagster-release dagster/dagster -f helm_values.yaml ` deploys 0.11.14rc3
`helm upgrade --install --version 0.11.4 dagster-release dagster/dagster -f helm_values.yaml ` deploys 0.11.14rc3
`helm upgrade --install --version 0.11.13 dagster-release dagster/dagster -f helm_values.yaml ` deploys 0.11.13

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment]
This is intended, as the tags for the Dagster provided images in the Helm chart before 0.11.13 was `latest`, which pulls the most up to date image for those system components (e.g. Dagit, Daemon, Celery workers, etc).

In 0.11.13, this behavior was changed so that the tags for these Dagster provided images now correspond to the Chart version (https://github.com/dagster-io/dagster/commit/6954c79d6f0f49aa76983c18650cfb9c5be27dba), but for charts before 0.11.13, the `latest` behavior still persists.

To get around this, you'll need to specify the tags for the Dagster system components in the values you pass to the chart as the version of the chart you're installing (e.g. `tag: 0.11.5` if you're installing `--version 0.11.5`). But moving forward after 0.11.13, this will not be required.
