### ISSUE TITLE
Dagit: Empty page in case of resource error

### ISSUE THREAD

**Issue by szalai1** [dagster-io/dagster#4309]
## Summary

One particular run, loads with an empty page when I click on it.

## Reproduction

The run failed due to a resource error, I think it's unrelated as I saw that error earlier.

## Dagit UI/UX Issue Screenshots

https://user-images.githubusercontent.com/6796005/123129046-eedc9000-d44b-11eb-8723-cb2b18279ee4.mov

## Additional Info about Your Environment

dagster 0.11.4

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by szalai1** [comment]
Things I observed since reporting this:
* Only one particular pipeline does this ( and only after a change related to modes)
* the pipeline can run successfully, but the run cannot be seen on dagit.

**Comment by hellendag** [comment]
@bengotow I believe we've seen this before, and that it may have been fixed by 4b94c85. (Slack context: https://dagster.slack.com/archives/C01U954MEER/p1620396349458000)

@szalai1 Thanks for the report! Are you able to upgrade to a more recent version? If I'm correct about the bugfix above, the issue would be fixed as of 0.11.9.

**Comment by szalai1** [comment]
thanks, @hellendag, I will upgrade dagster soon and report back.

**Comment by hellendag** [comment]
Gonna close this, please reopen if it's still an issue. :)
