### ISSUE TITLE
Parallel execution of sensors

### ISSUE THREAD

**Issue by Oliver-Sellwood** [dagster-io/dagster#4333]
## Use Case

In applications where low latency is a key requirement the serial execution of sensors can become an issue.

For instance when reading from a Kafka or Kinesis streams it makes sense to use a single sensor for each partition/shard. However when scaling to more partitions/shard the period of sensor executions can get into the minutes as it has to query each sensor in serial. This is a major latency bottleneck.

## Ideas of Implementation

Use multiprocessing or async methods to allow for concurrent execution of sensors.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by b4dboi** [comment]
Hi, I ran some benchmarks where I was focusing on scalability of sensors. My goal was to identify limits when running multiple sensors. I like the idea of sensors, as a lightweight probe, but the overall performance is not satisfactory so far.

There was no load on the daemon other than sensors during the test. The DefaultRunCoordinator was employed and the sensor daemon was configured as follows. I used dagster version 1.1.7.
```
  sensors:
    useThreads: true
    numWorkers: 16
```
The test and evaluation consisted of following steps.
1. Run multiple sensor runs (concurrently 1,10,20,40) under minimum interval (1s) and run key defined as timestamp with a minute resolution (code is below) -> the job run is executed only once per minute, other runs are skipped
2. Collect sensor ticks from job_ticks table (all ticks, even skipped)
3. Count number of ticks per minute and compare different levels of sensor concurrency

```
@op(ins={"time_sec": In(float)})
def sleep_op(context, time_sec):
    logger = get_dagster_logger()
    logger.info(f"Sleeping for {time_sec}")
    time.sleep(time_sec)


@graph
def sleep_graph():
    sleep_op()

sleep_jobs_perm = []
for i in range(60):
    sleep_jobs_perm.append(
        sleep_graph.to_job(
            name=f"sleep_job_perm{i}",
            executor_def=in_process_executor,
            config=config_from_files(
                [
                    file_relative_path(__file__, os.path.join("..", "run_config", "load.yaml")),
                ]
            )
        )
    )

def sensor_evaluation_fn(context: SensorEvaluationContext) -> Union[SkipReason, RunRequest]:
    return RunRequest(run_key=datetime.now().strftime("%y%m%d%H%M"), tags={"requested_at": str(datetime.utcnow())})

sleep_sensors_perm = [
    SensorDefinition(
        job=job, name=f"sensor_perm_{job.name}", minimum_interval_seconds=1, evaluation_fn=sensor_evaluation_fn
    )
    for job in sleep_jobs_perm
]
```
As one can see below, the number of sensor ticks is rapidly decreasing with the increasing level of concurrency. The sensor is evaluated only once per minute at 40 sensors. I consider this interval to be unsatisfactory, as this might be already handled by scheduled job (totally losing the benefit of the lightweight sensor). Actually, the lowest tick interval is close to 5s. 

![test_sensors_1s_sensor_run_count_16workers](https://user-images.githubusercontent.com/11676900/209978946-0cd002ed-0d8c-4cae-aaa7-d81605968912.png)

I tried to optimize this behavior in several ways. The changes were made step by step in isolated manner. 

At first, I tried to increase the number of sensor workers at the daemon side, but the impact was insignificant (at least at 20 concurrent sensor runs).

![test_sensors_1s_20_jobs_sensor_run_count_workers](https://user-images.githubusercontent.com/11676900/209981256-a0b01940-b94a-477c-a574-e49da10136af.png)

At second, I tried to increase `--max_workers` on the `dagster api grpc` (api_workers in the legend). However, the impact was again negligible as one can see from the diagram below (at least at 20 concurrent sensor runs).

![test_sensors_1s_20_jobs_sensor_run_count_workers_daemon_api](https://user-images.githubusercontent.com/11676900/209982364-5b9170ee-1014-40ed-aeb9-556fa611b3ba.png)

At last, I gave a chance to a k8s native way to improve the performance and increased the number of replicas of the code location server. Again, there is a small improvement but almost negligible. Moreover, dagit was repeatedly reloading the code location in version 1.1.7 when the number of replicas >1. I didn't notice such annoying behavior in version 1.1.2.  

![test_sensors_1s_20_jobs_sensor_run_count_replicas](https://user-images.githubusercontent.com/11676900/209983333-e865613e-d343-42cc-928f-8f9025ef9391.png)

Unfortunately, sensors are of very limiting use in this situation. I believe that this issue is directly linked to opened issue #7763 and architectural ideas in issue #9623.

**Comment by gibsondan** [comment]
https://docs.dagster.io/deployment/dagster-instance#sensor-evaluation demonstrates how to do this, so closing out this issue (although the benchmarks posted here will be very helpful for future improvements so thank you for those!)

**Comment by babaMar** [comment]
@gibsondan
> https://docs.dagster.io/deployment/dagster-instance#sensor-evaluation demonstrates how to do this, so closing out this issue (although the benchmarks posted here will be very helpful for future improvements so thank you for those!)

getting 404 for this link
