### ISSUE TITLE
Can @dagit/core be packaged and released to npm

### ISSUE THREAD

**Issue by kukuyuhai** [dagster-io/dagster#4367]
I need to customize the UI interface of the development workbench, and can directly import some jsx components.

**Comment by bengotow** [comment]
Hey @kukuyuhai thanks for filing this - we're not planning to publish @dagit/core for now because we're still iterating on a lot of the interfaces and exported components, but I'd love to know more about the UI customization you're looking for. In the past we've thought about exposing hooks and specific regions of the app so it's easier to inject your own graphs / links etc. Could you expand on what you're hoping to do?

**Comment by hellendag** [comment]
Closing this for issue hygiene. If you have more details about what you have in mind, please let us know. :)
