### ISSUE TITLE
Steps -> Ops

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#4710]
0.13.0 presents an opportunity to get rid of the concept of steps in favor of ops. This will involve renaming top level concepts (step launchers), a large-scale rename in dagit, and a large-scale python refactor.

**Comment by schrockn** [comment]
So I'll have opinions here. This makes 100% sense in a world where there is a guaranteed bijection (1:1 relationship) between ops and the compiled steps.

We already have an example where this is not true: dynamic orchestration. 1 dynamic op can produce N steps, so that can be odd. And then we have use case that we haven't built it but is ever on the horizon: importing dbt models as ops/assets and then coalescing them into a single step for execution.

**Comment by dpeng817** [comment]
@schrockn that makes sense to me. I can't think of a way to reconcile how dynamic orchestration works with this rename.
