### ISSUE TITLE
repo gets unselected from filter when fails to reload

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#4758]
Whenever I fail to reload a repo and then later fix the problem, I end up needing to re-select it from the repo-switcher and unselect whatever repo took its place.

**Comment by hellendag** [comment]
What if we automatically add any repo that goes from an `error -> loaded` to the selected set in the left nav, e.g. even if you didn't have it selected before? The idea being that this is a repo that you are currently working on, so we may as well surface it in the nav.

This is in contrast to trying to track repo names in localStorage for repos that no longer exist in the workspace due to errors, which seems...a little troublesome.

**Comment by sryza** [comment]
That sounds like a fine solution to me.

**Comment by sryza** [comment]
A related issue is that, when the repo I'm working with fails to load, another repo will get auto-selected.  After I fix whatever issue was causing my repo to fail to load, I then need to unselect the one that got auto-selected.  Would it be possible to turn off that auto-selection?  It would require being in a state where no repos are selected, which I think is fine (actually better, because it helps me notice that the repo that I'm trying to work with failed to reload).
