### ISSUE TITLE
Nick not able to figure out publish scripts

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#499]
This appears to hang at some point. Just noting here to track issue because merging a bit of a hack into master.

**Comment by mgasner** [comment]
Probably because you don't have pypi creds available (https://github.com/dagster-io/dagster/blob/master/bin/publish.py#L269) -- can we surface this better?

**Comment by mgasner** [comment]
I'm going to close this since I think it's handled decently well by the warning that prints to stdout when the script is invoked. Feel free to reopen if you'd like me to investigate ways of getting this to fail more loudly. We could probably check for the existence of the required `~/.pypirc` file and bail if it isn't found.
