### ISSUE TITLE
enable finding which partitions aren't backfilled

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#5543]
I have a job with thousands of partitions. I know some of them are unfilled, but I don't know which ones. Before kicking off a backfill over all unfilled partitions, I want to know how many runs that would end up submitting and gut-check that those partitions actually need to be filled.

Bonus points for the ability to find partitions that haven't been filled since a given date. Or to somehow mark all partitions before a given date as stale.

**Comment by bengotow** [comment]
I think we have some of the "guts" of this feature in place - technically you can turn on the "colorize by age" option and adjust the date threshold slider to see which materializations are older than X, you just can't translate that into a selection for a materialization. Seems like it'd be nice to have a few "selection helpers" (eg: "select all <X date" or "select all unfilled") rather than a button that just says "Run all unfilled"

**Comment by sryza** [comment]
@bengotow the main difficulty is that the partitions you see on the screen are often only a tiny fraction of all the partitions for the job. Spotting gaps in the 30 rendered partitions isn't difficult, but how do you discover that there are some missing partitions months in the past?

**Comment by sryza** [comment]
We've made a bunch of improvements to the backfill UI since this was filed that significantly improve this situation, including reporting the number of runs that will be launched as well as showing all partitions, not just 30.
