### ISSUE TITLE
auto retry not triggering for dagster framework errors

### ISSUE THREAD

**Issue by peterbaccaroshell** [dagster-io/dagster#6157]
## Summary

I have a job that will trigger a retry automatically when there is an error in the job by raising the RetryRequested exception.

There are situations however where there are failures in the Dagster framework before the job is started and in these instances, the retries are not being triggered.

## Reproduction

Create a daily partitioned job that raises a RetryRequested exception randomly and set the max_retries to 2 and seconds_to_wait to 10.  Perhaps ass a delay within the job to represent some work being performed.

Run a backfill for a year and check that all failures have triggered the 2 retries.

## Dagit UI/UX Issue Screenshots

![image](https://user-images.githubusercontent.com/74666079/148793424-be121416-1120-4db2-a6ea-eb06e8ac19ee.png)

![image](https://user-images.githubusercontent.com/74666079/148793446-d9a167c2-035b-4728-b461-5938bf6f2b98.png)

## Additional Info about Your Environment

Dagster version 0.13.13 running in AWS.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by dpeng817** [comment]
I think it's intentional that a retry would not occur if the run is failing before starting - retries are designed around non-deterministic error behavior within the business logic of your job. 

I wonder if these framework errors are pointing to a larger issue. Were you able to get past them by manually re-running a few times? Or were they consistently failing?

**Comment by peterbaccaroshell** [comment]
@dpeng817 I can understand that the RetryRequested exception in the custom code wouldn't come into play in this scenario as the job hasn't been started however since the job that was queued hasn't been started due to an error I would expect the framework itself to handle this by retrying itself.
The two framework errors above should be looked too at as these should not be occurring however when these framework errors occur as the job hasn't been started there appears to be no way to generate alerts (e.g. email via failure sensor) which is an issue.
When manually re-executing the failed jobs they all run successfully so there appears to be a race condition during backfills that cause some of the jobs to fail.  These framework errors happen quite consistently during backfills.

**Comment by johannkm** [comment]
Apologies for the delay in responding here- this spring we shipped automatic run retries. Instead of being scoped to a particular step they apply for the whole run, and cover system failures like this one (they cover any time that a run fails). You can check them out here: https://docs.dagster.io/deployment/run-retries
