### ISSUE TITLE
GraphDefinition.to_job(...)'s config argument is too strict with validation

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#6325]
When providing run config to a job via `GraphDefinition.to_job(...)`, it's convenient to receive errors in config at definition time rather than during execution. However, we also call post-processing validation on the config, which attempts to resolve everything down into concrete values. This can be problematic, for example, in the case of the StringSource config type. post-processing will attempt to resolve the StringSource down into an actual environment variable, which you might not have defined on your local machine, for example. Can lead to annoying situations.

A better solution would be to perform only config validation, and leave post-processing to happen during execution.

**Comment by dwallace0723** [comment]
Thanks for filing @dpeng817! This bug is hitting us pretty hard right now. Our main goal is to facilitate the use of secrets in configuration **without** exposing them in the UI, which the `_Source` config types seem perfect for. However, it seems like the only way to get these play nicely with job construction via `.to_job()` is to have every env var set on every environment/machine. Right now, this isn't realistic for us.
