### ISSUE TITLE
AWS ECS Tasks

### ISSUE THREAD

**Issue by peterdudfield** [dagster-io/dagster#6362]
## Use Case
It would be great to have dagster operator that can start ECS tasks. 

This means that various ECS tasks could be orchestrated using the dagster workflows.

I'm fairly new to Dagster so I'm sorry if there is already a feature

## Ideas of Implementation
ECSTask perhaps would take the following options
- ecs cluster
- ecs task arn, or ecs task family
- vpc + subnet to run the task on
- optional extras to overwrite things

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @peterdudfield - the first thing that we're likely to build along these lines is an ECS *executor* in Dagster: https://docs.dagster.io/deployment/executors#executors

which would allow you to configure your jobs so that Dagster automatically spins up a new ECS task for you and then runs your op code within that task.

That's a bit different from an op that itself manages an ECS task, but has some nice benefits: you can run the same op locally and in ECS without needing to change any code, for example, which can be really nice for local development and testing - and you get the full benefits of Dagster's event log and programming model. The main downside is that it can only run ops - you can't run an arbitrary task that isn't an op.

I'd be curious if an ECS executor would satisfy the use case that let to file this, or if it's a hard requirement for you that the op itself spin up an ECS task.

**Comment by peterdudfield** [comment]
Thanks @gibsondan for getting back to me. 

Yea, I was hoping to run some AWS tasks I already have defined. This is because I have docker files ready to go. 

My current thinking is to switch the Kubernetes and then use [this](https://docs.dagster.io/_apidocs/libraries/dagster-k8s#kubernetes-dagster-k8s). Do you think this is a sensible approach?

I'm pretty new to dagster, so please do point out something if I have obviously missed it.

**Comment by peterdudfield** [comment]
Thanks very much. Those examples are useful. I can imagine something similar with boto3

**Comment by peterdudfield** [comment]
I'm happy for the issue to be closed, if you like
