### ISSUE TITLE
414 Request-URI Too Large for "Open in Playground"

### ISSUE THREAD

**Issue by blerner-dd** [dagster-io/dagster#6555]
## Summary

There's a historical run in a pipeline. I go to the pipeline page of one of my piplines, the runs view, click on the three dots, click "Open in Playground" (see screenshot) and then I get a 414 Request Too Large.
I can't paste the link here because of sensitive data, but I just checked and, with percent encodings, it is 21000 characters long.

I think you guys should move data from query params to the body.

## Reproduction
Try opening the playground for a job whose configuration is long enough to cause a `414`

## Dagit UI/UX Issue Screenshots
![image](https://user-images.githubusercontent.com/89089653/153494079-39a95dc5-9141-4fcb-9f76-82928173cdce.png)

## Additional Info about Your Environment
Running dagster `0.12.12`

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment]
I don't think we can really make this a POST since its purpose is to populate localStorage with the config value, but I think we can add a route that will load the config based on the run ID. This will allow permalinking to a preconfigured launchpad without having to pass in any config as a GET param.
