### ISSUE TITLE
include assets on run page, even when run is from a job

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#6733]

**Comment by bengotow** [comment]
I think we can do this, but it could be a little more tricky for jobs because the default case (run the whole job) could yield a ton of assets. We need the "asset tags" to max out with a "see more" modal.

It looks like there's already a `run.assets` resolver, so maybe we can go ahead and build this? Right now assets can appear in tags here (Screenshot), but only if it's an __ASSET_GROUP run and not a normal run.

![image](https://user-images.githubusercontent.com/1037212/156206228-d2d96040-9e70-498a-8315-50a274868b12.png)
