### ISSUE TITLE
Dagit doesn't display description for SourceAsset

### ISSUE THREAD

**Issue by nicholsn** [dagster-io/dagster#6734]
## Summary

After loading the [Software-Defined Asset][sda] example and viewing the SourceAsset `sfo_q2_weather_sample` in Dagit, the description field does not populate with the text defined when the asset is initialized.

[sda]: https://docs.dagster.io/guides/dagster/software-defined-assets

## Reproduction

Define `SourceAsset` with a description field, then navigate to the Asset Definition page (e.g., after loading the SDA example).

```python
sfo_q2_weather_sample = SourceAsset(
    key=AssetKey("sfo_q2_weather_sample"),
    description="Weather samples, taken every five minutes at SFO",
)

```

## Dagit UI/UX Issue Screenshots

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/463344/154860495-6c51df8a-150b-4236-a4b5-31c693683a2b.png">

## Additional Info about Your Environment

Running 0.14.1

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment]
Thanks for reporting this @nicholsn ! We're aiming to fix this in a week or two.

**Comment by bengotow** [comment]
Hey @sryza, I traced this through Dagit and it looks like it would be rendering if the example was using AssetGroup instead of `spark_weather_job = build_assets_job`? I think the `sfo_q2_weather_sample` SourceAsset is actually being ignored and is never read from the JobDefinition into the RepositoryDefinition.source_assets list, and the asset definition you're seeing is one autogenerated in `external_data.py` (via `asset_keys_without_definitions`)

Maybe`examples/software_defined_assets` needs the same treatment we gave the toys in https://github.com/dagster-io/dagster/pull/6643?

**Comment by sryza** [comment]
Given that this works with our recommended `AssetGroup` API, I'm going to close this. I merged a change last week that updates the software-defined assets guide to use `AssetGroup` instead of `build_assets_job`. It will show up in next week's release.
