### ISSUE TITLE
Use Nothing as graph InputDefinition does not work as expected

### ISSUE THREAD

**Issue by boenshao** [dagster-io/dagster#7610]
## Summary

Being able to specify `Nothing` as Graph input, to achieve order-based execution of nested sub-graph.

## Reproduction

The below code:
```
@op(ins={"dummy": In(Nothing)})
def foo():
    ...

@graph(input_defs=[InputDefinition(name="dummy", dagster_type=Nothing)])
def g():
    foo()
```

Raise below error:

```
UserWarning: Error loading repository location repo.py:dagster.core.errors.DagsterInvalidDefinitionError: @graph 'g' decorated function does not have parameter(s) 'dummy', which are in provided input_defs. @graph decorated functions should only have keyword arguments that match input names and, if system information is required, a first positional parameter named 'context'.
```

This did get parsed successfully though:

```
@op(ins={"dummy": In(Nothing)})
def foo():
    ...

@graph(input_defs=[InputDefinition(name="dummy", dagster_type=Nothing)])
def g(dummy):
    foo(dummy)
```

## Additional Info about Your Environment

Python 3.8.12
Dagster 0.14.12

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by clairelin135** [comment]
Hi Boen. To clarify the behavior here, every graph is a container of ops. When a graph is executed, the nodes in the graph are flattened to a graph of leaf ops, so every input of a graph must map to an input of given op in the graph. Likewise, every output of an op in a graph must map to the graph's outputs. 

This is why the second code snippet works--because the "dummy" input has been mapped to a `Nothing` input of an op within the graph.

I'll update the error messaging to make this clearer in the future.
