### ISSUE TITLE
FIPS Compliance

### ISSUE THREAD

**Issue by faelin** [dagster-io/dagster#7657]
Is there any information available on Dagster's compliance (or lack thereof) with the FIPS 140 standard?

**Comment by rexledesma** [comment]
We can't make any statements on FIPS compliance in Dagster open-source since we have no control over the third-party modules that you install as a part of the Dagster (and related, e.g. Dagit) packages. NGINX [has a similar problem](https://www.nginx.com/blog/achieving-fips-compliance-nginx-plus/#FIPS-Compliance-with-NGINX-Open-Source) in regards to their FIPS compliance.

For [Dagster Cloud](https://dagster.io/cloud), our paid and hosted product, we don't have a timeline for achieving this compliance. However, we'd be happy to discuss it with you - please reach out in our [Slack](http://dagster.io/slack).
