### ISSUE TITLE
Way to close all launchpad tabs at once

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#8037]
From user:
> It would be nice to have a way to close all launchpad tabs at once, sometimes a bunch accumulate and it's a lot of clicking to dismiss each one, each requiring its own confirmation. Working with configs has otherwise gotten easier lately, which is great.

**Comment by sryza** [comment]
I pinged the user to comment here.

**Comment by tfederman** [comment]
That's right, sometimes I'm debugging/rerunning a pipeline several times and go from each failed run to the next by opening it in the launchpad.

Some of our run configs are long and at a glance it's hard to tell if the state of the launchpad contents are the yaml files loaded from disk, or the prior edited state that's been persisted client side. I'm not sure what the mechanism is for persisting that and when to expect it to clear. And sometimes I don't know or remember the state of the yaml files on disk since I could be switching between branches or pulling someone else's code. 

So the easiest way to reason about the launchpad contents before launching a new run is to start with a prior run, which is a clear known state.

**Comment by hellendag** [comment]
We'll be taking a look at changes to the Launchpad.

**Comment by rexledesma** [comment]
Resolved by https://github.com/dagster-io/dagster/pull/9981
