### ISSUE TITLE
Make execution plan subset creation actually only create the subset

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#812]
Right now creating an execution subplan involves creating the *entire* plan and then removing the unused nodes. Given that the most common use case is to create one node, this is quite inefficient.

**Comment by natekupp** [comment]
@schrockn is this still important? With changing run groupings, I imagine it'll be more common to construct subsets with more than one node.

Otherwise, agree this is inefficient, but seems like we should prioritize work like this based on results from a profiler vs. doing it preemptively. Thoughts?

**Comment by schrockn** [comment]
yeah no need to prioritize. i think this is more of a note to myself than anything

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by nancydyc** [comment]
#3089

**Comment by mgasner** [comment]
Can we close this until we think that execution plan construction is a performance issue?

**Comment by schrockn** [comment]
Yes let's just close it. It also may be effected by @alangenfeld's work on dynamic orchestration since we are now have the notion of partial execution plans
