### ISSUE TITLE
we should error when an asset has an empty-string group name

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#8667]
right now, we silently convert to "default"

```
from dagster import asset


@asset(group_name="")
def asset():
    ...
```

**Comment by erinkcochran87** [comment]
Triaging issues for this milestone - I'd say we could document this, but if the error message we surface is clear about the problem it might not be necessary.

**Comment by hassen-io** [comment]
Hi,

I'm suggesting a solution to this issue. I agree with the idea that using empty-string value is misleading, and might probably be the result of a dynamic naming that went wrong.

My suggestion is to create a check on assets validating a non-empty name if provided. You can find an implementation in the pull request.

However, as this is my first code contribution, I have the feeling I didn't covered all the use cases where this group name is set. If so, can you please point out my missing if any? In the meantime, I'll double check myself.

Happy to discuss more

**Comment by gautham18113** [comment]
Hello, I was looking for a first issue to contribute to. But it looks like this issue is already being handled [here](https://github.com/dagster-io/dagster/blob/dd0b7b091a4fe0733b4e02dfc0a4a2fc68a96a75/python_modules/dagster/dagster/_core/definitions/utils.py#L48-L49) and thrown [here](https://github.com/dagster-io/dagster/blob/dd0b7b091a4fe0733b4e02dfc0a4a2fc68a96a75/python_modules/dagster/dagster/_core/definitions/utils.py#L59-L62) ? The regex seems to handle empty strings, but correct me if I misunderstood.

**Comment by sryza** [comment]
@gautham18113 I just gave this a try:
```
from dagster import asset


@asset(group_name="")
def asset1():
    ...
```

The code ran successfully (which is not the desired behavior - it should error).

**Comment by Sierrra** [comment]
Hi @sryza !
I suggested a solution for the issue in #17221 .
Actually, simple fix of validate_group_name function won't work, because of side effects of group_name checks. I fixed it.
