### ISSUE TITLE
Nightly branch doesn't pick up minor version number

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#868]
![screenshot 2019-02-26 06 24 11](https://user-images.githubusercontent.com/28738937/53419714-31caed80-398f-11e9-8e67-0446433847a5.png)

**Comment by mgasner** [comment]
#1174

**Comment by schrockn** [comment]
![Screenshot 2019-04-16 08 21 30](https://user-images.githubusercontent.com/28738937/56222313-a8e04200-6020-11e9-872a-7e7ffbf34974.png)

There are still shenanigans happening here

**Comment by mgasner** [comment]
Where this stands is:
- tags are working fine on GH (https://github.com/dagster-io/dagster/releases/tag/20190427)
- builds have been failing for good, unrelated reasons (dev_env_setup.sh had issues, etc.)
- versions are not showing up on PyPI correctly, because our chosen %Y%m%d format isn't a valid PEP440 version
