### ISSUE TITLE
in sensors, enable wildcards when querying for materializations by asset key

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#8750]
E.g. "tell me about materializations for all assets with key prefix X" or "key suffix Y".

**Comment by samuelstuetz** [comment]
I have considered partitions, but whether a customer partition exists may change depending on them having bought a feature. So the partitions would change quite a lot in a dynamic way, making this quite confusing.
It would make more sense to make them different assets as they are physically and business logically wise different assets they are just of the same type.
Sort of like different objects of the same class in code speak. However I would like to handle them as a group and subscribe to all sensor events of that type in order to make the code more manageable.

**Comment by sryza** [comment]
Closing as a duplicate of https://github.com/dagster-io/dagster/issues/8750
