### ISSUE TITLE
Launch dialog for multiple partitioned assets erroneously says "Upstream Data Missing" 

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#9291]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/654855/183514510-6141fa0a-5f1b-4092-89e1-87ccd7f68aad.png">

Here's the asset graph:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/654855/183514674-71e955f2-7c49-480d-9ab1-08aa6e1bc2ab.png">

None of the assets have been materialized yet.

To reproduce:
- Launch the fully featured project example in Dagit
- Click the "core" asset group
- Click "Materialize All"

**Comment by hellendag** [comment]
@bengotow may have already fixed this and will take a look.

**Comment by bengotow** [comment]
Can confirm this is no longer happening in this scenario. This was happening before because we had a place we were trying to check asset key equality and doing it incorrectly.

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/1037212/187277192-50b31ee0-9cee-426a-a71c-9d6cdd657201.png">
