### ISSUE TITLE
dagster-dbt, can we select the dbt models folder? or can only use the direct model only?

### ISSUE THREAD

**Issue by ericwijaya001** [dagster-io/dagster#9356]
### What's the issue or suggestion?

For example, I want to run all the models in the models/finance folder, is there a way to run only the models in the models/finance folder? This can be done in dbt by dbt run --select models/finance.

I tried in the following way but can't
finance_job = define_asset_job("all_finance_job", selection="models/finance")

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by flvndh** [comment]
Hi @ericwijaya001 you can use the `select` parameter of `load_assets_from_dbt_manifest` and `load_assets_from_dbt_project` to do that.

**Comment by OwenKephart** [comment]
@flvndh 's answer is correct -- just to expand on it a bit more, the "selection" parameter in `define_asset_job` is different from the `select` parameter when running `dbt`.

This is because the `define_asset_job` parameter is selecting over ALL Dagster assets (dbt or non-dbt), and so they use different (although similar syntax). The string-based syntax in Dagster is currently limited to selecting specific asset keys, with `/` as the delimiter, along with upstream/downstream selections (using `+` or `*`).

So, the selection `finance_job = define_asset_job("all_finance_job", selection="models/finance")` means "select exactly the `AssetKey(["models", "finance"])`. You can learn more about Dagster's selection here: https://docs.dagster.io/_apidocs/assets#dagster.AssetSelection

By default, Dagster will separate dbt models into different Asset groups based on their folder, which I believe should mean that all of your models/finance assets will be in the `finance` Asset group. If this is the case, you can select them using `finance_job = define_asset_job("all_finance_job", selection=AssetSelection.groups("finance"))`. You can also customize which group each model shows up in using the `node_info_to_group_fn` argument (a function which takes a dictionary of info about the node and returns a group for it).

dbt has a very flexible selection syntax for its models, which you can take advantage of with the `select` parameter when loading assets (which will limit which models get loaded as assets in the first place).

**Comment by sryza** [comment]
If we had hierarchical groups, we could handle this more natively in Dagster.
