### ISSUE TITLE
[dagster-dbt] load_assets_from_dbt_project should not default to using a profiles_dir of /path/to/dbt/config

### ISSUE THREAD

**Issue by OwenKephart** [dagster-io/dagster#9688]
### Dagster version

0.16.x

### What's the issue?

The dbt_cli_resource does not use this default, and it's fine for this flag to be left out when invoking dbt commands, so we should not use our own default.

We should wait until dagster-dbt 1.0 to make this change, as it is breaking.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jayhale** [comment]
Agreed.  This nuance took me a while to figure out when initially setting up our dbt project.

**Comment by rexledesma** [comment]
This is resolved when using `DbtCli` and `@dbt_assets`, since the user must explicitly specify the `--profiles-dir` in `global_config`. Otherwise, we default to the current working directory (the `project_dir`) instead of `${project_dir}/config`. This is similar to guidance from https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles#advanced-customizing-a-profile-directory.

See https://github.com/dagster-io/dagster/discussions/14477 for more details.
