### ISSUE TITLE
Make all additional asset metadata display in a `pre` element by default

### ISSUE THREAD

**Issue by m-o-leary** [dagster-io/dagster#9777]
### What's the use case?

I am using `dagster-dbt` to materialize assets in a dbt project.

I am pulling out the compiled SQL from an asset in a function passed to the r`untime_metadata_fn` argument of the l`oad_assets_from_dbt_project` function. 

The idea is to be able to easily analyse and rerun the exact query from an asset materialization for debugging purposes whilst viewing the asset graph.

The SQL shows up nicely formatted in the `ASSET_MATERIALIZATION` event popup within the execution view but it would be nice to have it display formatted in the table on the right in the asset graph view also (which it doesn't).

I can see that the raw SQL is shown  further down in a pre element within a td

### Ideas of implementation

Ideal solution would be that the compiled SQL show up with the same formatting as the raw SQL from a dbt model.

I think a simple implementation could be to just have all the cells displaying custom asset metadata have a pre tag inside?

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
(copying answer over from slack) The raw sql renders nicely because we automatically render asset descriptions as markdown in the asset details page. The description we attach to the asset is generated [here](https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py?L144) (basically just wrap it in triple back ticks).

By default, if you just attach a bit of metadata like {"compiled_sql": "<compiled sql goes here>"}, this will just be formatted as normal text (even if you wrap it in triple backticks). Your intuition about using MetadataValue is totally correct though -- if instead have your metadata value be MetadataValue.md (md = markdown), then things will render properly. So the full solution would be passing {"compiled_sql": MetadataValue.md("```<compiled sql goes here>```")}
