### ISSUE TITLE
[docs] - Add docs for env vars and secrets in Dagster Cloud 

### ISSUE THREAD

**Issue by erinkcochran87** [dagster-io/dagster#9817]
This issue serves to track research / content work for adding documentation about environment variables and secrets to Dagster Cloud.

---

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment]
The difficulties I encountered:
- I couldn't figure out how to follow this direction: https://docs.dagster.io/dagster-cloud/deployment/serverless#adding-secrets.
- The directions here were different and insufficient: https://docs.dagster.io/dagster-cloud/developing-testing/branch-deployments/using-branch-deployments-with-github#step-42-configure-github-action-secrets.

It turned out the solution was to uncomment
```
          env_vars: ${{ toJson(secrets) }}
```
in my `.github/workflows/branch_deployments.yaml` and `.github/workflows/deploy.yaml`
