### ISSUE TITLE
load_assets_from_dbt_github_project

### ISSUE THREAD

**Issue by sryza** [dagster-io/dagster#9874]
relevant user requests:
- https://dagster.slack.com/archives/C01U954MEER/p1664789785018309
  > There isn't currently a direct way to do this, but here's what some users do:
  > - compile the dbt project to create a manifest.json file
  > - use load_assets_from_dbt_manifest to create Dagster assets from that manifest file

**Comment by rexledesma** [comment]
Closing this because:
- We don't recommend compiling a dbt project at run time: https://github.com/dagster-io/dagster/pull/16043.
- We have introduced `dagster-dbt project scaffold` to streamline the creation of a Dagster project from a dbt project in open source: https://github.com/dagster-io/dagster/pull/16040
- With the Dagster Cloud dbt NUX [introduced in our blog post](https://dagster.io/blog/migrate-off-dbt-cloud), we also streamline the creation of a Dagster project from a dbt project hosted in git.

**Comment by sryza** [comment]
👍
