### ISSUE TITLE
dagster-dbt incorrectly produces asset observations for all assets on every asset

### ISSUE THREAD

**Issue by jayhale** [dagster-io/dagster#9952]
### Dagster version

dagster, version 1.0.12

### What's the issue?

When using dagster-dbt, the run job produces asset observations for every asset on every asset.

E.g., if a dbt project has two assets:
```
dbt_project.yml
models/model_a.sql
models/model_b.sql
```

Building the dbt project as a Dagster job results in 4 asset observations instead of 2.

The resulting data is clearly incorrect, e.g.:
![image](https://user-images.githubusercontent.com/31579448/194938720-2f177123-cfac-4c40-916d-f1975c30488f.png)

### What did you expect to happen?

Only 1 asset observation should be recorded for each dbt asset when building the dbt project with a Dagster job.

### Deployment type

Dagster Cloud

### Deployment details

Dagster Cloud Serverless

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment]
The expected behavior is to have one AssetObservation event generated for each test on each model when that model is materialized using Dagster, which I believe is what's happening here.

Unfortunately, the metadata on that AssetObservation event (which should describe the result of the test) includes essentially identical fields to to the AssetMaterialization event (which should describe the result of running the model). In this case, Compilation Duration is a property both of the model and the tests associated with the model, but they all get lumped together into a single chart.

The fix (which will be implemented in this week's release) is to excise the largely useless timing metadata from the observation and just put the test result metadata on the AssetObservation event.
