### ISSUE TITLE
Handling broken pipelines in dagit

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#998]
Right now when something is wrong w/ a pipeline definition, `dagit` will spew the error to the console and refuse to load.

Instead, it would be great to show the dagit UI and highlight which pipeline in the repository is broken

**Comment by schrockn** [comment]
@natekupp can you specify more precisely what type of error (e.g. a syntax error? Invalid Definition Error?) causes this bad experience

**Comment by tinkerware** [comment]
I ran across an issue that seems related. Going over the Inputs tutorial at https://dagster.readthedocs.io/en/stable/sections/learn/tutorial/inputs.html I ran the test pipeline first with an untyped solid, and then *changed the same solid* to use type signatures. The `runs` view refused to load with a GraphQL error: `
GraphQL error] Pipeline "hello_inputs_pipeline" config errors: Error 1: Type failure at path "root:solids:add_hello_to_word:inputs:word:value" on type "String". Value at path root:solids:add_hello_to_word:inputs:word:value is not valid. Expected "String".`

The backtrace I see in the console is:

```
An error occurred while resolving field LogMessageConnection.nodes
Traceback (most recent call last):
  File "/Users/cagatay/.pyenv/versions/3.7.4/envs/dagster-3.7/lib/python3.7/site-packages/graphql/execution/executor.py", line 450, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/cagatay/.pyenv/versions/3.7.4/envs/dagster-3.7/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/Users/cagatay/.pyenv/versions/3.7.4/envs/dagster-3.7/lib/python3.7/site-packages/dagster_graphql/schema/runs.py", line 184, in resolve_nodes
    RunConfig(mode=self._pipeline_run.mode),
  File "/Users/cagatay/.pyenv/versions/3.7.4/envs/dagster-3.7/lib/python3.7/site-packages/dagster/core/execution/api.py", line 70, in create_execution_plan
    environment_config = create_environment_config(pipeline, environment_dict, run_config)
  File "/Users/cagatay/.pyenv/versions/3.7.4/envs/dagster-3.7/lib/python3.7/site-packages/dagster/core/execution/context_creation_pipeline.py", line 50, in create_environment_config
    raise DagsterInvalidConfigError(pipeline, result.errors, environment_dict)
dagster.core.errors.DagsterInvalidConfigError: Pipeline "hello_inputs_pipeline" config errors:
    Error 1: Type failure at path "root:solids:add_hello_to_word:inputs:word:value" on type "String". Value at path root:solids:add_hello_to_word:inputs:word:value is not valid. Expected "String".
```

This is somewhat annoying, since making type changes to your solids that are incompatible with previous runs in your history will blow up Dagit, until you manually excise the problematic runs from history (haven't tried this yet, so not sure if it's possible). Is this the same problem this issue is addressing and should create a new one?

**Comment by sephib** [comment]
We have the same problem -
It is quite annoying since we need to remember not to view "stale" pipelines while reviewing the logs - otherwise `dagit` crashes

**Comment by alangenfeld** [comment]
@sephib what version are you on and do you have a stack trace? We definitely shouldn't be crashing.

**Comment by schrockn** [comment]
@alangenfeld if there is a syntax error in their pipeline definition construction dagit isn't going to load.

**Comment by schrockn** [comment]
@sephib and @tinkerware a lot of issues you have seen are already resolved (we now persist execution plan structures instead of recompiling them). Post 0.8.0 dagit will run in a completely different process than user code so user syntax errors will not effect dagit at all. Thanks for bearing with us and for the excellent feedback!

**Comment by sephib** [comment]
> @sephib what version are you on and do you have a stack trace? We definitely shouldn't be crashing.

version 0.7.3 (waiting for a conda version update)  
since the environment is off the grid - i can't send you a stack trace. 
The error is 
> dagster.core.errors.DagsterInvalidConfigError: ...
> graphql.error.located_error.GraphQLLocatedError: error in config for pipeline pipeline_name

**Comment by natekupp** [comment]
@mgasner is this still an issue post- the gRPC / user code separation work?

**Comment by schrockn** [comment]
Yes but I believe this moved the bug to another layer in the UI. See https://github.com/dagster-io/dagster/issues/2718

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by hellendag** [comment]
Closing in favor of #2718.
